import test from 'node:test';import assert from 'node:assert/strict';import {writeFile,chmod,mkdir,symlink} from 'node:fs/promises';import {join,dirname} from 'node:path';
import {storeFixture} from '../helpers/store-fixture.ts';
import {captureProPlugins} from '../../src/pro/capture.ts';
import {ownedProDiagnostic,REMOTE_PLUGIN_ID,CHROME_PLUGIN_ID} from '../../src/pro/preflight.ts';
import {fingerprintRequiredPlugins,pluginFilesBusy} from '../../src/pro/plugin-files.ts';
import {pluginInventoryBusy} from '../../src/pro/inventory.ts';
async function executable(path:string,output:string,exit=0){await writeFile(path,`#!${process.execPath}\nprocess.stdout.write(${JSON.stringify(output)});process.exitCode=${exit};\n`);await chmod(path,0o700);}
async function inventory(root:string){const rows=[];for(const [pluginId,name] of [[REMOTE_PLUGIN_ID,'remote'],[CHROME_PLUGIN_ID,'chrome']]){const path=join(root,name!);await mkdir(path);await writeFile(join(path,'plugin.json'),'content');rows.push({pluginId,installed:true,enabled:true,version:'1',source:{path}});}return JSON.stringify({installed:rows});}
test('actual native inventory child and native filesystem worker produce exact captured evidence',async()=>storeFixture(async path=>{const raw=await inventory(dirname(path));await executable(path,raw);const captured=await captureProPlugins(path);assert.equal(captured.inventory,raw);assert.equal(captured.fingerprint,await fingerprintRequiredPlugins(raw));assert.ok(Object.isFrozen(captured));assert.equal(pluginInventoryBusy(),false);assert.equal(pluginFilesBusy(),false);}));
test('inventory spawn and nonzero exit map only to query-failed diagnostics',async()=>storeFixture(async path=>{for(const create of [false,true]){if(create)await executable(path,'failed',7);await assert.rejects(captureProPlugins(path),(e:unknown)=>ownedProDiagnostic(e)?.code==='PluginInventoryQueryFailed');}assert.equal(pluginInventoryBusy(),false);}));
test('malformed installed source metadata retains inventory-invalid diagnostic',async()=>storeFixture(async path=>{await executable(path,'{"installed":[]}');await assert.rejects(captureProPlugins(path),(e:unknown)=>ownedProDiagnostic(e)?.code==='PluginInventoryInvalid');assert.equal(pluginFilesBusy(),false);}));
test('unverified plugin content is not mislabeled as browser unavailability',async()=>storeFixture(async path=>{const raw=await inventory(dirname(path));await symlink(path,join(dirname(path),'remote','link'));await executable(path,raw);await assert.rejects(captureProPlugins(path),(e:unknown)=>{const d=ownedProDiagnostic(e);assert.equal(d?.stage,'PluginContent');assert.equal(d?.code,'PluginContentUnverified');assert.equal(d?.publicMessage,'The installed plugin files could not be verified; Chrome availability was not tested.');return true;});}));
test('pre-cancelled capture preserves exact reason and submits neither native owner',async()=>{const stop=new AbortController(),reason={cancel:true};stop.abort(reason);await assert.rejects(captureProPlugins('/missing',stop.signal),e=>e===reason);assert.equal(pluginInventoryBusy(),false);assert.equal(pluginFilesBusy(),false);});
