import test from 'node:test';import assert from 'node:assert/strict';import {writeFile,chmod,readFile} from 'node:fs/promises';
import {storeFixture} from '../helpers/store-fixture.ts';
import {readCodexPluginInventory,pluginInventoryBusy,PluginInventoryError,type PluginInventoryFailure} from '../../src/pro/inventory.ts';
import {OwnedWorkerBusyError} from '../../src/runtime/owned-worker-slot.ts';
async function fixture(code:string,run:(path:string)=>Promise<void>){await storeFixture(async path=>{await writeFile(path,`#!${process.execPath}\n${code}\n`);await chmod(path,0o700);await run(path);});}
const kind=(wanted:PluginInventoryFailure)=>(e:unknown)=>{assert.ok(e instanceof PluginInventoryError);assert.equal(e.kind,wanted);return true;};
test('actual native inventory uses literal argv, no shell, preserving UTF8 and BOM',async()=>fixture('if(JSON.stringify(process.argv.slice(2))!==JSON.stringify(["plugin","list","--json"]))process.exit(9);process.stdout.write("\\ufeff한국어😀");',async path=>{assert.equal(await readCodexPluginInventory(path),'\ufeff한국어😀');assert.equal(pluginInventoryBusy(),false);}));
test('missing executable reports native spawn failure after worker is reaped',async()=>{await assert.rejects(readCodexPluginInventory('/definitely-missing-inventory-executable'),kind('Spawn'));assert.equal(pluginInventoryBusy(),false);});
test('nonzero exit prefers stderr and truncates Unicode scalars after Rust trim',async()=>fixture('process.stdout.write("wrong");process.stderr.write("\\u0085"+"😀".repeat(1100)+" ");process.exitCode=7;',async path=>{await assert.rejects(readCodexPluginInventory(path),(e:unknown)=>{assert.ok(e instanceof PluginInventoryError);assert.equal(e.kind,'Exit');assert.equal(e.exitCode,7);assert.equal(e.message,'Codex plugin inventory query failed with exit code 7: '+'😀'.repeat(1000));return true;});}));
test('invalid UTF8 cannot be returned as inventory JSON',async()=>fixture('process.stdout.write(Buffer.from([0xc3,0x28]));',async path=>{await assert.rejects(readCodexPluginInventory(path),kind('Utf8'));assert.equal(pluginInventoryBusy(),false);}));
test('oversized stdout and stderr are rejected even with zero exit',async()=>{for(const pipe of ['stdout','stderr'])await fixture(`process.${pipe}.write(Buffer.alloc(1048577,120));`,async path=>{await assert.rejects(readCodexPluginInventory(path),kind('TooLarge'));assert.equal(pluginInventoryBusy(),false);});});
test('caller cancellation joins native worker and prevents another inventory launch',async()=>fixture('setTimeout(()=>process.stdout.write("done"),150);',async path=>{
 const stop=new AbortController(),reason={cancel:true};const result=readCodexPluginInventory(path,stop.signal);const observed=result.then(()=>({ok:true as const}),error=>({ok:false as const,error}));assert.equal(pluginInventoryBusy(),true);stop.abort(reason);
 await assert.rejects(readCodexPluginInventory(path),OwnedWorkerBusyError);const end=await observed;assert.equal(end.ok,false);if(!end.ok)assert.equal(end.error,reason);assert.equal(pluginInventoryBusy(),false);
}));
test('pre-cancelled request creates no native owner',async()=>{const stop=new AbortController(),reason={stop:true};stop.abort(reason);await assert.rejects(readCodexPluginInventory('/missing',stop.signal),e=>e===reason);assert.equal(pluginInventoryBusy(),false);});
test('actual ten-second native timeout reaps direct child before releasing worker capacity',{timeout:15000},async()=>fixture('require("node:fs").writeFileSync(process.argv[1]+".pid",String(process.pid));setInterval(()=>{},1000);',async path=>{await assert.rejects(readCodexPluginInventory(path),kind('Timeout'));assert.equal(pluginInventoryBusy(),false);const pid=Number(await readFile(path+'.pid','utf8'));assert.ok(Number.isSafeInteger(pid)&&pid>0);assert.throws(()=>process.kill(pid,0),(e:unknown)=>(e as NodeJS.ErrnoException).code==='ESRCH');}));
test('two individually valid streams may together exceed one MiB without false rejection',async()=>fixture('process.stdout.write("x".repeat(600000));process.stderr.write("y".repeat(600000));',async path=>{assert.equal((await readCodexPluginInventory(path)).length,600000);}));
test('exact one-MiB stdout and stderr boundaries are both accepted',async()=>fixture('process.stdout.write("x".repeat(1048576));process.stderr.write("y".repeat(1048576));',async path=>{assert.equal((await readCodexPluginInventory(path)).length,1048576);}));
