import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {mkdir,writeFile} from 'node:fs/promises';import {existsSync,readFileSync} from 'node:fs';import {dirname,join} from 'node:path';
import {storeFixture} from '../helpers/store-fixture.ts';import {resolveProWorkingDirectory,PromptPreprocessError,proProjectReaderBusy} from '../../src/pro/project.ts';
const schema='CREATE TABLE threads(id TEXT PRIMARY KEY,title TEXT,cwd TEXT,updated_at INTEGER,rollout_path TEXT,model TEXT,reasoning_effort TEXT,tokens_used INTEGER,archived INTEGER,archived_at INTEGER)';
function setup(path:string){const db=new DatabaseSync(path);db.exec(schema);return db;}
test('exact distinct original active threads retain their own project directory',async()=>storeFixture(async path=>{const a=join(dirname(path),'a'),b=join(dirname(path),'b');await mkdir(a);await mkdir(b);const db=setup(path);try{for(const [id,cwd] of [['a',a],['b',b]])db.prepare('INSERT INTO threads(id,cwd,archived) VALUES(?,?,0)').run(id!,cwd!);}finally{db.close();}const before=readFileSync(path);assert.equal(await resolveProWorkingDirectory(path,'a'),a);assert.equal(await resolveProWorkingDirectory(path,'b'),b);assert.deepEqual(readFileSync(path),before);}));
test('missing/archived original identity never falls back to another valid project',async()=>storeFixture(async path=>{const db=setup(path);try{db.prepare('INSERT INTO threads(id,cwd,archived) VALUES(?,?,1)').run('old',dirname(path));db.prepare('INSERT INTO threads(id,cwd,archived) VALUES(?,?,0)').run('other',dirname(path));}finally{db.close();}for(const id of ['old','missing','OTHER'])await assert.rejects(resolveProWorkingDirectory(path,id),(e:unknown)=>e instanceof PromptPreprocessError&&e.publicMessage.endsWith('the original active thread was not found'));}));
test('relative blank missing and regular-file project paths all fail closed',async()=>storeFixture(async path=>{const db=setup(path);try{db.exec("INSERT INTO threads(id,archived) VALUES('t',0)");for(const cwd of ['',' ','relative',join(dirname(path),'missing'),path]){db.prepare("UPDATE threads SET cwd=? WHERE id='t'").run(cwd);await assert.rejects(resolveProWorkingDirectory(path,'t'),PromptPreprocessError);}}finally{db.close();}}));
test('strict original full-row decoding rejects malformed unrelated title before using valid cwd',async()=>storeFixture(async path=>{const db=setup(path);try{db.prepare("INSERT INTO threads(id,title,cwd,archived) VALUES('t',CAST(x'ff' AS TEXT),?,0)").run(dirname(path));}finally{db.close();}await assert.rejects(resolveProWorkingDirectory(path,'t'),PromptPreprocessError);}));
test('missing database is never created, and pre-cancel creates no reader',async()=>storeFixture(async path=>{await assert.rejects(resolveProWorkingDirectory(path,'t'),PromptPreprocessError);assert.equal(existsSync(path),false);const stop=new AbortController(),reason={stop:true};stop.abort(reason);await assert.rejects(resolveProWorkingDirectory(path,'t',stop.signal),e=>e===reason);assert.equal(proProjectReaderBusy(),false);}));
test('abort during actual worker startup preserves reason only after reader exits',async()=>storeFixture(async path=>{const db=setup(path);try{db.prepare("INSERT INTO threads(id,cwd,archived) VALUES('t',?,0)").run(dirname(path));}finally{db.close();}const stop=new AbortController(),reason={abort:true},work=resolveProWorkingDirectory(path,'t',stop.signal);const outcome=work.then(value=>({ok:true as const,value}),error=>({ok:false as const,error}));assert.equal(proProjectReaderBusy(),true);stop.abort(reason);const result=await outcome;assert.equal(result.ok,false);if(!result.ok)assert.equal(result.error,reason);assert.equal(proProjectReaderBusy(),false);}));
