import test from 'node:test';import assert from 'node:assert/strict';import {writeFile,mkdir,chmod,unlink} from 'node:fs/promises';import {dirname,join} from 'node:path';import {DatabaseSync} from 'node:sqlite';
import {storeFixture} from '../helpers/store-fixture.ts';
import {startRuntimeResident} from '../../src/runtime/discord-runtime/resident-startup.ts';
import {ProPromptRuntime,type ProRemoteConnection} from '../../src/pro/runtime.ts';
import {PromptPreprocessError} from '../../src/pro/project.ts';
import {REMOTE_PLUGIN_ID,CHROME_PLUGIN_ID,type ProRuntimeDiagnostic} from '../../src/pro/preflight.ts';
import {rewriteProPrompt,formatLocalDevicePrompt} from '../../src/pro/prompt.ts';
const render=(e:unknown)=>e instanceof Error?e.message:'native error';
const native="import readline from 'node:readline';readline.createInterface({input:process.stdin}).on('line',l=>{const m=JSON.parse(l);if(m.id!==undefined)process.stdout.write(JSON.stringify({id:m.id,result:{}})+'\\n');});";
async function fixture(run:(f:{root:string;state:string;executable:string;project:string;plugin:string;server:Awaited<ReturnType<typeof startRuntimeResident>>;reports:ProRuntimeDiagnostic[];capture:(remote?:ProRemoteConnection|null)=>Promise<ProPromptRuntime>;repairInventory:()=>Promise<void>})=>Promise<void>){await storeFixture(async mirror=>{
 const root=dirname(mirror),state=join(root,'state.sqlite'),executable=join(root,'codex-fixture'),project=join(root,'original-project'),plugin=join(root,'installed-remote');await mkdir(project);await mkdir(plugin);const chrome=join(root,'installed-chrome');await mkdir(chrome);await writeFile(join(plugin,'plugin.json'),'remote');await writeFile(join(chrome,'plugin.json'),'chrome');const manifest=join(root,'plugins/codex-discord-remote/.codex-plugin');await mkdir(manifest,{recursive:true});await writeFile(join(manifest,'plugin.json'),'{"version":"1"}');
 const db=new DatabaseSync(state);try{db.exec('CREATE TABLE threads(id TEXT PRIMARY KEY,title TEXT,cwd TEXT,updated_at INTEGER,rollout_path TEXT,model TEXT,reasoning_effort TEXT,tokens_used INTEGER,archived INTEGER,archived_at INTEGER)');db.prepare("INSERT INTO threads(id,cwd,archived) VALUES('original',?,0)").run(project);}finally{db.close();}
 const raw=JSON.stringify({installed:[{pluginId:REMOTE_PLUGIN_ID,installed:true,enabled:true,version:'1',source:{path:plugin}},{pluginId:CHROME_PLUGIN_ID,installed:true,enabled:true,version:'2',source:{path:chrome}}]});
 const repairInventory=async()=>{await writeFile(executable,`#!${process.execPath}\nprocess.stdout.write(${JSON.stringify(raw)});\n`);await chmod(executable,0o700);};await repairInventory();
 const server=await startRuntimeResident({process:{executable:process.execPath,arguments:['--input-type=module','-e',native],environment:{}},clientInfo:{name:'pro-fixture',title:'fixture',version:'1'}},mirror,'runtime',null,render),reports:ProRuntimeDiagnostic[]=[];
 const capture=(remote:ProRemoteConnection|null={deviceId:'device-1',isConnected:()=>true})=>ProPromptRuntime.capture({root,stateDatabase:state,executable,server,remote,render,report:d=>{reports.push(d);}});
 try{await run({root,state,executable,project,plugin,server,reports,capture,repairInventory});}finally{await server.dispose();}
});}
test('actual native baseline, manifest, resident and original project produce exact prompt tag',async()=>fixture(async f=>{const runtime=await f.capture(),pid=f.server.lifecycleSnapshot().processId;assert.equal(await runtime.prepare('!pro review inspect','original'),formatLocalDevicePrompt(rewriteProPrompt('!pro review inspect')!,'original',{deviceId:'device-1',workingDirectory:f.project}));assert.equal(f.server.lifecycleSnapshot().processId,pid);assert.equal(f.reports.length,0);}));
test('ordinary prompts survive a failed startup capture and perform no later plugin query',async()=>fixture(async f=>{await unlink(f.executable);const runtime=await f.capture();assert.equal(await runtime.prepare('ordinary exact text  ','original'),'ordinary exact text  ');assert.equal(f.reports.length,0);await assert.rejects(runtime.prepare('!pro review','original'),PromptPreprocessError);assert.equal(f.reports[0]!.code,'PluginInventoryQueryFailed');}));
test('missing and disconnected explicit remote ports stay distinct after successful preflight',async()=>fixture(async f=>{const absent=await f.capture(null);await assert.rejects(absent.prepare('!pro review','original'),PromptPreprocessError);assert.equal(f.reports.at(-1)!.code,'RemoteMcpNotConfigured');const disconnected=await f.capture({deviceId:'device-1',isConnected:()=>false});await assert.rejects(disconnected.prepare('!pro review','original'),PromptPreprocessError);assert.equal(f.reports.at(-1)!.code,'RemoteMcpConnectionFailed');}));
test('changed installed content triggers one actual quiescent native replacement then passes',async()=>fixture(async f=>{const runtime=await f.capture(),pid=f.server.lifecycleSnapshot().processId;await writeFile(join(f.plugin,'plugin.json'),'changed');assert.match(await runtime.prepare('!pro inspect','original'),/conversation_scope=/);assert.equal(f.server.generation(),2n);assert.notEqual(f.server.lifecycleSnapshot().processId,pid);assert.throws(()=>process.kill(pid!,0),(e:unknown)=>(e as NodeJS.ErrnoException).code==='ESRCH');assert.equal(f.reports.length,0);}));
test('active native admission prevents replacement and retains stale diagnostic',async()=>fixture(async f=>{const runtime=await f.capture(),lease=f.server.admitRequest(),pid=f.server.lifecycleSnapshot().processId;try{await writeFile(join(f.plugin,'plugin.json'),'changed');await assert.rejects(runtime.prepare('!pro inspect','original'),PromptPreprocessError);assert.equal(f.server.generation(),1n);assert.equal(f.server.lifecycleSnapshot().processId,pid);assert.equal(f.reports.at(-1)!.code,'ResidentStale');}finally{lease.release();}}));
test('failed startup snapshot is not silently blessed in same generation after repair',async()=>fixture(async f=>{await unlink(f.executable);const runtime=await f.capture();await f.repairInventory();await assert.rejects(runtime.prepare('!pro inspect','original'),PromptPreprocessError);assert.equal(f.reports.at(-1)!.code,'ResidentSnapshotFailed');assert.equal(f.server.generation(),1n);assert.equal(await f.server.forceRestartIfQuiescent(),true);assert.match(await runtime.prepare('!pro inspect','original'),/local-device-mcp/);}));
test('missing original thread never acquires another valid project after otherwise valid preflight',async()=>fixture(async f=>{const runtime=await f.capture();await assert.rejects(runtime.prepare('!pro inspect','missing'),(e:unknown)=>e instanceof PromptPreprocessError&&e.publicMessage.includes('original active thread was not found'));assert.equal(f.server.generation(),1n);}));
