import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';
import {completionMetadataQuery} from '../../src/store/completion-metadata-sql.ts';
import {currentCompletionEntryIn,type CompletionEntry} from '../../src/store/completion-metadata.ts';
const entry:CompletionEntry={source:'Final',id:'job',target:'target',turn:'turn',channel:100n,bytes:4n,position:{stamp:1,ordinal:0n,id:'job'}};
function fixture(run:(db:DatabaseSync)=>void){const db=new DatabaseSync(':memory:');try{db.exec("CREATE TABLE codex_delivery_outbox(delivery_id TEXT PRIMARY KEY,target_thread_id TEXT,turn_id TEXT,channel_id INTEGER,content TEXT,created_at REAL);CREATE TABLE codex_delivery_receipts(receipt_key TEXT,message_id TEXT,retryable INTEGER,blocked_reason TEXT);INSERT INTO codex_delivery_outbox VALUES('job','target','turn',100,'body',1)");run(db);}finally{db.close();}}
test('current final revalidation pins the original channel before ranking',()=>fixture(db=>{assert.deepEqual(currentCompletionEntryIn(db,entry,'runtime',1n),entry);db.exec("UPDATE codex_delivery_outbox SET channel_id=9999 WHERE delivery_id='job'");assert.equal(currentCompletionEntryIn(db,entry,'runtime',1n),null);}));
test('same-time earlier sibling is not bypassed by filtering on requested identity',()=>fixture(db=>{db.exec("INSERT INTO codex_delivery_outbox VALUES('aaa','earlier','turn',100,'head',1)");assert.equal(currentCompletionEntryIn(db,entry,'runtime',1n),null);db.exec("DELETE FROM codex_delivery_outbox WHERE delivery_id='aaa'");assert.deepEqual(currentCompletionEntryIn(db,entry,'runtime',1n),entry);}));
test('unknown and blocked earlier receipts preserve the same lane head barrier',()=>fixture(db=>{db.exec("INSERT INTO codex_delivery_outbox VALUES('aaa','earlier','turn',100,'head',1)");for(const blocked of [null,'blocked']){db.exec('DELETE FROM codex_delivery_receipts');db.prepare('INSERT INTO codex_delivery_receipts VALUES(?,NULL,0,?)').run('[100,"completion/v1","aaa",0]',blocked);assert.equal(currentCompletionEntryIn(db,entry,'runtime',1n),null);}}));
test('oversized metadata and payload siblings are not skipped to promote a later final',()=>fixture(db=>{const q=db.prepare('INSERT INTO codex_delivery_outbox VALUES(?,?,?,?,?,?)');q.run('aaa','x'.repeat(4100),'turn',100,'head',1);assert.equal(currentCompletionEntryIn(db,entry,'runtime',1n),null);db.exec("DELETE FROM codex_delivery_outbox WHERE delivery_id='aaa'");q.run('aaa','earlier','turn',100,'x'.repeat(2097153),1);assert.equal(currentCompletionEntryIn(db,entry,'runtime',1n),null);}));
test('changed target, turn and deletion are rejected while an outer transaction is preserved',()=>fixture(db=>{db.exec('BEGIN');db.exec("UPDATE codex_delivery_outbox SET target_thread_id='changed'");assert.equal(currentCompletionEntryIn(db,entry,'runtime',1n),null);db.exec("UPDATE codex_delivery_outbox SET target_thread_id='target',turn_id='changed'");assert.equal(currentCompletionEntryIn(db,entry,'runtime',1n),null);db.exec('DELETE FROM codex_delivery_outbox');assert.equal(currentCompletionEntryIn(db,entry,'runtime',1n),null);assert.equal(db.isTransaction,true);db.exec('ROLLBACK');assert.deepEqual(currentCompletionEntryIn(db,entry,'runtime',1n),entry);}));
test('native SQLite scoped query ranks only the original channel, with equivalent stable results',()=>{const db=new DatabaseSync(':memory:');let evaluations=0;try{db.function('probe',(v)=>{evaluations++;return v;});db.exec('CREATE TABLE rows(delivery_id TEXT PRIMARY KEY,target_thread_id TEXT,turn_id TEXT,channel_id INTEGER,content TEXT,created_at REAL);CREATE VIEW codex_delivery_outbox AS SELECT delivery_id,target_thread_id,turn_id,channel_id,content,probe(created_at) created_at FROM rows;CREATE TABLE codex_delivery_receipts(receipt_key TEXT,message_id TEXT,retryable INTEGER,blocked_reason TEXT)');const insert=db.prepare('INSERT INTO rows VALUES(?,?,?,?,?,1)');for(let i=0;i<130;i++)insert.run(`job-${i}`,`target-${i}`,'turn',100+i,'body');const suffix=' SELECT stamp,ordinal,sort_id,id,target,turn,channel,bytes FROM candidates WHERE id=?3 AND target=?4 AND turn=?5';let legacyWork=0,scopedWork=0;for(let i=0;i<130;i++){const args=['runtime',1n,`job-${i}`,`target-${i}`,'turn'] as const;const old=db.prepare(completionMetadataQuery('Final')+suffix);old.setReadBigInts(true);evaluations=0;const expected=old.get(...args);legacyWork+=evaluations;const current=db.prepare(completionMetadataQuery('Final',true)+suffix);current.setReadBigInts(true);evaluations=0;const actual=current.get(...args,BigInt(100+i));scopedWork+=evaluations;assert.deepEqual(actual,expected);}assert.ok(scopedWork<legacyWork,`${scopedWork} scoped evaluations must be less than ${legacyWork} legacy evaluations`);assert.ok(scopedWork>=130);assert.ok(legacyWork>=16900);}finally{db.close();}});
