import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {existsSync} from 'node:fs';
import {storeFixture} from '../helpers/store-fixture.ts';import {openInitialized,verifyCurrentCatalogIn,CheckedRead} from '../../src/store/owned-driver.ts';
import {completeConfirmedDelivery} from '../../src/store/delivery-confirmed.ts';import {selectDelivery,type StoredDelivery} from '../../src/store/delivery.ts';import {beginDeliveryReceiptIn} from '../../src/store/delivery-receipts.ts';
import {receiptHash} from '../../src/store/delivery-receipt-key.ts';import {serializeSerdeValue} from '../../src/core/serde-json.ts';import {splitDeliveryChunks} from '../../src/discord/text.ts';
async function edit<T>(path:string,run:(db:DatabaseSync)=>T):Promise<T>{const db=await openInitialized(path);try{return run(db);}finally{db.close();}}
async function seed(path:string,body='final'):Promise<StoredDelivery>{return edit(path,db=>{db.prepare("INSERT INTO codex_delivery_outbox(delivery_id,job_id,target_thread_id,turn_id,channel_id,content,created_at,updated_at) VALUES ('d','job','target','turn',42,?,1,1)").run(body);return selectDelivery(db,'d');});}
const key=(i:number)=>serializeSerdeValue([42n,'completion/v1','d',BigInt(i)]);
async function receipts(path:string,chunks:readonly string[]){await edit(path,db=>{for(const[i,c]of chunks.entries())db.prepare('INSERT INTO codex_delivery_receipts(receipt_key,content_hash,message_id) VALUES(?,?,?)').run(key(i),receiptHash(c),String(100+i));});}
const count=(path:string,table:string)=>edit(path,db=>db.prepare(`SELECT COUNT(*) n FROM ${table}`).get()?.n);
test('all confirmed chunks retire original outbox in one transaction while receipts survive',async()=>storeFixture(async path=>{const p=await seed(path,'x'.repeat(4000)),chunks=splitDeliveryChunks(p.content,true);await receipts(path,chunks);assert.equal(completeConfirmedDelivery(path,p,chunks),true);assert.equal(await count(path,'codex_delivery_outbox'),0);assert.equal(await count(path,'codex_delivery_receipts'),chunks.length);assert.equal(completeConfirmedDelivery(path,p,chunks),false);}));
test('missing receipt rolls back a tentative intent and retains the pending final',async()=>storeFixture(async path=>{const p=await seed(path);assert.equal(completeConfirmedDelivery(path,p,['final']),false);assert.equal(await count(path,'codex_delivery_receipts'),0);assert.equal(await count(path,'codex_delivery_outbox'),1);}));
test('authoritative retry receipt is not consumed by unsuccessful confirmed-only fast path',async()=>storeFixture(async path=>{const p=await seed(path);await edit(path,db=>db.prepare('INSERT INTO codex_delivery_receipts(receipt_key,content_hash,retryable) VALUES(?,?,1)').run(key(0),receiptHash('final')));assert.equal(completeConfirmedDelivery(path,p,['final']),false);assert.equal(await edit(path,db=>db.prepare('SELECT retryable FROM codex_delivery_receipts').get()?.retryable),1);}));
test('partial confirmation, unknown, blocked and content conflicts keep every original receipt',async()=>{for(const mode of ['missing','unknown','blocked','conflict'])await storeFixture(async path=>{const p=await seed(path,'x'.repeat(2100)),chunks=splitDeliveryChunks(p.content,true);await receipts(path,[chunks[0]!]);if(mode!=='missing')await edit(path,db=>db.prepare('INSERT INTO codex_delivery_receipts(receipt_key,content_hash,message_id,blocked_reason) VALUES(?,?,?,?)').run(key(1),mode==='conflict'?'wrong':receiptHash(chunks[1]!),mode==='conflict'?'101':null,mode==='blocked'?'denied':null));const before=await edit(path,db=>db.prepare('SELECT * FROM codex_delivery_receipts ORDER BY receipt_key').all());assert.equal(completeConfirmedDelivery(path,p,chunks),false);assert.deepEqual(await edit(path,db=>db.prepare('SELECT * FROM codex_delivery_receipts ORDER BY receipt_key').all()),before);assert.equal(await count(path,'codex_delivery_outbox'),1);});});
test('all stale StoredDelivery fields reject without retiring or changing receipts',async()=>storeFixture(async path=>{const p=await seed(path);await receipts(path,['final']);for(const k of Object.keys(p) as(keyof StoredDelivery)[]){const v=p[k],stale={...p,[k]:typeof v==='string'?v+'changed':typeof v==='bigint'?v+1n:v+1};assert.equal(completeConfirmedDelivery(path,stale,['final']),false,k);}assert.equal(await count(path,'codex_delivery_outbox'),1);}));
test('first-reply, commentary and goal barriers remain effective even with delivered receipts',async()=>{for(const sql of ["INSERT INTO discord_ingress_journal(ingress_id,kind,channel_id,owner_user_id,target_thread_id,state,phase,owner_kind,owner_id,payload_json,created_at,updated_at) VALUES('i','message',42,7,'target','owned','queued','prompt','job','{}',1,1)","INSERT INTO codex_commentary_outbox(delivery_key,job_id,target_thread_id,turn_id,channel_id,text) VALUES('c','job','target','turn',42,'progress')","INSERT INTO codex_goal_progress(thread,turn,channel,content,job_id) VALUES('target','turn',42,'goal','job')"])await storeFixture(async path=>{const p=await seed(path);await receipts(path,['final']);await edit(path,db=>db.exec(sql));assert.equal(completeConfirmedDelivery(path,p,['final']),false);assert.equal(await count(path,'codex_delivery_outbox'),1);});});
test('delete rejection and ignored delete do not retire the outbox',async()=>{for(const statement of ["SELECT RAISE(ABORT,'reject retirement')","SELECT RAISE(IGNORE)"])await storeFixture(async path=>{const p=await seed(path);await receipts(path,['final']);await edit(path,db=>db.exec(`CREATE TRIGGER deny_retire BEFORE DELETE ON codex_delivery_outbox BEGIN ${statement}; END`));if(statement.includes('ABORT'))assert.throws(()=>completeConfirmedDelivery(path,p,['final']),/reject retirement/);else assert.equal(completeConfirmedDelivery(path,p,['final']),false);assert.equal(await count(path,'codex_delivery_outbox'),1);assert.equal(await count(path,'codex_delivery_receipts'),1);});});
test('missing files are not created and incompatible schema is not migrated',async()=>storeFixture(async path=>{const p:StoredDelivery={deliveryId:'d',jobId:'job',targetThreadId:'t',turnId:'v',channelId:42n,content:'final',attemptCount:0n,lastError:'',createdAt:1,updatedAt:1};assert.throws(()=>completeConfirmedDelivery(path,p,['final']));assert.equal(existsSync(path),false);const db=new DatabaseSync(path);db.exec('CREATE TABLE sentinel(value TEXT);PRAGMA user_version=1');db.close();assert.throws(()=>completeConfirmedDelivery(path,p,['final']));const read=new DatabaseSync(path,{readOnly:true});try{assert.equal(read.prepare('PRAGMA user_version').get()?.user_version,1);assert.deepEqual(read.prepare("SELECT name FROM sqlite_schema WHERE type='table'").all().map(r=>r.name),['sentinel']);}finally{read.close();}}));
test('catalog verification requires and preserves the borrowed transaction, with no schema repair',async()=>storeFixture(async path=>{const db=await openInitialized(path);try{assert.throws(()=>verifyCurrentCatalogIn(db),/active snapshot/);db.exec('BEGIN');verifyCurrentCatalogIn(db);assert.equal(db.isTransaction,true);db.exec('ROLLBACK');const r=CheckedRead.open(path);r.finish();db.exec('BEGIN; DROP TABLE cdr_idle_release');assert.throws(()=>verifyCurrentCatalogIn(db));assert.equal(db.isTransaction,true);db.exec('ROLLBACK');db.exec('BEGIN');verifyCurrentCatalogIn(db);db.exec('ROLLBACK');}finally{db.close();}}));
test('borrowed receipt begins within caller transaction and rollback removes its intent',async()=>storeFixture(async path=>{const db=await openInitialized(path);try{assert.throws(()=>beginDeliveryReceiptIn(db,'key','hash'),/active transaction/);db.exec('BEGIN IMMEDIATE');assert.deepEqual(beginDeliveryReceiptIn(db,'key','hash'),{kind:'New'});assert.equal(db.isTransaction,true);db.exec('ROLLBACK');assert.equal(db.prepare('SELECT count(*) n FROM codex_delivery_receipts').get()?.n,0);}finally{db.close();}}));
test('empty chunk list or invalid signed destination return false without file creation',async()=>storeFixture(async path=>{const p:StoredDelivery={deliveryId:'d',jobId:'j',targetThreadId:'t',turnId:'v',channelId:42n,content:'x',attemptCount:0n,lastError:'',createdAt:1,updatedAt:1};assert.equal(completeConfirmedDelivery(path,p,[]),false);assert.equal(completeConfirmedDelivery(path,{...p,channelId:0n},['x']),false);assert.equal(existsSync(path),false);}));
