import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';
import {boundedMirrorTargetsIn} from '../../src/store/mirror-target-snapshot.ts';import {mirrorTargetsIn} from '../../src/store/mirror-policy-read.ts';import {ActiveTransactionError} from '../../src/store/owned-driver.ts';
function fixture(run:(db:DatabaseSync)=>void){const db=new DatabaseSync(':memory:');try{db.exec('CREATE TABLE mirror_threads(codex_thread_id,thread_title,discord_channel_id,discord_thread_id,updated_at)');run(db);}finally{if(db.isOpen)db.close();}}
test('complete mirror snapshot preserves source ordering/filtering and every selected field',()=>fixture(db=>{db.exec("INSERT INTO mirror_threads VALUES('old','제목',10,20,1),('new','title',11,21,2),('','filtered',12,22,3),('zero','filtered',13,0,4)");db.exec('PRAGMA query_only=ON');const rows=boundedMirrorTargetsIn(db,4n,1000n);assert.deepEqual(rows,mirrorTargetsIn(db,9223372036854775807n));assert.deepEqual(rows.map(r=>r.codexThreadId),['new','old']);assert.equal(rows[1]!.threadTitle,'제목');assert.equal(db.isTransaction,false);assert.ok(Object.isFrozen(rows));}));
test('row overflow rejects whole snapshot including rows filtered by source',()=>fixture(db=>{db.exec("INSERT INTO mirror_threads VALUES('ok','x',1,2,1),('','x',1,0,2)");assert.throws(()=>boundedMirrorTargetsIn(db,1n,1000n),/exceeds budget/);assert.equal(db.isTransaction,false);assert.equal(boundedMirrorTargetsIn(db,2n,1000n).length,1);}));
test('UTF8 and selected numeric bytes have exact boundary',()=>fixture(db=>{db.exec("INSERT INTO mirror_threads VALUES('a','한',1,2,0)");assert.equal(boundedMirrorTargetsIn(db,1n,6n).length,1);assert.throws(()=>boundedMirrorTargetsIn(db,1n,5n),/exceeds budget/);}));
test('malformed selected values are refused and oversized numeric blobs are bounded before decode',()=>fixture(db=>{db.exec("INSERT INTO mirror_threads VALUES('','x',1,x'ff',0)");assert.throws(()=>boundedMirrorTargetsIn(db,1n,1000n));assert.equal(db.isTransaction,false);db.exec('UPDATE mirror_threads SET discord_thread_id=zeroblob(100000)');assert.throws(()=>boundedMirrorTargetsIn(db,1n,1000n),/exceeds budget/);db.exec("UPDATE mirror_threads SET discord_thread_id=0,thread_title=CAST(x'ff' AS TEXT)");assert.throws(()=>boundedMirrorTargetsIn(db,1n,1000n));}));
test('caller transaction is untouched and errors release only owned transaction',()=>fixture(db=>{db.exec('BEGIN');assert.throws(()=>boundedMirrorTargetsIn(db,1n,100n),ActiveTransactionError);assert.equal(db.isTransaction,true);db.exec('ROLLBACK');db.exec('DROP TABLE mirror_threads');assert.throws(()=>boundedMirrorTargetsIn(db,1n,100n),/no such table/);assert.equal(db.isTransaction,false);}));
test('invalid budgets reject before DB access and empty valid snapshot returns empty',()=>fixture(db=>{assert.deepEqual(boundedMirrorTargetsIn(db,1n,1n),[]);for(const [rows,bytes]of [[0n,1n],[65537n,1n],[1n,0n],[1n,16777217n],[1,1n]] as const)assert.throws(()=>boundedMirrorTargetsIn(db,rows as bigint,bytes),RangeError);db.close();assert.throws(()=>boundedMirrorTargetsIn(db,0n,1n),RangeError);}));
test('borrowed original query keeps SQL limit before filtering and decodes filtered rows',()=>fixture(db=>{db.exec("INSERT INTO mirror_threads VALUES('ok','x',1,2,1),('','x',1,0,2)");assert.deepEqual(mirrorTargetsIn(db,1n),[]);assert.equal(mirrorTargetsIn(db,-1n).length,1);assert.deepEqual(mirrorTargetsIn(db,0n),[]);db.exec("UPDATE mirror_threads SET thread_title=CAST(x'ff' AS TEXT) WHERE codex_thread_id=''");assert.throws(()=>mirrorTargetsIn(db,1n));}));
