import {it} from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync,existsSync} from 'node:fs';
import {storeFixture} from '../helpers/store-fixture.ts';import {mirrorInspectionSnapshotReadonly} from '../../src/store/mirror-inspection.ts';
function setup(path:string,sql=''){const db=new DatabaseSync(path);try{db.exec(`CREATE TABLE mirror_threads(codex_thread_id,thread_title,discord_channel_id,discord_thread_id,project_key);CREATE TABLE mirror_projects(project_key,discord_channel_id);${sql}`);}finally{db.close();}}
it('empty legacy mapping schema is read without initialization or version changes',async()=>storeFixture(async path=>{setup(path);const before=readFileSync(path),snapshot=mirrorInspectionSnapshotReadonly(path);assert.deepEqual(snapshot.mappings,[]);assert.deepEqual(snapshot.parents,[]);assert.deepEqual(snapshot.projectIssues,[]);assert.match(snapshot.projectSummary,/duplicate_project_channels: 0/);assert.deepEqual(readFileSync(path),before);}));
it('missing store and missing required table are errors, never an empty healthy inventory',async()=>storeFixture(async path=>{assert.throws(()=>mirrorInspectionSnapshotReadonly(path));assert.equal(existsSync(path),false);const db=new DatabaseSync(path);db.exec('CREATE TABLE mirror_threads(codex_thread_id,thread_title,discord_channel_id,discord_thread_id,project_key)');db.close();const before=readFileSync(path);assert.throws(()=>mirrorInspectionSnapshotReadonly(path),/mirror_projects/);assert.deepEqual(readFileSync(path),before);}));
it('one normalized project preserves exact ordered thread identities, invalid IDs included for later diagnostics',async()=>storeFixture(async path=>{
 setup(path,"INSERT INTO mirror_projects VALUES('/a/./b',9007199254740993);INSERT INTO mirror_threads VALUES('z','Z',9007199254740993,0,'/a/b'),('a','A',9007199254740993,-2,'/a/x/../b')");const s=mirrorInspectionSnapshotReadonly(path);assert.deepEqual(s.mappings.map(r=>r.codexThreadId),['a','z']);assert.deepEqual(s.parents,[9007199254740993n]);assert.equal(s.mappings[0]!.discordThreadId,-2n);assert.deepEqual(s.projectIssues,[]);assert.ok(Object.isFrozen(s));assert.ok(Object.isFrozen(s.mappings[0]));
}));
it('duplicate project rooms, missing mappings, mismatched parents and ambiguous normalized keys remain separate issues',async()=>storeFixture(async path=>{
 setup(path,"INSERT INTO mirror_projects VALUES('/a',10),('/a/.',11),('/b',20),('/c',20);INSERT INTO mirror_threads VALUES('a','A',10,101,'/a'),('b','B',99,102,'/b'),('c','C',30,103,'/missing')");const s=mirrorInspectionSnapshotReadonly(path);assert.deepEqual(s.projectIssues,['duplicate_project_channel | channel=20 | projects=2','ambiguous_project_mapping | thread=a | stored_parent=10','project_parent_mismatch | thread=b | stored_parent=99','missing_project_mapping | thread=c | stored_parent=30']);assert.deepEqual(s.parents,[10n,11n,20n]);assert.equal(s.projectSummary,'missing_project_mapping: 1\nproject_parent_mismatch: 1\nambiguous_project_mapping: 1\nduplicate_project_channels: 1');
}));
it('project duplicate counts count channels rather than number of extra project rows',async()=>storeFixture(async path=>{
 setup(path,"INSERT INTO mirror_projects VALUES('a',-1),('b',-1),('c',-1),('d',0),('e',0)");const s=mirrorInspectionSnapshotReadonly(path);assert.deepEqual(s.parents,[-1n,0n]);assert.deepEqual(s.projectIssues,['duplicate_project_channel | channel=-1 | projects=3','duplicate_project_channel | channel=0 | projects=2']);assert.match(s.projectSummary,/duplicate_project_channels: 2$/);
}));
it('malformed storage class, SQL NULL and invalid UTF8 do not produce partially accepted mappings',async()=>{
 for(const sql of ["INSERT INTO mirror_threads VALUES('a',NULL,1,2,'p')","INSERT INTO mirror_threads VALUES('a','A','1',2,'p')","INSERT INTO mirror_projects VALUES(NULL,1)","INSERT INTO mirror_threads VALUES(CAST(x'ff' AS TEXT),'A',1,2,'p')"]){await storeFixture(async path=>{setup(path,sql);const before=readFileSync(path);assert.throws(()=>mirrorInspectionSnapshotReadonly(path));assert.deepEqual(readFileSync(path),before);const db=new DatabaseSync(path);try{db.exec('BEGIN IMMEDIATE; ROLLBACK');}finally{db.close();}});}
});
