import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {existsSync,readFileSync} from 'node:fs';
import {storeFixture} from '../helpers/store-fixture.ts';
import {restartReadinessSnapshotBlocking as blocking} from '../../src/store/restart-readiness-blocking.ts';
import {restartReadinessSnapshot as snapshot,joinRestartSnapshotReader as join,restartSnapshotReaderBusy as busy,RestartSnapshotWorkerError} from '../../src/store/restart-readiness.ts';
import {OwnedWorkerBusyError} from '../../src/runtime/owned-worker-slot.ts';
import {computeRestartSnapshotPure,STARTING_CANDIDATE_HOLD_PREFIX} from '../../src/store/restart-snapshot-pure.ts';
const core='CREATE TABLE mirror_threads(codex_thread_id);CREATE TABLE codex_turn_queue(job_id,target_thread_id,state,turn_id,last_error);';
function setup(path:string,sql=''):void{const db=new DatabaseSync(path);try{db.exec(core+sql);}finally{db.close();}}
test('worker snapshot matches pure policy for all tables, sorted targets and claimed intake',async()=>storeFixture(async p=>{
 setup(p,"INSERT INTO mirror_threads VALUES('😀'),('z');INSERT INTO codex_turn_queue VALUES('b','q','running','turn',''),('a','q','pending',NULL,'');CREATE TABLE codex_prompt_intakes(job_id,target_thread_id,claim_token);INSERT INTO codex_prompt_intakes VALUES('i','i','');CREATE TABLE codex_app_server_managed_targets(thread_id);INSERT INTO codex_app_server_managed_targets VALUES('managed');CREATE TABLE codex_thread_fork_handoffs(handoff_id,source_thread_id,observed_target_thread_id,target_thread_id);INSERT INTO codex_thread_fork_handoffs VALUES('f','source',NULL,'dest');");
 const expected=computeRestartSnapshotPure({mirrorThreads:['😀','z'],turnQueue:[['b','q','running','turn',''],['a','q','pending',null,'']],promptIntakes:[['i','i','']],appServerManagedTargets:['managed'],threadForkHandoffs:[['f','source',null,'dest']]});
 const before=readFileSync(p);let ticks=0;const timer=setInterval(()=>ticks++,1);try{const result=await snapshot(p);assert.deepEqual(result,expected);assert.ok(Object.isFrozen(result)&&Object.isFrozen(result.targetThreadIds));assert.ok(ticks>0);assert.deepEqual(readFileSync(p),before);}finally{clearInterval(timer);await join();}
}));
test('optional absent tables and views are skipped without migrations',async()=>storeFixture(async p=>{setup(p,"CREATE VIEW codex_prompt_intakes AS SELECT nonexistent FROM missing;PRAGMA user_version=9;");const before=readFileSync(p);assert.deepEqual(await snapshot(p),{targetThreadIds:[],blockers:[],observations:[]});assert.deepEqual(readFileSync(p),before);await join();}));
test('missing file and missing core state fail rather than granting readiness',async()=>storeFixture(async p=>{await assert.rejects(snapshot(p),RestartSnapshotWorkerError);assert.equal(existsSync(p),false);const db=new DatabaseSync(p);db.exec('CREATE TABLE sentinel(x)');db.close();const before=readFileSync(p);await assert.rejects(snapshot(p),RestartSnapshotWorkerError);assert.deepEqual(readFileSync(p),before);await join();}));
test('invalid first mirror target outranks later missing queue table',async()=>storeFixture(async p=>{const db=new DatabaseSync(p);db.exec("CREATE TABLE mirror_threads(codex_thread_id);INSERT INTO mirror_threads VALUES(' bad')");db.close();assert.throws(()=>blocking(p),e=>e instanceof Error&&e.name==='InvalidAppServerManagedTargetError');}));
test('row semantic error is observed before a later malformed row',async()=>storeFixture(async p=>{setup(p,"INSERT INTO codex_turn_queue VALUES('a','t','completed',NULL,''),('b',NULL,'pending',NULL,'');");assert.throws(()=>blocking(p),e=>e instanceof Error&&e.name==='InvalidQueueStateError');}));
test('native text storage class, NULL and invalid UTF8 never become accepted targets',async()=>storeFixture(async p=>{setup(p);const db=new DatabaseSync(p);try{for(const expr of ['123','NULL',"x'61'","CAST(x'80' AS TEXT)"]){db.exec(`DELETE FROM mirror_threads;INSERT INTO mirror_threads VALUES(${expr})`);assert.throws(()=>blocking(p));}}finally{db.close();}}));
test('UTF16 text, BOM and astral strings roundtrip with strict native decoding',async()=>storeFixture(async p=>{const db=new DatabaseSync(p);db.exec("PRAGMA encoding='UTF-16le';"+core);db.prepare('INSERT INTO mirror_threads VALUES(?)').run('\ufeff😀');db.close();assert.deepEqual(blocking(p).targetThreadIds,['\ufeff😀']);}));
test('starting hold is recognized only with exact prefix',async()=>storeFixture(async p=>{setup(p);const db=new DatabaseSync(p);db.prepare('INSERT INTO codex_turn_queue VALUES(?,?,?,?,?)').run('held','t','starting',null,STARTING_CANDIDATE_HOLD_PREFIX);db.prepare('INSERT INTO codex_turn_queue VALUES(?,?,?,?,?)').run('plain','t','starting',null,STARTING_CANDIDATE_HOLD_PREFIX.trimEnd());db.close();assert.deepEqual(blocking(p).blockers,['queue job plain is starting']);}));
test('single worker rejects overlap; abort retains slot until native worker exit',async()=>storeFixture(async p=>{setup(p);const a=new AbortController(),reason=new Error('cancel');const running=snapshot(p,a.signal);assert.equal(busy(),true);a.abort(reason);await assert.rejects(running,e=>e===reason);assert.equal(busy(),true);await assert.rejects(snapshot(p),OwnedWorkerBusyError);await join();assert.equal(busy(),false);assert.deepEqual((await snapshot(p)).blockers,[]);await join();}));
test('preabort and malformed path do not start reader or create file',async()=>storeFixture(async p=>{const a=new AbortController(),reason=new Error('pre');a.abort(reason);await assert.rejects(snapshot(p,a.signal),e=>e===reason);await assert.rejects(snapshot('\ud800'),TypeError);assert.equal(busy(),false);assert.equal(existsSync(p),false);}));
