import assert from "node:assert/strict";
import {test} from "node:test";
import {DatabaseSync} from "node:sqlite";
import {existsSync} from "node:fs";
import {storeFixture} from "../helpers/store-fixture.ts";
import {openInitialized} from "../../src/store/owned-driver.ts";
import {StateAccessFacade as state} from "../../src/store/state-access-facade.ts";
import {getIngressIn} from "../../src/store/ingress-read.ts";
import {selectJob} from "../../src/store/queue-read.ts";
import {serializeSerdeValue} from "../../src/core/serde-json.ts";
import {parseSerdeValue} from "../../src/core/serde-json-parse.ts";
import {snapshotStoredIngress,storedIngressEqual} from "../../src/store/ingress-snapshot.ts";
const scope={target:"T",channel:42n,owner:3n},binding={target:"T",route:"Explicit",command:{Stop:{reference:"T"}}};
async function fixture(run:(path:string,db:DatabaseSync)=>void|Promise<void>){await storeFixture(async path=>{const db=await openInitialized(path);try{await run(path,db);}finally{db.close();}});}
function job(db:DatabaseSync,id="job",s="pending",owner=3){db.prepare("INSERT INTO codex_turn_queue(job_id,target_thread_id,channel_id,owner_user_id,app_server_generation,prompt,queued,ack_sent,state,attempt_count,turn_id,baseline_turn_ids,created_at,updated_at) VALUES(?,'T',42,?,1,'original',0,1,?,0,?,'[]',1,1)").run(id,owner,s==="quarantined"?"running":s,s==="quarantined"?"cdr-quarantined:original":s==="running"?"V":null);if(s==="quarantined")db.prepare("UPDATE codex_turn_queue SET last_error=? WHERE job_id=?").run("[cdr-rust:app-server-fork-quarantine:v1] original",id);}
function intake(db:DatabaseSync,id="intake"){db.prepare("INSERT INTO codex_prompt_intakes(job_id,target_thread_id,channel_id,owner_user_id,raw_prompt,auto_queue_when_busy,require_current_mirror,claim_token,created_at,updated_at) VALUES (?,'T',42,3,'raw',0,0,'lease',4,5)").run(id);}
function ingress(db:DatabaseSync,event=101,control=false,outcome:string|null=null){const payload=control?{version:1n,lifecycle_binding:binding,plan:{Execute:binding.command}}:{version:1n,plan:{Execute:{Ask:{prompt:"original"}}}};db.prepare("INSERT INTO discord_ingress_journal(ingress_id,kind,event_id,channel_id,owner_user_id,source_message_id,payload_json,state,phase,target_thread_id,outcome_json,created_at,updated_at) VALUES (?,'message',?,42,3,?,?,'executing','processing','T',?,10,11)").run(`message:${event}`,event,event,serializeSerdeValue(payload),outcome);return getIngressIn(db,`message:${event}`)!;}
function empty(db:DatabaseSync){for(const t of ["cdr_execution_holds","cdr_stop_revision_receipts"])assert.equal(db.prepare(`SELECT count(*) AS n FROM ${t}`).get()!.n,0);assert.equal(db.prepare("SELECT revision FROM cdr_stop_clock").get()!.revision,0);}
function accept(path:string,expected:ReturnType<typeof ingress>|null=null,check=()=>{}){return state.acceptNonrunningStop(path,scope,binding,expected,check,()=>50);}
test("nonrunning receipt holds queue/intake/unowned originals atomically without rewriting or replay",async()=>fixture((path,db)=>{
  job(db,"z");job(db,"a","starting");intake(db);const original=ingress(db,101,false,'{"keep":9007199254740993,"float":1.0}'),stop=ingress(db,100,true),before=db.prepare("SELECT * FROM codex_turn_queue ORDER BY job_id").all();let checks=0;
  const receipt=accept(path,stop,()=>{checks++;});assert.deepEqual(receipt,{jobs:["a","intake","z"],ingresses:["message:101"]});assert.equal(checks,2);assert.deepEqual(db.prepare("SELECT * FROM codex_turn_queue ORDER BY job_id").all(),before);
  const held=getIngressIn(db,original.ingressId)!;assert.equal(held.state,"held");assert.equal(held.phase,original.phase);assert.equal(held.updatedAt,original.updatedAt);assert.equal((held.outcome as any).keep,9007199254740993n);assert.equal(typeof (held.outcome as any).float,"number");
  const claimed=getIngressIn(db,stop.ingressId)!;assert.equal(claimed.phase,"stop_accepted");assert.equal(claimed.updatedAt,50);assert.deepEqual(claimed.outcome,{kind:"stop_accepted",jobs:["a","intake","z"],ingresses:["message:101"],execution_end_confirmed:false});
  const row=db.prepare("SELECT * FROM cdr_stop_revision_receipts").get()!;assert.equal(row.operation_id,"stop:message:100");const saved=parseSerdeValue<Record<string,unknown>>(row.scope_json as string);assert.equal(saved.hadPreparing,true);assert.deepEqual(saved.binding,binding);assert.equal(row.revision,1);
  assert.throws(()=>accept(path,stop));assert.equal(db.prepare("SELECT count(*) AS n FROM cdr_stop_revision_receipts").get()!.n,1);
}));
test("nonrunning empty/Running/Quarantined returns no receipt while unresolved saves bounded intent even empty",async()=>{
  for(const s of [null,"running","quarantined"])await fixture((path,db)=>{if(s)job(db,"job",s);assert.equal(accept(path),null);empty(db);const r=state.acceptUnresolvedStop(path,scope,binding,null,()=>{});assert.deepEqual(r,{jobs:s?["job"]:[]});assert.equal(Object.hasOwn(r!,"ingresses"),false);assert.equal(db.prepare("SELECT revision FROM cdr_stop_clock").get()!.revision,1);});
});
test("missing legacy database returns null without creation",async()=>storeFixture(async path=>{assert.equal(accept(path),null);assert.equal(state.acceptUnresolvedStop(path,scope,binding,null,()=>{}),null);assert.equal(existsSync(path),false);}));
test("original hold reason/evidence and existing unowned stop evidence survive later direct stop",async()=>fixture((path,db)=>{
  job(db);ingress(db);const first=accept(path)!;const hold=db.prepare("SELECT reason,evidence_json FROM cdr_execution_holds").get(),raw=db.prepare("SELECT outcome_json FROM discord_ingress_journal").get();const second=accept(path)!;assert.deepEqual(first,second);assert.deepEqual(db.prepare("SELECT reason,evidence_json FROM cdr_execution_holds").get(),hold);assert.deepEqual(db.prepare("SELECT outcome_json FROM discord_ingress_journal").get(),raw);assert.equal(db.prepare("SELECT revision FROM cdr_stop_clock").get()!.revision,2);
}));
test("queue/intake same ID is counted twice for bounds but deduplicated receipt preserves initial queue hold",async()=>fixture((path,db)=>{job(db,"same");intake(db,"same");assert.deepEqual(accept(path),{jobs:["same"]});assert.equal(parseSerdeValue<Record<string,unknown>>(db.prepare("SELECT evidence_json FROM cdr_execution_holds").get()!.evidence_json as string).kind,"stop");}));
test("128 total originals accepted and 129 across categories rolls back before holdings",async()=>{for(const count of [128,129])await fixture((path,db)=>{for(let i=0;i<count-1;i++)job(db,`j${i}`);intake(db);if(count===128)assert.equal(accept(path)!.jobs.length,128);else{assert.throws(()=>accept(path));empty(db);}});});
for(const mutation of ["UPDATE codex_turn_queue SET owner_user_id=99","UPDATE codex_prompt_intakes SET channel_id=99","UPDATE discord_ingress_journal SET owner_user_id=99","UPDATE discord_ingress_journal SET owner_kind='unexpected'","UPDATE discord_ingress_journal SET event_id=0","UPDATE discord_ingress_journal SET outcome_json='null'","UPDATE discord_ingress_journal SET outcome_json='{\"stop_hold\":{}}'"])
 test(`mixed original custody refuses ${mutation}`,async()=>fixture((path,db)=>{job(db);intake(db);ingress(db);db.exec(mutation);assert.throws(()=>accept(path));empty(db);}));
test("Mapped and Selected routes verify actual mirror before any hold",async()=>{for(const [route,mapped,yes] of [["Mapped","T",true],["Mapped",null,false],["Selected",null,true],["Selected","T",false]] as const)await fixture((path,db)=>{job(db);if(mapped)db.prepare("INSERT INTO mirror_threads VALUES(?,'p','title',100,42,0)").run(mapped);const b={target:"T",route,command:{Stop:{reference:null}}};if(yes)assert.ok(state.acceptNonrunningStop(path,scope,b,null,()=>{}));else{assert.throws(()=>state.acceptNonrunningStop(path,scope,b,null,()=>{}));empty(db);}});});
test("selected custody checked twice and failure after staged writes rolls back all categories",async()=>fixture((path,db)=>{
  job(db);intake(db);const original=ingress(db),stop=ingress(db,100,true);let count=0;assert.throws(()=>accept(path,stop,()=>{if(++count===2)throw new Error("selected changed");}),/selected changed/);assert.equal(count,2);empty(db);assert.ok(storedIngressEqual(getIngressIn(db,original.ingressId)!,original));assert.ok(storedIngressEqual(getIngressIn(db,stop.ingressId)!,stop));
}));
for(const sql of ["UPDATE codex_turn_queue SET prompt='changed';","DELETE FROM cdr_execution_holds;","UPDATE codex_prompt_intakes SET raw_prompt='changed';","UPDATE discord_ingress_journal SET updated_at=999 WHERE ingress_id='message:101';","UPDATE cdr_stop_revision_receipts SET scope_json='{}' WHERE operation_id=NEW.operation_id;","UPDATE cdr_stop_revisions SET operation_id='foreign';"])
 test(`final readback detects transactional tampering: ${sql}`,async()=>fixture((path,db)=>{job(db);intake(db);const original=ingress(db),stop=ingress(db,100,true);db.exec(`CREATE TRIGGER tamper AFTER INSERT ON cdr_stop_revisions BEGIN ${sql} END`);assert.throws(()=>accept(path,stop));empty(db);assert.equal(selectJob(db,"job").prompt,"original");assert.ok(storedIngressEqual(getIngressIn(db,original.ingressId)!,original));assert.ok(storedIngressEqual(getIngressIn(db,stop.ingressId)!,stop));}));
test("foreign existing hold and inconsistent clock refuse acceptance without borrowing evidence",async()=>{for(const mutation of ["INSERT INTO cdr_execution_holds VALUES('job','other','prior','{}',0)","UPDATE cdr_stop_clock SET revision=1"])await fixture((path,db)=>{job(db);db.exec(mutation);assert.throws(()=>accept(path));assert.equal(db.prepare("SELECT count(*) AS n FROM cdr_stop_revision_receipts").get()!.n,0);});});
test("original processing record, exact binding and source message ID are mandatory",async()=>{for(const change of ["UPDATE discord_ingress_journal SET phase='different'","UPDATE discord_ingress_journal SET source_message_id=999","UPDATE discord_ingress_journal SET payload_json='{\"version\":1}'"])await fixture((path,db)=>{job(db);const stop=ingress(db,100,true);db.exec(change);assert.throws(()=>accept(path,stop));empty(db);});});
test("invalid primitive/accessor/async callback input cannot run user code or write a hold",async()=>fixture((path,db)=>{
  job(db);let calls=0;assert.throws(()=>state.acceptNonrunningStop(path,{...scope,get target(){calls++;return "T";}},binding,null,()=>{}));assert.equal(calls,0);assert.throws(()=>state.acceptNonrunningStop(path,scope,binding,null,(async()=>{}) as ()=>void));empty(db);
  const stop=ingress(db,100,true);const input={...stop,get payload(){calls++;return stop.payload;}};assert.throws(()=>snapshotStoredIngress(input));assert.equal(calls,0);assert.throws(()=>state.acceptNonrunningStop(path,scope,binding,stop,()=>{},()=>Number.NaN));empty(db);
}));

test("absent original-ingress DB and existing uninitialized store are never created or migrated",async()=>{
  await fixture((path,db)=>{const stop=ingress(db,100,true),missing=path+".missing";assert.throws(()=>accept(missing,stop),/database unavailable/);assert.equal(existsSync(missing),false);});
  await storeFixture(async path=>{const db=new DatabaseSync(path);try{db.exec("CREATE TABLE sentinel(value TEXT)");assert.throws(()=>accept(path));assert.deepEqual(db.prepare("SELECT name FROM sqlite_schema WHERE type='table'").all().map(r=>r.name),["sentinel"]);}finally{db.close();}});
});
test("global revision overflow preserves the previous exact receipt and rolls back new holds",async()=>fixture((path,db)=>{
  job(db);const max=(1n<<63n)-1n;db.prepare("UPDATE cdr_stop_clock SET revision=?").run(max);db.prepare("INSERT INTO cdr_stop_revision_receipts VALUES('maximum','other',?,'{}')").run(max);db.prepare("INSERT INTO cdr_stop_revisions VALUES('other',?,'maximum')").run(max);assert.throws(()=>accept(path),/revision evidence differs/);assert.equal(db.prepare("SELECT count(*) AS n FROM cdr_execution_holds").get()!.n,0);assert.equal(db.prepare("SELECT count(*) AS n FROM cdr_stop_revision_receipts").get()!.n,1);
}));
test("a new preparing request inserted by a stop-revision trigger prevents accepting a stale snapshot",async()=>fixture((path,db)=>{
  job(db);db.exec("CREATE TRIGGER phantom AFTER INSERT ON cdr_stop_revisions BEGIN INSERT INTO codex_prompt_intakes(job_id,target_thread_id,channel_id,owner_user_id,raw_prompt,auto_queue_when_busy,require_current_mirror,created_at,updated_at) VALUES ('new','T',42,3,'raw',0,0,1,1); END");assert.throws(()=>accept(path));empty(db);assert.equal(db.prepare("SELECT count(*) AS n FROM codex_prompt_intakes").get()!.n,0);
}));
