import test from 'node:test';import assert from 'node:assert/strict';import {writeFileSync,existsSync} from 'node:fs';import {dirname,join} from 'node:path';
import {storeFixture} from '../helpers/store-fixture.ts';import {readContextSnapshotBlocking,DEFAULT_CONTEXT_BUDGET,ContextReadError} from '../../src/codex-state/context-read.ts';
const meta='{"type":"session_meta","payload":{"id":"original"}}\n';const usage='{"type":"event_msg","payload":{"type":"token_count","info":{"last_token_usage":{"input_tokens":80000},"total_token_usage":{"input_tokens":100000000}}}}\n';
test('real bounded file returns original last usage and preserves unknown totals',async()=>storeFixture(async path=>{writeFileSync(path,meta+usage);const r=readContextSnapshotBlocking(path,'original');assert.equal(r.usage?.lastInputTokens,80000n);assert.equal(r.usage?.lastTotalTokens,null);assert.deepEqual(r.recentItems,[]);}));
test('wrong, missing or later changed identity never yields prior usage',async()=>storeFixture(async path=>{for(const text of [meta.replace('original','other')+usage,usage,meta+usage+meta.replace('original','other')]){writeFileSync(path,text);assert.throws(()=>readContextSnapshotBlocking(path,'original'),/session identity/);}writeFileSync(path,meta);assert.throws(()=>readContextSnapshotBlocking(path,''),/session identity/);}));
test('partial or malformed later records reject the entire snapshot',async()=>storeFixture(async path=>{for(const suffix of ['{"type":','broken\n','[]\n','null\n']){writeFileSync(path,meta+usage+suffix);assert.throws(()=>readContextSnapshotBlocking(path,'original'),ContextReadError);}}));
test('invalid UTF8 and BOM fail JSON decode rather than silently replacing bytes',async()=>storeFixture(async path=>{for(const bytes of [Buffer.concat([Buffer.from(meta),Buffer.from('{"text":"'),Buffer.from([0xff]),Buffer.from('"}\n')]),Buffer.from('\ufeff'+meta)]){writeFileSync(path,bytes);assert.throws(()=>readContextSnapshotBlocking(path,'original'),/invalid JSON/);}}));
test('byte, line and zero-duration budgets enforce their boundaries on actual file',async()=>storeFixture(async path=>{writeFileSync(path,meta);for(const budget of [{...DEFAULT_CONTEXT_BUDGET,maxBytes:1},{...DEFAULT_CONTEXT_BUDGET,maxLineBytes:8},{...DEFAULT_CONTEXT_BUDGET,maxLineBytes:0},{...DEFAULT_CONTEXT_BUDGET,maxDurationMs:0}])assert.throws(()=>readContextSnapshotBlocking(path,'original',budget),ContextReadError);assert.equal(readContextSnapshotBlocking(path,'original',{...DEFAULT_CONTEXT_BUDGET,maxBytes:Buffer.byteLength(meta),maxLineBytes:Buffer.byteLength(meta)}).usage,null);}));
test('chunk-crossing Unicode records obey byte lengths and recent scalar limits',async()=>storeFixture(async path=>{const text='😀'.repeat(20000),record=JSON.stringify({type:'event_msg',payload:{type:'user_message',message:text}})+'\n';writeFileSync(path,meta+record);const r=readContextSnapshotBlocking(path,'original',DEFAULT_CONTEXT_BUDGET,1);assert.equal(r.recentItems[0]?.text,'😀'.repeat(1500));assert.equal(r.recentItems[0]?.truncated,true);assert.throws(()=>readContextSnapshotBlocking(path,'original',{...DEFAULT_CONTEXT_BUDGET,maxLineBytes:Buffer.byteLength(record)-1}),/line budget/);}));
test('blank records skip only source ASCII whitespace and require newline completion',async()=>storeFixture(async path=>{writeFileSync(path,' \t\r\n'+meta+'\f\n');assert.equal(readContextSnapshotBlocking(path,'original').usage,null);for(const prefix of ['\v\n','\u0085\n']){writeFileSync(path,prefix+meta);assert.throws(()=>readContextSnapshotBlocking(path,'original'),/invalid JSON/);}writeFileSync(path,meta+' ');assert.throws(()=>readContextSnapshotBlocking(path,'original'),/incomplete/);}));
test('missing files are not created, directory rejected, empty file remains unknown failure',async()=>storeFixture(async path=>{const missing=join(dirname(path),'absent');assert.throws(()=>readContextSnapshotBlocking(missing,'original'));assert.equal(existsSync(missing),false);assert.throws(()=>readContextSnapshotBlocking(dirname(path),'original'),/regular file/);writeFileSync(path,'');assert.throws(()=>readContextSnapshotBlocking(path,'original'),/not been recorded/);}));
test('usage decoding errors in later records remain failures, no previous observation fallback',async()=>storeFixture(async path=>{writeFileSync(path,meta+usage+usage.replace('80000','1.0'));assert.throws(()=>readContextSnapshotBlocking(path,'original'),/input tokens must/);}));
test('visible text mode is applied before recent window eviction in real file',async()=>storeFixture(async path=>{const records=[['user_message','keep','commentary'],['agent_message','ignored','analysis'],['agent_message','also ignored','commentary']].map(([type,message,phase])=>JSON.stringify({type:'event_msg',payload:{type,message,phase}})).join('\n')+'\n';writeFileSync(path,meta+records);assert.equal(readContextSnapshotBlocking(path,'original',DEFAULT_CONTEXT_BUDGET,1,'UserAndFinal').recentItems[0]?.text,'keep');}));

test('fault-injected concurrent append invalidates otherwise complete old snapshot',async()=>storeFixture(async path=>{
 const fs=(await import('node:fs')).default,{syncBuiltinESMExports}=await import('node:module');writeFileSync(path,meta+usage);const original=fs.readSync;let changed=false;
 fs.readSync=((...args:Parameters<typeof fs.readSync>)=>{const n=(original as Function)(...args);if(!changed){changed=true;fs.appendFileSync(path,'{}\n');}return n;}) as typeof fs.readSync;syncBuiltinESMExports();
 try{assert.throws(()=>readContextSnapshotBlocking(path,'original'),/snapshot is unverified/);assert.equal(changed,true);}finally{fs.readSync=original;syncBuiltinESMExports();}
}));
test('budget getter is rejected without execution before opening an absent file',()=>{
 let hooks=0;assert.throws(()=>readContextSnapshotBlocking('/not-created-context-fixture','original',{get maxBytes(){hooks++;return 10;},maxLineBytes:10,maxDurationMs:100}));assert.equal(hooks,0);
});
