import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFile} from 'node:fs/promises';import {storeFixture} from '../helpers/store-fixture.ts';import {CodexThreadStore} from '../../src/codex-state/store.ts';import {CodexStateError} from '../../src/codex-state/errors.ts';
const schema='CREATE TABLE threads(id TEXT,title TEXT,cwd TEXT,updated_at INTEGER,rollout_path TEXT,model TEXT,reasoning_effort TEXT,tokens_used INTEGER,archived INTEGER,archived_at INTEGER)';
async function fixture(sql:string,run:(path:string,store:CodexThreadStore)=>Promise<void>|void){await storeFixture(async path=>{const db=new DatabaseSync(path);try{db.exec(schema);db.exec(sql);}finally{db.close();}await run(path,CodexThreadStore.open(path));});}
const budget=(e:unknown)=>e instanceof CodexStateError&&e.cause instanceof RangeError;
test('complete bounded snapshot preserves original ordering and byte identity of readonly DB',async()=>fixture("INSERT INTO threads(id,title,updated_at,archived)VALUES('b','B',2,0),('a','A',2,0),('old','X',1,1)",async(path,store)=>{const before=await readFile(path);assert.deepEqual(store.loadRecentThreadsBounded(2n,100n),store.loadRecentThreads());assert.deepEqual(await readFile(path),before);}));
test('one row over the budget rejects without presenting a truncated successful snapshot',async()=>fixture("INSERT INTO threads(id,archived)VALUES('a',0),('b',0)",(_path,store)=>{assert.throws(()=>store.loadRecentThreadsBounded(1n,100n),budget);assert.equal(store.loadRecentThreadsBounded(2n,100n).length,2);}));
test('exact byte boundary includes UTF8 multibyte text and all selected numeric scalars',async()=>fixture("INSERT INTO threads(id,title,updated_at,tokens_used,archived)VALUES('a','한',12,-3,0)",(_path,store)=>{assert.equal(store.loadRecentThreadsBounded(1n,8n).length,1);assert.throws(()=>store.loadRecentThreadsBounded(1n,7n),budget);}));
test('large malformed numeric BLOB is budgeted before selected native row allocation',async()=>fixture("INSERT INTO threads(id,updated_at,archived)VALUES('a',zeroblob(100000),0)",(_path,store)=>{assert.throws(()=>store.loadRecentThreadsBounded(1n,100n),budget);assert.throws(()=>store.loadRecentThreadsBounded(1n,200000n),e=>e instanceof CodexStateError&&!(e.cause instanceof RangeError));}));
test('archived rows are outside active snapshot budget and NULL optional fields retain defaults',async()=>fixture("INSERT INTO threads(id,title,archived)VALUES('a',NULL,0),('old',zeroblob(100000),1)",(_path,store)=>{assert.equal(store.loadRecentThreadsBounded(1n,1n)[0]!.title,'');}));
test('failure rolls back readonly transaction and later committed state is observed afresh',async()=>fixture("INSERT INTO threads(id,archived)VALUES('a',0),('b',0)",(path,store)=>{assert.throws(()=>store.loadRecentThreadsBounded(1n,100n),budget);const db=new DatabaseSync(path);try{db.exec("DELETE FROM threads WHERE id='b'");}finally{db.close();}assert.equal(store.loadRecentThreadsBounded(1n,100n).length,1);}));
test('invalid budgets reject before query and empty active store returns complete empty snapshot',async()=>fixture('',(_path,store)=>{for(const [rows,bytes]of [[0n,1n],[65537n,1n],[1n,0n],[1n,16777217n]])assert.throws(()=>store.loadRecentThreadsBounded(rows!,bytes!),RangeError);assert.deepEqual(store.loadRecentThreadsBounded(1n,1n),[]);}));
