import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {existsSync} from 'node:fs';import {readFile} from 'node:fs/promises';import {setTimeout as sleep} from 'node:timers/promises';import {storeFixture} from '../../helpers/store-fixture.ts';import {discoverMirrorThreads,mirrorDiscoveryBusy,MirrorDiscoveryError} from '../../../src/runtime/session-mirror/discovery.ts';import {OwnedWorkerBusyError,OwnedWorkerTimeoutError} from '../../../src/runtime/owned-worker-slot.ts';
const limits={maxRows:10n,maxValueBytes:100000n,maxOutputBytes:10000,timeoutMs:10000};
const schema='CREATE TABLE threads(id TEXT,title TEXT,cwd TEXT,updated_at INTEGER,rollout_path TEXT,model TEXT,reasoning_effort TEXT,tokens_used INTEGER,archived INTEGER,archived_at INTEGER)';
async function fixture(sql:string,run:(path:string)=>Promise<void>){await storeFixture(async path=>{const db=new DatabaseSync(path);try{db.exec(schema);db.exec(sql);}finally{db.close();}await run(path);});}
test('actual readonly worker returns only ordered routing fields and leaves DB bytes unchanged',async()=>fixture("INSERT INTO threads(id,title,rollout_path,updated_at,archived)VALUES('b','secret title','/b',1,0),('a','other','/a',2,0),('old','archived','/old',3,1)",async path=>{const before=await readFile(path);assert.deepEqual(await discoverMirrorThreads(path,limits),[{id:'a',rolloutPath:'/a'},{id:'b',rolloutPath:'/b'}]);assert.deepEqual(await readFile(path),before);assert.equal(mirrorDiscoveryBusy(),false);}));
test('strict full original row decoder rejects unrelated malformed text rather than accepting routing-only subset',async()=>fixture("INSERT INTO threads(id,title,rollout_path,archived)VALUES('a',CAST(X'ff'AS TEXT),'/a',0)",async path=>{await assert.rejects(discoverMirrorThreads(path,limits),MirrorDiscoveryError);}));
test('row, value and output overflow refuse entire discovery without a prefix',async()=>fixture("INSERT INTO threads(id,rollout_path,archived)VALUES('a','/a',0),('b','/b',0)",async path=>{for(const patch of [{maxRows:1n},{maxValueBytes:1n},{maxOutputBytes:1}])await assert.rejects(discoverMirrorThreads(path,{...limits,...patch}),MirrorDiscoveryError);assert.equal((await discoverMirrorThreads(path,limits)).length,2);}));
test('missing original state is not created by worker',async()=>storeFixture(async path=>{await assert.rejects(discoverMirrorThreads(path,limits),MirrorDiscoveryError);assert.equal(existsSync(path),false);}));
test('concurrent discovery never submits a second worker or queues behind the first',async()=>fixture("INSERT INTO threads(id,archived)VALUES('a',0)",async path=>{const first=discoverMirrorThreads(path,limits);assert.equal(mirrorDiscoveryBusy(),true);await assert.rejects(discoverMirrorThreads(path,limits),OwnedWorkerBusyError);await first;assert.equal(mirrorDiscoveryBusy(),false);}));
test('timeout retains busy native reader and caller until actual SQLite worker exits',async()=>fixture("INSERT INTO threads(id,archived)VALUES('a',0)",async path=>{const lock=new DatabaseSync(path);lock.exec('BEGIN EXCLUSIVE');const started=performance.now();let pending:Promise<unknown>|undefined;try{let settled=false;pending=discoverMirrorThreads(path,{...limits,timeoutMs:1}).then(v=>{settled=true;return v;},e=>{settled=true;return e;});await sleep(50);assert.equal(mirrorDiscoveryBusy(),true);assert.equal(settled,false);assert.ok(await pending instanceof OwnedWorkerTimeoutError);assert.ok(performance.now()-started>=4500,'actual locked SQLite open must finish its native busy timeout before ownership releases');assert.equal(mirrorDiscoveryBusy(),false);}finally{if(lock.isTransaction)lock.exec('ROLLBACK');lock.close();await pending;}}));
test('abort preserves exact reason after actual join and pre-abort opens no worker',async()=>fixture("INSERT INTO threads(id,archived)VALUES('a',0)",async path=>{const c=new AbortController(),reason={cancel:true};const pending=discoverMirrorThreads(path,limits,c.signal);c.abort(reason);await assert.rejects(pending,e=>e===reason);assert.equal(mirrorDiscoveryBusy(),false);await assert.rejects(discoverMirrorThreads(path,limits,c.signal),e=>e===reason);assert.equal(mirrorDiscoveryBusy(),false);}));
test('limits are captured without getter execution before any worker opens',async()=>storeFixture(async path=>{let hooks=0;await assert.rejects(discoverMirrorThreads(path,{...limits,get maxRows(){hooks++;return 1n;}}),TypeError);assert.equal(hooks,0);assert.equal(mirrorDiscoveryBusy(),false);assert.equal(existsSync(path),false);}));
