import test from 'node:test';import assert from 'node:assert/strict';import {MirrorDispatch} from '../../../src/runtime/session-mirror/dispatch.ts';
const limits={maxTargets:20,maxBytes:4096},h=(thread:string,channel=1n)=>({thread,channel}),ok={targets:1n,events:1n,sent:1n},render=(e:unknown)=>String(e);
test('discovery and native ownership preserve channel exclusion and old waiter fairness',async()=>{const calls:string[]=[],release=new Map<string,(v:typeof ok)=>void>();const owner=new MirrorDispatch(limits,(t)=>{calls.push(t.thread);return new Promise(r=>{release.set(t.thread,r);});},render);owner.refresh([h('a'),h('b'),h('c',2n)]);assert.equal(owner.dispatch(),2);await Promise.resolve();assert.deepEqual(calls,['a','c']);release.get('a')!(ok);await owner.waitForSettlement();owner.harvest();owner.refresh([h('a'),h('new',3n),h('b'),h('c',2n)]);assert.equal(owner.dispatch(),2);await Promise.resolve();assert.deepEqual(calls,['a','c','b','new']);release.get('b')!(ok);release.get('c')!(ok);release.get('new')!(ok);await owner.close();});
test('failure backoff is target-local, one second then two seconds, and success resets it',async()=>{let now=0n,fail=true;const calls:string[]=[];const owner=new MirrorDispatch(limits,async t=>{calls.push(t.thread);if(t.thread==='bad'&&fail)throw 'same';return ok;},render,()=>now);owner.refresh([h('bad'),h('good',2n)]);assert.equal(owner.dispatch(),2);await owner.waitForSettlement();await Promise.resolve();const first=owner.harvest();assert.equal(first.find(r=>r.finished.target.thread==='bad')!.report!.count,1n);owner.refresh([h('bad'),h('good',2n)]);assert.equal(owner.dispatch(),1);await owner.waitForSettlement();owner.harvest();now=1000000000n;owner.refresh([h('bad')]);assert.equal(owner.dispatch(),1);await owner.waitForSettlement();assert.equal(owner.harvest()[0]!.report,null);now=2000000000n;owner.refresh([h('bad')]);assert.equal(owner.dispatch(),0);now=3000000000n;fail=false;owner.refresh([h('bad')]);assert.equal(owner.dispatch(),1);await owner.waitForSettlement();assert.equal(owner.harvest()[0]!.finished.outcome.kind,'Completed');owner.refresh([h('bad')]);assert.equal(owner.dispatch(),1);await owner.close();});
test('disappeared target loses retry history after complete discovery',async()=>{let now=0n;const owner=new MirrorDispatch(limits,async()=>{throw 'bad';},render,()=>now);owner.refresh([h('a')]);owner.dispatch();await owner.waitForSettlement();owner.harvest();owner.refresh([]);owner.refresh([h('a')]);assert.equal(owner.dispatch(),1);await owner.waitForSettlement();assert.equal(owner.harvest()[0]!.report!.count,1n);await owner.close();});
test('renderer failure faults dispatch and close preserves the original settled outcome',async()=>{const raw={failure:true},sentinel={render:true};const owner=new MirrorDispatch(limits,async()=>{throw raw;},()=>{throw sentinel;});owner.refresh([h('a')]);owner.dispatch();await owner.waitForSettlement();assert.throws(()=>owner.harvest(),e=>e===sentinel);assert.throws(()=>owner.dispatch());const results=await owner.close();assert.equal(results.length,1);const outcome=results[0]!.outcome;if(outcome.kind!=='Failed')assert.fail();assert.equal(outcome.error,raw);});
test('oversized discovery retains prior ready work and monotonic regression blocks new dispatch',async()=>{let now=2n;const owner=new MirrorDispatch({maxTargets:1,maxBytes:20},async()=>ok,render,()=>now);owner.refresh([h('old')]);assert.throws(()=>owner.refresh([h('a'),h('b')]));assert.equal(owner.readyCount,1);now=1n;assert.throws(()=>owner.dispatch());assert.equal(owner.activeCount,0);now=3n;assert.equal(owner.dispatch(),1);await owner.close();});

test('oversized thread identity rejects the complete discovery before ownership selection',async()=>{const owner=new MirrorDispatch({maxTargets:2,maxBytes:50000},async()=>ok,render);owner.refresh([h('old')]);assert.throws(()=>owner.refresh([h('x'.repeat(16385))]));assert.equal(owner.readyCount,1);assert.equal(owner.dispatch(),1);await owner.close();});
test('unexpected Promise diagnostics fault safely while retaining the actual outcome',async()=>{const owner=new MirrorDispatch(limits,async()=>{throw 'original';},(()=>Promise.reject('diagnostic rejection')) as any);owner.refresh([h('a')]);owner.dispatch();await owner.waitForSettlement();assert.throws(()=>owner.harvest(),/returned Promise/);assert.equal((await owner.close()).length,1);});
