import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {storeFixture} from '../../helpers/store-fixture.ts';import {COLUMNS} from '../../../src/store/queue-read.ts';import {MirrorSnapshotOwner} from '../../../src/runtime/session-mirror/snapshot-owner.ts';import {runMirrorEpoch,MirrorEpochError} from '../../../src/runtime/session-mirror/epoch.ts';
const limits={threads:{maxRows:10n,maxValueBytes:10000n,maxOutputBytes:10000,timeoutMs:10000},store:{maxTargets:10n,maxJobs:10n,maxValueBytes:10000n,maxOutputBytes:10000,timeoutMs:10000}},ready={maxTargets:10,maxBytes:10000},ok={targets:1n,events:0n,sent:0n};
async function fixture(run:(state:string,bridge:string)=>Promise<void>){await storeFixture(async state=>storeFixture(async bridge=>{let db=new DatabaseSync(state);try{db.exec("CREATE TABLE threads(id TEXT,title TEXT,cwd TEXT,updated_at INTEGER,rollout_path TEXT,model TEXT,reasoning_effort TEXT,tokens_used INTEGER,archived INTEGER,archived_at INTEGER);INSERT INTO threads(id,rollout_path,archived)VALUES('t','/original',0)");}finally{db.close();}db=new DatabaseSync(bridge);try{db.exec('CREATE TABLE mirror_threads(codex_thread_id,thread_title,discord_channel_id,discord_thread_id,updated_at);CREATE TABLE codex_turn_queue('+COLUMNS+');');db.exec("INSERT INTO mirror_threads VALUES('t','title',10,20,1)");}finally{db.close();}await run(state,bridge);}));}
test('native epoch discovers and reports completion then stops without a second dispatch',async()=>fixture(async(state,bridge)=>{const c=new AbortController();let polls=0,discoveries=0,reports=0;const owner=new MirrorSnapshotOwner(state,bridge,limits,ready,async()=>{polls++;return ok;},String);const closed=await runMirrorEpoch(owner,rows=>{reports+=rows.length;c.abort('done');},()=>{discoveries++;},c.signal);assert.equal(discoveries,1);assert.equal(polls,1);assert.equal(reports,1);assert.deepEqual(closed,[]);assert.equal(owner.activeCount,0);}));
test('epoch shutdown during actual poll waits for adapter cleanup and retains cancelled outcome',async()=>fixture(async(state,bridge)=>{const c=new AbortController();let release!:(v:typeof ok)=>void,started!:()=>void;const entered=new Promise<void>(r=>started=r),held=new Promise<typeof ok>(r=>release=r);const owner=new MirrorSnapshotOwner(state,bridge,limits,ready,()=>{started();return held;},String);let done=false;const running=runMirrorEpoch(owner,()=>{},()=>{},c.signal).then(r=>{done=true;return r;});await entered;c.abort('stop');await Promise.resolve();assert.equal(done,false);assert.equal(owner.activeCount,1);release(ok);const rows=await running;assert.equal(rows[0]!.outcome.kind,'Cancelled');assert.equal(owner.activeCount,0);}));
test('shared discovery failure stops epoch and carries original source error',async()=>fixture(async(state,bridge)=>{const db=new DatabaseSync(bridge);db.exec('DROP TABLE codex_turn_queue');db.close();let calls=0;const owner=new MirrorSnapshotOwner(state,bridge,limits,ready,async()=>{calls++;return ok;},String);await assert.rejects(runMirrorEpoch(owner,()=>{},()=>{},new AbortController().signal),e=>e instanceof MirrorEpochError&&String(e.cause).includes('codex_turn_queue'));assert.equal(calls,0);assert.equal(owner.activeCount,0);}));
test('one-second discovery progresses while an unrelated target remains actually pending',async()=>fixture(async(state,bridge)=>{const c=new AbortController();let release!:(v:typeof ok)=>void;const held=new Promise<typeof ok>(r=>release=r);let discoveries=0,polls=0;const owner=new MirrorSnapshotOwner(state,bridge,limits,ready,()=>{polls++;return held;},String),started=performance.now();const running=runMirrorEpoch(owner,()=>{},()=>{if(++discoveries===2){c.abort('two');release(ok);}},c.signal);await running;assert.equal(discoveries,2);assert.equal(polls,1);assert.ok(performance.now()-started>=900);assert.equal(owner.activeCount,0);}));
test('overlapping epochs rejected and invalid Promise observer is observed without rejection leak',async()=>fixture(async(state,bridge)=>{const c=new AbortController(),owner=new MirrorSnapshotOwner(state,bridge,limits,ready,async()=>ok,String);const running=runMirrorEpoch(owner,()=>{},()=>{c.abort('done');},c.signal);await assert.rejects(runMirrorEpoch(owner,()=>{},()=>{},c.signal),/already running/);await running;const other=new MirrorSnapshotOwner(state,bridge,limits,ready,async()=>ok,String);await assert.rejects(runMirrorEpoch(other,()=>{},(()=>Promise.reject('observer')) as unknown as ()=>void,new AbortController().signal),MirrorEpochError);}));
test('pre-aborted epoch performs no query or poll and closes ownership cleanly',async()=>fixture(async(state,bridge)=>{const c=new AbortController();c.abort('pre');let calls=0;const owner=new MirrorSnapshotOwner(state,bridge,limits,ready,async()=>{calls++;return ok;},String);assert.deepEqual(await runMirrorEpoch(owner,()=>{calls++;},()=>{calls++;},c.signal),[]);assert.equal(calls,0);}));

test('report callback failure retains the already-harvested completion evidence',async()=>fixture(async(state,bridge)=>{const owner=new MirrorSnapshotOwner(state,bridge,limits,ready,async()=>ok,String),failure={reportFailed:true};await assert.rejects(runMirrorEpoch(owner,()=>{throw failure;},()=>{},new AbortController().signal),e=>{assert.ok(e instanceof MirrorEpochError);assert.equal(e.cause,failure);assert.equal((e as any).unreported?.length,1);assert.equal((e as any).unreported[0].finished.outcome.kind,'Completed');return true;});}));
