import {spawn} from 'node:child_process';
import test from 'node:test';import assert from 'node:assert/strict';import {setTimeout as sleep} from 'node:timers/promises';import {MirrorTargetExecution,type MirrorPollCounts} from '../../../src/runtime/session-mirror/execution.ts';
const value:MirrorPollCounts={targets:1n,events:2n,sent:1n},hint=(thread='a',channel=1n)=>({thread,channel});
function gate(){let release!:(v:MirrorPollCounts)=>void;const promise=new Promise<MirrorPollCounts>(r=>{release=r;});return {promise,release:()=>release(value)};}
test('eight in-flight operations and per-thread/per-channel exclusion survive until harvest',async()=>{const owner=new MirrorTargetExecution(),g=gate();for(let i=0;i<8;i++)assert.equal(owner.tryStart(hint(String(i),BigInt(i)),()=>g.promise),true);assert.equal(owner.tryStart(hint('extra',20n),()=>g.promise),false);g.release();await owner.waitForSettlement();await sleep(0);assert.equal(owner.size,8);assert.equal(owner.takeSettled().length,8);assert.equal(owner.size,0);assert.equal(owner.tryStart(hint('a'),async()=>value),true);assert.equal(owner.tryStart(hint('a',2n),async()=>value),false);assert.equal(owner.tryStart(hint('b',1n),async()=>value),false);await owner.close();});
test('deadline cannot free a noncooperative operation and late success is not accepted',async()=>{const owner=new MirrorTargetExecution(20),g=gate();let signal!:AbortSignal;owner.tryStart(hint(),(_t,s)=>{signal=s;return g.promise;});await sleep(50);assert.equal(signal.aborted,true);assert.equal(owner.size,1);assert.deepEqual(owner.takeSettled(),[]);assert.equal(owner.tryStart(hint(),async()=>value),false);g.release();await owner.waitForSettlement();const [result]=owner.takeSettled();assert.equal(result!.outcome.kind,'TimedOut');assert.equal(owner.size,0);await owner.close();});
test('close is idempotent, joins actual finally cleanup and preserves cancellation reason',async()=>{const owner=new MirrorTargetExecution(),g=gate(),reason={stop:true};let cleaned=false;owner.tryStart(hint(),async()=>{try{return await g.promise;}finally{cleaned=true;}});await sleep(0);const closing=owner.close(reason);assert.equal(owner.close(reason),closing);let done=false;void closing.then(()=>{done=true;});await sleep(5);assert.equal(done,false);assert.equal(cleaned,false);assert.equal(owner.size,1);g.release();const results=await closing;assert.equal(cleaned,true);assert.equal(results[0]!.outcome.kind,'Cancelled');if(results[0]!.outcome.kind==='Cancelled')assert.equal(results[0]!.outcome.reason,reason);assert.equal(owner.size,0);assert.throws(()=>owner.tryStart(hint(),async()=>value));});
test('synchronous callback failure is retained without inspecting opaque error',async()=>{const owner=new MirrorTargetExecution(),error={opaque:true};owner.tryStart(hint(),()=>{throw error;});await owner.waitForSettlement();const [r]=owner.takeSettled();assert.equal(r!.outcome.kind,'Failed');if(r!.outcome.kind==='Failed')assert.equal(r!.outcome.error,error);await owner.close();});
test('thenable callback result is rejected without invoking its then getter',async()=>{const owner=new MirrorTargetExecution();let hooks=0;owner.tryStart(hint(),()=>({get then(){hooks++;throw Error();}} as any));await owner.waitForSettlement();assert.equal(owner.takeSettled()[0]!.outcome.kind,'Failed');assert.equal(hooks,0);await owner.close();});
test('pre-aborted signal starts nothing and midflight abort retains actual custody',async()=>{const owner=new MirrorTargetExecution(),a=new AbortController(),reason={cancel:true};a.abort(reason);assert.throws(()=>owner.tryStart(hint(),async()=>value,a.signal),e=>e===reason);assert.equal(owner.size,0);const b=new AbortController(),g=gate();owner.tryStart(hint(),()=>g.promise,b.signal);await sleep(0);b.abort(reason);assert.equal(owner.size,1);g.release();await owner.waitForSettlement();const [r]=owner.takeSettled();assert.equal(r!.outcome.kind,'Cancelled');await owner.close();});
test('invalid progress is a failed operation, immutable counts are copied from valid result',async()=>{const owner=new MirrorTargetExecution();owner.tryStart(hint(),async()=>({...value,sent:-1n}));await owner.waitForSettlement();assert.equal(owner.takeSettled()[0]!.outcome.kind,'Failed');const mutable={...value};owner.tryStart(hint(),async()=>mutable);await owner.waitForSettlement();const [r]=owner.takeSettled();mutable.sent=99n;if(r!.outcome.kind!=='Completed')assert.fail();assert.equal(r!.outcome.progress.sent,1n);await owner.close();});

test('timed-out actual child retains channel ownership until native close is observed',async()=>{const owner=new MirrorTargetExecution(20);let child:ReturnType<typeof spawn>|undefined;owner.tryStart(hint(),()=>new Promise((resolve,reject)=>{child=spawn(process.execPath,['-e',"process.stdin.resume();process.stdin.on('end',()=>process.exit(0));"],{stdio:['pipe','ignore','ignore']});child.once('error',reject);child.once('close',(code)=>code===0?resolve(value):reject(new Error('fixture child failed')));}));try{await sleep(60);const pid=child!.pid!;assert.doesNotThrow(()=>process.kill(pid,0));assert.equal(owner.takeSettled().length,0);assert.equal(owner.tryStart(hint('other',1n),async()=>value),false);child!.stdin!.end();await owner.waitForSettlement();assert.equal(owner.takeSettled()[0]!.outcome.kind,'TimedOut');assert.throws(()=>process.kill(pid,0),(e:unknown)=>(e as NodeJS.ErrnoException).code==='ESRCH');}finally{if(child!==undefined&&child.exitCode===null)child.kill('SIGKILL');await owner.close();}});
test('stalled target does not prevent independent destination progress',async()=>{const owner=new MirrorTargetExecution(),g=gate();owner.tryStart(hint('slow',1n),()=>g.promise);owner.tryStart(hint('fast',2n),async()=>value);await owner.waitForSettlement();const results=owner.takeSettled();assert.equal(results.length,1);assert.equal(results[0]!.target.thread,'fast');assert.equal(owner.size,1);assert.equal(owner.activeChannels().has(1n),true);assert.equal(owner.tryStart(hint('third',3n),async()=>value),true);g.release();await owner.close();});
