import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {storeFixture} from '../../helpers/store-fixture.ts';import {COLUMNS} from '../../../src/store/queue-read.ts';import {MirrorSnapshotOwner} from '../../../src/runtime/session-mirror/snapshot-owner.ts';import {runMirrorWorker,mirrorRunnerBusy} from '../../../src/runtime/session-mirror/runner.ts';import {mirrorSnapshotDiscoveryBusy} from '../../../src/runtime/session-mirror/discovery-snapshot.ts';
const limits={threads:{maxRows:10n,maxValueBytes:10000n,maxOutputBytes:10000,timeoutMs:10000},store:{maxTargets:10n,maxJobs:10n,maxValueBytes:10000n,maxOutputBytes:10000,timeoutMs:10000}},ready={maxTargets:10,maxBytes:10000},ok={targets:1n,events:0n,sent:0n};
async function fixture(run:(state:string,bridge:string)=>Promise<void>){await storeFixture(async state=>storeFixture(async bridge=>{let db=new DatabaseSync(state);try{db.exec("CREATE TABLE threads(id TEXT,title TEXT,cwd TEXT,updated_at INTEGER,rollout_path TEXT,model TEXT,reasoning_effort TEXT,tokens_used INTEGER,archived INTEGER,archived_at INTEGER);INSERT INTO threads(id,rollout_path,archived)VALUES('t','/original',0)");}finally{db.close();}db=new DatabaseSync(bridge);try{db.exec('CREATE TABLE mirror_threads(codex_thread_id,thread_title,discord_channel_id,discord_thread_id,updated_at);CREATE TABLE codex_turn_queue('+COLUMNS+');');db.exec("INSERT INTO mirror_threads VALUES('t','title',10,20,1)");}finally{db.close();}await run(state,bridge);}));}
test('native full runner reports target completion and stops without recreating owner',async()=>fixture(async(state,bridge)=>{const c=new AbortController();let created=0;await runMirrorWorker(()=>{created++;return new MirrorSnapshotOwner(state,bridge,limits,ready,async()=>ok,String);},String,event=>{assert.equal(event.kind,'Targets');c.abort('done');},c.signal);assert.equal(created,1);assert.equal(mirrorRunnerBusy(),false);}));
test('shared native schema failure joins old epoch before one-second retry and fresh discovery',async()=>fixture(async(state,bridge)=>{let db=new DatabaseSync(bridge);db.exec('DROP TABLE codex_turn_queue');db.close();const c=new AbortController();let created=0,failures=0;const started=performance.now();await runMirrorWorker(()=>{assert.equal(mirrorSnapshotDiscoveryBusy(),false);created++;return new MirrorSnapshotOwner(state,bridge,limits,ready,async()=>ok,String);},String,event=>{if(event.kind==='SharedFailure'){failures++;assert.equal(event.decision.retryAfterNanoseconds,1000000000n);assert.equal(event.decision.report!.count,1n);db=new DatabaseSync(bridge);db.exec('CREATE TABLE codex_turn_queue('+COLUMNS+')');db.close();}else c.abort('done');},c.signal);assert.equal(created,2);assert.equal(failures,1);assert.ok(performance.now()-started>=1000);}));
test('reporter failure retains original epoch error and prevents another epoch',async()=>fixture(async(state,bridge)=>{const db=new DatabaseSync(bridge);db.exec('DROP TABLE codex_turn_queue');db.close();let created=0;const reason={report:true};await assert.rejects(runMirrorWorker(()=>{created++;return new MirrorSnapshotOwner(state,bridge,limits,ready,async()=>ok,String);},String,()=>{throw reason;},new AbortController().signal),e=>e instanceof AggregateError&&e.errors[1]===reason);assert.equal(created,1);assert.equal(mirrorRunnerBusy(),false);}));
test('pre-aborted worker creates no owner and leaves global admission free',async()=>{const c=new AbortController();c.abort('pre');let calls=0;assert.deepEqual(await runMirrorWorker(()=>{calls++;throw 'unused';},String,()=>{},c.signal),[]);assert.equal(calls,0);assert.equal(mirrorRunnerBusy(),false);});
test('second worker cannot overlap a held native epoch and shutdown awaits its actual poll',async()=>fixture(async(state,bridge)=>{let release!:(v:typeof ok)=>void,entered!:()=>void;const held=new Promise<typeof ok>(r=>release=r),started=new Promise<void>(r=>entered=r);const c=new AbortController(),factory=()=>new MirrorSnapshotOwner(state,bridge,limits,ready,()=>{entered();return held;},String),running=runMirrorWorker(factory,String,()=>{},c.signal);await started;await assert.rejects(runMirrorWorker(factory,String,()=>{},new AbortController().signal),/already running/);c.abort('stop');assert.equal(mirrorRunnerBusy(),true);release(ok);const result=await running;assert.equal(result[0]!.outcome.kind,'Cancelled');assert.equal(mirrorRunnerBusy(),false);}));

test('a factory cannot reuse the already closed owner after a shared failure',async()=>fixture(async(state,bridge)=>{const db=new DatabaseSync(bridge);db.exec('DROP TABLE codex_turn_queue');db.close();const owner=new MirrorSnapshotOwner(state,bridge,limits,ready,async()=>ok,String);await assert.rejects(runMirrorWorker(()=>owner,String,()=>{},new AbortController().signal),/fresh owner/);assert.equal(mirrorRunnerBusy(),false);}));

test('diagnostic rendering failure also retains original source error and settled evidence',async()=>fixture(async(state,bridge)=>{const db=new DatabaseSync(bridge);db.exec('DROP TABLE codex_turn_queue');db.close();const reason={render:true};await assert.rejects(runMirrorWorker(()=>new MirrorSnapshotOwner(state,bridge,limits,ready,async()=>ok,String),()=>{throw reason;},()=>{assert.fail('no report');},new AbortController().signal),e=>e instanceof AggregateError&&e.errors[1]===reason&&String(e.errors[0].cause).includes('codex_turn_queue'));assert.equal(mirrorRunnerBusy(),false);}));
