import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {storeFixture} from '../../helpers/store-fixture.ts';import {COLUMNS} from '../../../src/store/queue-read.ts';import {MirrorSnapshotOwner,MirrorTargetUnavailableError} from '../../../src/runtime/session-mirror/snapshot-owner.ts';import {OwnedWorkerBusyError} from '../../../src/runtime/owned-worker-slot.ts';
const limits={threads:{maxRows:10n,maxValueBytes:10000n,maxOutputBytes:10000,timeoutMs:10000},store:{maxTargets:10n,maxJobs:10n,maxValueBytes:10000n,maxOutputBytes:10000,timeoutMs:10000}},ready={maxTargets:10,maxBytes:10000},ok={targets:1n,events:0n,sent:0n};
async function fixture(run:(state:string,bridge:string)=>Promise<void>){await storeFixture(async state=>storeFixture(async bridge=>{let db=new DatabaseSync(state);try{db.exec("CREATE TABLE threads(id TEXT,title TEXT,cwd TEXT,updated_at INTEGER,rollout_path TEXT,model TEXT,reasoning_effort TEXT,tokens_used INTEGER,archived INTEGER,archived_at INTEGER);INSERT INTO threads(id,rollout_path,archived)VALUES('t','/original',0)");}finally{db.close();}db=new DatabaseSync(bridge);try{db.exec('CREATE TABLE mirror_threads(codex_thread_id,thread_title,discord_channel_id,discord_thread_id,updated_at);CREATE TABLE codex_turn_queue('+COLUMNS+');');db.exec("INSERT INTO mirror_threads VALUES('t','title',10,20,1)");}finally{db.close();}await run(state,bridge);}));}
test('native snapshot is bound to owned target and channel before actual poll begins',async()=>fixture(async(state,bridge)=>{const calls:unknown[]=[];const owner=new MirrorSnapshotOwner(state,bridge,limits,ready,async(t,c,j)=>{calls.push([t.rolloutPath,c,j.length,Object.isFrozen(j)]);return ok;},String);try{assert.throws(()=>owner.dispatch(),/not been discovered/);await owner.refresh();assert.equal(owner.dispatch(),1);await owner.waitForSettlement();assert.deepEqual(calls,[['/original',20n,0,true]]);assert.equal(owner.harvest()[0]!.finished.outcome.kind,'Completed');}finally{await owner.close();}}));
test('refresh cannot replace captured data or channel of an in-flight target',async()=>fixture(async(state,bridge)=>{let release!:(v:typeof ok)=>void;const held=new Promise<typeof ok>(r=>release=r),calls:unknown[]=[];const owner=new MirrorSnapshotOwner(state,bridge,limits,ready,async(t,c,j)=>{calls.push([t.rolloutPath,c,j]);return calls.length===1?held:ok;},String);try{await owner.refresh();owner.dispatch();await Promise.resolve();let db=new DatabaseSync(state);db.exec("UPDATE threads SET rollout_path='/new'");db.close();db=new DatabaseSync(bridge);db.exec('UPDATE mirror_threads SET discord_thread_id=21');db.close();await owner.refresh();assert.equal(owner.dispatch(),0);release(ok);await owner.waitForSettlement();owner.harvest();await owner.refresh();owner.dispatch();await owner.waitForSettlement();owner.harvest();assert.equal((calls[0] as any)[0],'/original');assert.equal((calls[0] as any)[1],20n);assert.equal((calls[1] as any)[0],'/new');assert.equal((calls[1] as any)[1],21n);}finally{release(ok);await owner.close();}}));
test('mapped absent original thread is target-local failure without invoking poll',async()=>fixture(async(state,bridge)=>{const db=new DatabaseSync(state);db.exec('DELETE FROM threads');db.close();let calls=0;const owner=new MirrorSnapshotOwner(state,bridge,limits,ready,async()=>{calls++;return ok;},String);try{await owner.refresh();owner.dispatch();await owner.waitForSettlement();const result=owner.harvest()[0]!.finished.outcome;assert.equal(result.kind,'Failed');if(result.kind==='Failed')assert.ok(result.error instanceof MirrorTargetUnavailableError);assert.equal(calls,0);}finally{await owner.close();}}));
test('shutdown aborts and joins current native discovery and prevents later dispatch',async()=>fixture(async(state,bridge)=>{const owner=new MirrorSnapshotOwner(state,bridge,limits,ready,async()=>ok,String),reason={stop:true};const pending=owner.refresh();await assert.rejects(owner.refresh(),OwnedWorkerBusyError);assert.throws(()=>owner.dispatch(),OwnedWorkerBusyError);const observed=pending.catch(e=>e),closing=owner.close(reason);assert.equal(await observed,reason);await closing;assert.equal(owner.refreshing,false);assert.throws(()=>owner.dispatch(),/closed/);}));
test('shutdown keeps active poll owned until it actually settles',async()=>fixture(async(state,bridge)=>{let release!:(v:typeof ok)=>void;const held=new Promise<typeof ok>(r=>release=r);let signal:AbortSignal|undefined;const owner=new MirrorSnapshotOwner(state,bridge,limits,ready,(_t,_c,_j,s)=>{signal=s;return held;},String);await owner.refresh();owner.dispatch();await Promise.resolve();let done=false;const closing=owner.close().then(r=>{done=true;return r;});assert.equal(signal!.aborted,true);assert.equal(done,false);assert.equal(owner.activeCount,1);release(ok);assert.equal((await closing)[0]!.outcome.kind,'Cancelled');assert.equal(owner.activeCount,0);}));

test('failed refresh faults dispatch instead of executing an old valid snapshot',async()=>fixture(async(state,bridge)=>{let calls=0;const owner=new MirrorSnapshotOwner(state,bridge,limits,ready,async()=>{calls++;return ok;},String);try{await owner.refresh();const db=new DatabaseSync(bridge);db.exec('DROP TABLE codex_turn_queue');db.close();await assert.rejects(owner.refresh(),/codex_turn_queue/);assert.throws(()=>owner.dispatch(),/faulted/);assert.equal(calls,0);}finally{await owner.close();}}));
