import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {existsSync} from 'node:fs';import {readFile} from 'node:fs/promises';import {storeFixture} from '../../helpers/store-fixture.ts';import {COLUMNS} from '../../../src/store/queue-read.ts';import {discoverMirrorStore,mirrorStoreDiscoveryBusy,MirrorStoreDiscoveryError} from '../../../src/runtime/session-mirror/store-discovery.ts';import {OwnedWorkerBusyError,OwnedWorkerTimeoutError} from '../../../src/runtime/owned-worker-slot.ts';
const limits={maxTargets:10n,maxJobs:10n,maxValueBytes:100000n,maxOutputBytes:10000,timeoutMs:10000};
async function fixture(run:(path:string)=>Promise<void>){await storeFixture(async path=>{const db=new DatabaseSync(path);try{db.exec('CREATE TABLE mirror_threads(codex_thread_id,thread_title,discord_channel_id,discord_thread_id,updated_at);CREATE TABLE codex_turn_queue('+COLUMNS+');');db.exec("INSERT INTO mirror_threads VALUES('t','title',10,20,1)");db.prepare('INSERT INTO codex_turn_queue VALUES('+Array(19).fill('?').join(',')+')').run('j','t',20n,null,null,1n,null,'prompt',1n,0n,'pending',0n,null,'["a",18446744073709551615]','',1,1,0n,null);}finally{db.close();}await run(path);});}
test('actual read-only native discovery returns complete typed mapping and queue without DB changes',async()=>fixture(async path=>{const before=await readFile(path),s=await discoverMirrorStore(path,limits);assert.deepEqual(s.targets,[{codexThreadId:'t',threadTitle:'title',discordChannelId:10n,discordThreadId:20n}]);assert.equal(s.jobs[0]!.channelId,20n);assert.deepEqual(s.jobs[0]!.baselineTurnIds,['a','18446744073709551615']);assert.ok(Object.isFrozen(s)&&Object.isFrozen(s.targets[0])&&Object.isFrozen(s.jobs[0]!.baselineTurnIds));assert.deepEqual(await readFile(path),before);assert.equal(mirrorStoreDiscoveryBusy(),false);}));
test('target, queue and output limits reject whole discovery',async()=>fixture(async path=>{for(const patch of [{maxValueBytes:1n},{maxOutputBytes:1}])await assert.rejects(discoverMirrorStore(path,{...limits,...patch}),MirrorStoreDiscoveryError);const db=new DatabaseSync(path);try{db.exec("INSERT INTO mirror_threads VALUES('other','title',11,21,2)");}finally{db.close();}await assert.rejects(discoverMirrorStore(path,{...limits,maxTargets:1n}),/budget/);assert.equal((await discoverMirrorStore(path,limits)).targets.length,2);}));
test('invalid queue prevents returning otherwise valid target snapshot',async()=>fixture(async path=>{const db=new DatabaseSync(path);try{db.exec("UPDATE codex_turn_queue SET baseline_turn_ids='{'");}finally{db.close();}await assert.rejects(discoverMirrorStore(path,limits),/baseline_turn_ids/);}));
test('missing bridge store is not initialized or created',async()=>storeFixture(async path=>{await assert.rejects(discoverMirrorStore(path,limits),MirrorStoreDiscoveryError);assert.equal(existsSync(path),false);}));
test('concurrent discovery is refused and cancellation joins original native reader',async()=>fixture(async path=>{const c=new AbortController(),reason={cancel:true},pending=discoverMirrorStore(path,limits,c.signal);assert.equal(mirrorStoreDiscoveryBusy(),true);await assert.rejects(discoverMirrorStore(path,limits),OwnedWorkerBusyError);c.abort(reason);await assert.rejects(pending,e=>e===reason);assert.equal(mirrorStoreDiscoveryBusy(),false);}));
test('locked native SQLite deadline waits for owned exit and never returns stale targets',async()=>fixture(async path=>{const db=new DatabaseSync(path);db.exec('BEGIN EXCLUSIVE');try{await assert.rejects(discoverMirrorStore(path,{...limits,timeoutMs:1}),OwnedWorkerTimeoutError);assert.equal(mirrorStoreDiscoveryBusy(),false);}finally{db.exec('ROLLBACK');db.close();}assert.equal((await discoverMirrorStore(path,limits)).targets.length,1);}));
test('pre-cancelled and accessor limit inputs submit no worker',async()=>storeFixture(async path=>{const c=new AbortController();c.abort('cancel');await assert.rejects(discoverMirrorStore(path,limits,c.signal),e=>e==='cancel');let calls=0;await assert.rejects(discoverMirrorStore(path,{...limits,get maxJobs(){calls++;return 1n;}}),TypeError);assert.equal(calls,0);assert.equal(mirrorStoreDiscoveryBusy(),false);assert.equal(existsSync(path),false);}));

test('queue count is independently bounded and malformed filtered target still blocks discovery',async()=>fixture(async path=>{let db=new DatabaseSync(path);try{db.exec("INSERT INTO codex_turn_queue SELECT * FROM codex_turn_queue");}finally{db.close();}await assert.rejects(discoverMirrorStore(path,{...limits,maxJobs:1n}),/queue snapshot exceeds budget/);assert.equal((await discoverMirrorStore(path,limits)).jobs.length,2);db=new DatabaseSync(path);try{db.exec("INSERT INTO mirror_threads VALUES('',CAST(x'ff' AS TEXT),1,0,2)");}finally{db.close();}await assert.rejects(discoverMirrorStore(path,limits),MirrorStoreDiscoveryError);}));
