import assert from 'node:assert/strict';import {test} from 'node:test';import {setImmediate as tick} from 'node:timers/promises';
import {acknowledgeUntil as ack,interactionAcknowledgementDeadline,INTERACTION_ACK_BUDGET_MS} from '../../../src/runtime/discord-dispatch/acknowledge-until.ts';import {InteractionDispatchError,interactionDispatchErrorInfo} from '../../../src/runtime/discord-dispatch/errors.ts';
class Clock{time=0;waiting=new Set<{at:number;wake:()=>void}>();now=()=>this.time;sleepUntil=(at:number,signal:AbortSignal):Promise<void>=>{signal.throwIfAborted();if(at<=this.time)return Promise.resolve();return new Promise((resolve,reject)=>{const item={at,wake:()=>{clean();resolve();}},clean=()=>{this.waiting.delete(item);signal.removeEventListener('abort',abort);},abort=()=>{clean();reject(signal.reason);};this.waiting.add(item);signal.addEventListener('abort',abort,{once:true});});};advance(at:number){this.time=at;for(const item of [...this.waiting])if(item.at<=at)item.wake();}}
const signal=()=>new AbortController().signal,wait=(signal:AbortSignal)=>new Promise<void>((_r,j)=>{signal.throwIfAborted();signal.addEventListener('abort',()=>j(signal.reason),{once:true});});
test('budget is relative to received time and expired deadline never starts IO',async()=>{const clock=new Clock();clock.advance(2500);let calls=0;assert.equal(INTERACTION_ACK_BUDGET_MS,2500);assert.equal(interactionAcknowledgementDeadline(100),2600);assert.equal(await ack(async()=>{calls++;},2500,signal(),clock),false);assert.equal(calls,0);assert.equal(clock.waiting.size,0);});
test('successful acknowledgement cancels timer without aborting completed operation',async()=>{const clock=new Clock();let aborts=0;assert.equal(await ack(async s=>{s.addEventListener('abort',()=>{aborts++;});},2500,signal(),clock),true);assert.equal(aborts,0);assert.equal(clock.waiting.size,0);});
test('transport String error becomes exact typed source acknowledgement error',async()=>{const clock=new Clock();await assert.rejects(ack(async()=>{throw 'offline failure';},2500,signal(),clock),e=>e instanceof InteractionDispatchError&&e.kind==='Acknowledge'&&e.message==='failed to acknowledge Discord interaction: offline failure');assert.equal(clock.waiting.size,0);});
test('deadline wins over same-turn completion and joins owned work',async()=>{const clock=new Clock();let finish!:()=>void;const pending=ack(()=>new Promise<void>(r=>{finish=r;}),2500,signal(),clock);await tick();finish();clock.advance(2500);assert.equal(await pending,false);assert.equal(clock.waiting.size,0);});
test('timeout cancels operation and waits for real asynchronous cleanup',async()=>{const clock=new Clock();let release!:()=>void,cleaned=false;const cleanup=new Promise<void>(r=>{release=r;});const pending=ack(async s=>{try{await wait(s);}finally{await cleanup;cleaned=true;}},2500,signal(),clock);await tick();clock.advance(2500);let settled=false;void pending.then(()=>{settled=true;});await tick();assert.equal(settled,false);assert.equal(cleaned,false);release();assert.equal(await pending,false);assert.equal(cleaned,true);});
test('force cancellation preserves exact reason after native cleanup',async()=>{const clock=new Clock(),force=new AbortController(),reason=new Error('force'),pending=ack(wait,2500,force.signal,clock),rejected=assert.rejects(pending,e=>e===reason);await tick();force.abort(reason);await rejected;assert.equal(clock.waiting.size,0);});
test('operation that became ready after deadline is never started',async()=>{const clock=new Clock();let calls=0;const pending=ack(async()=>{calls++;},2500,signal(),clock);clock.advance(2500);assert.equal(await pending,false);assert.equal(calls,0);});
test('distinct timeout cleanup failure is surfaced rather than silently discarded',async()=>{const clock=new Clock(),pending=ack(async s=>{try{await wait(s);}finally{throw 'cleanup failure';}},2500,signal(),clock),rejected=assert.rejects(pending,e=>e instanceof InteractionDispatchError&&e.message.endsWith('cleanup failure'));await tick();clock.advance(2500);await rejected;});
test('clock failure cancels and joins pending operation before escaping',async()=>{const reason=new Error('clock');let cleaned=false;await assert.rejects(ack(async s=>{try{await wait(s);}finally{cleaned=true;}},2500,signal(),{now:()=>0,sleepUntil:async()=>{throw reason;}}),e=>e===reason);assert.equal(cleaned,true);});
test('error classification is passive and does not inspect unknown causes',()=>{let calls=0;const proxy=new Proxy({}, {get(){calls++;throw new Error('getter');},getPrototypeOf(){calls++;throw new Error('prototype');}}),error=new InteractionDispatchError('Acknowledge',proxy);assert.equal(calls,0);assert.equal(error.cause,proxy);assert.equal(interactionDispatchErrorInfo(proxy),null);assert.equal(interactionDispatchErrorInfo(Object.create(InteractionDispatchError.prototype)),null);assert.equal(interactionDispatchErrorInfo(error)?.kind,'Acknowledge');assert.equal(calls,0);});
