import assert from 'node:assert/strict';import {test} from 'node:test';import {InteractionClaimCache,type InteractionClaim} from '../../../src/runtime/discord-dispatch/claim-cache.ts';
function claim(cache:InteractionClaimCache,id:bigint):InteractionClaim{const value=cache.tryClaim(id);assert.equal(value.kind,'Claimed');if(value.kind!=='Claimed')throw new Error('claim required');return value.claim;}
test('pending claims never evict while committed claims can make capacity available',()=>{const cache=new InteractionClaimCache(2),first=claim(cache,1n),second=claim(cache,2n);assert.equal(cache.tryClaim(3n).kind,'Saturated');assert.equal(second.commit(),true);const third=claim(cache,3n);assert.equal(cache.tryClaim(1n).kind,'DuplicatePending');assert.deepEqual(cache.snapshot(),{size:2,capacity:2,pending:2,committed:0});first.release();third.release();});
test('released old handle cannot erase or commit replacement generation',()=>{const cache=new InteractionClaimCache(1),old=claim(cache,1n);assert.equal(old.release(),true);const replacement=claim(cache,1n);assert.equal(old.release(),false);assert.equal(old.commit(),false);assert.equal(cache.tryClaim(1n).kind,'DuplicatePending');assert.equal(replacement.commit(),true);assert.equal(cache.tryClaim(1n).kind,'DuplicateCommitted');});
test('committed claims evict in commit order, not claim creation order',()=>{const cache=new InteractionClaimCache(2),a=claim(cache,1n),b=claim(cache,2n);b.commit();a.commit();const c=claim(cache,3n);assert.equal(cache.tryClaim(1n).kind,'DuplicateCommitted');assert.equal(cache.tryClaim(3n).kind,'DuplicatePending');c.release();const bAgain=claim(cache,2n);bAgain.release();});
test('duplicate check precedes saturation and commit/release are single-use',()=>{const cache=new InteractionClaimCache(1),a=claim(cache,1n);assert.equal(cache.tryClaim(1n).kind,'DuplicatePending');assert.equal(cache.tryClaim(2n).kind,'Saturated');assert.equal(a.commit(),true);assert.equal(a.commit(),false);assert.equal(a.release(),false);assert.equal(cache.tryClaim(1n).kind,'DuplicateCommitted');});
test('shared owner suppresses redelivery across asynchronous dispatchers',async()=>{const cache=new InteractionClaimCache(),results=await Promise.all(Array.from({length:32},async()=>cache.tryClaim(1n)));assert.equal(results.filter(x=>x.kind==='Claimed').length,1);assert.equal(results.filter(x=>x.kind==='DuplicatePending').length,31);for(const result of results)if(result.kind==='Claimed')result.claim.release();assert.equal(cache.snapshot().size,0);});
test('default4096 and zero capacity normalization preserve source boundary',()=>{assert.equal(new InteractionClaimCache().capacity,4096);const cache=new InteractionClaimCache(0),a=claim(cache,1n);assert.equal(cache.capacity,1);assert.equal(cache.tryClaim(2n).kind,'Saturated');a.release();for(const n of [-1,1.5,Infinity,Number.MAX_SAFE_INTEGER+1])assert.throws(()=>new InteractionClaimCache(n));});
test('full u64 IDs stay lossless and invalid IDs never consume capacity',()=>{const cache=new InteractionClaimCache(2),max=(1n<<64n)-1n,a=claim(cache,max),b=claim(cache,max-1n);a.commit();assert.equal(cache.tryClaim(max).kind,'DuplicateCommitted');assert.equal(cache.tryClaim(max-1n).kind,'DuplicatePending');for(const bad of [0n,-1n,1n<<64n,1 as unknown as bigint])assert.throws(()=>cache.tryClaim(bad));assert.equal(cache.snapshot().size,2);b.release();});
test('repeated commit/eviction compacts queue without changing newest retained identities',()=>{const cache=new InteractionClaimCache(3);for(let i=1n;i<=5000n;i++)claim(cache,i).commit();assert.deepEqual(cache.snapshot(),{size:3,capacity:3,pending:0,committed:3});for(const id of [4998n,4999n,5000n])assert.equal(cache.tryClaim(id).kind,'DuplicateCommitted');const fresh=claim(cache,1n);assert.equal(cache.tryClaim(4999n).kind,'DuplicateCommitted');fresh.release();});
test('cache and claim facades cannot be overridden to forge successful custody',()=>{const cache=new InteractionClaimCache(),a=claim(cache,1n);assert.equal(Object.isFrozen(cache),true);assert.equal(Object.isFrozen(a),true);assert.throws(()=>Object.defineProperty(a,'commit',{value:()=>true}));assert.throws(()=>Object.defineProperty(cache,'tryClaim',{value:()=>({kind:'Claimed'})}));class Fake extends InteractionClaimCache{}assert.throws(()=>new Fake());a.release();});
