import assert from 'node:assert/strict';import {test} from 'node:test';import {setImmediate as tick} from 'node:timers/promises';
import {InteractionClaimCache,type InteractionClaim} from '../../../src/runtime/discord-dispatch/claim-cache.ts';import {respondWithoutWork as respond} from '../../../src/runtime/discord-dispatch/respond-without-work.ts';import {InteractionDispatchError} from '../../../src/runtime/discord-dispatch/errors.ts';import {serializeInteractionResponse} from '../../../src/discord/interaction-response.ts';
function claim(cache:InteractionClaimCache,id=1n):InteractionClaim{const result=cache.tryClaim(id);assert.ok(result.kind==='Claimed');return result.claim;}
const clock={now:()=>0,sleepUntil:(_at:number,signal:AbortSignal)=>new Promise<void>((_r,j)=>{signal.throwIfAborted();signal.addEventListener('abort',()=>j(signal.reason),{once:true});})};
test('confirmed no-work response commits claim only after actual acknowledgement',async()=>{const cache=new InteractionClaimCache(),guard=claim(cache);let finish!:()=>void;const pending=respond(guard,(response)=>{assert.equal(JSON.parse(serializeInteractionResponse(response)).data.flags,64);return new Promise<void>(r=>{finish=r;});},'missing identity',2500,new AbortController().signal,clock);await tick();assert.equal(cache.tryClaim(1n).kind,'DuplicatePending');finish();assert.equal(await pending,'RespondedWithoutWork');assert.equal(cache.tryClaim(1n).kind,'DuplicateCommitted');});
test('deadline expiry releases guard without invoking transport',async()=>{const cache=new InteractionClaimCache(),guard=claim(cache);let calls=0;assert.equal(await respond(guard,async()=>{calls++;},'reject',0,new AbortController().signal,clock),'DeadlineExceeded');assert.equal(calls,0);assert.equal(cache.snapshot().size,0);claim(cache).release();});
test('acknowledgement failure retains typed error and releases claim for later retry',async()=>{const cache=new InteractionClaimCache();await assert.rejects(respond(claim(cache),async()=>{throw 'offline';},'reject',2500,new AbortController().signal,clock),e=>e instanceof InteractionDispatchError&&e.kind==='Acknowledge');assert.equal(cache.snapshot().size,0);claim(cache).release();});
test('same guard cannot be consumed by concurrent response calls',async()=>{const cache=new InteractionClaimCache(),guard=claim(cache);let finish!:()=>void,calls=0;const pending=respond(guard,()=>{calls++;return new Promise<void>(r=>{finish=r;});},'first',2500,new AbortController().signal,clock);await assert.rejects(respond(guard,async()=>{calls++;},'second',2500,new AbortController().signal,clock),e=>e instanceof InteractionDispatchError&&e.kind==='ClaimState');await tick();assert.equal(calls,1);finish();await pending;});
test('stale guard cannot commit acknowledgement over replacement claim',async()=>{const cache=new InteractionClaimCache(),guard=claim(cache);let finish!:()=>void;const pending=respond(guard,()=>new Promise<void>(r=>{finish=r;}),'reject',2500,new AbortController().signal,clock),rejected=assert.rejects(pending,e=>e instanceof InteractionDispatchError&&e.kind==='ClaimState');await tick();guard.release();const replacement=claim(cache);finish();await rejected;assert.equal(cache.tryClaim(1n).kind,'DuplicatePending');replacement.release();});
test('response validation failure still releases transferred claim',async()=>{const cache=new InteractionClaimCache();await assert.rejects(respond(claim(cache),async()=>{},'\ud800',2500,new AbortController().signal,clock));assert.equal(cache.snapshot().size,0);});
test('forged or already consumed guard cannot send network work',async()=>{const cache=new InteractionClaimCache(),guard=claim(cache);guard.release();let calls=0;for(const value of [guard,{commit:()=>true,release:()=>true}])await assert.rejects(respond(value,async()=>{calls++;},'reject',2500,new AbortController().signal,clock));assert.equal(calls,0);});
