import assert from 'node:assert/strict';
import {test} from 'node:test';
import {once} from 'node:events';
import {setImmediate as tick} from 'node:timers/promises';
import {WebSocketServer} from 'ws';
import {SecretToken} from '../../../src/config/remote.ts';
import {GatewaySessionMachine} from '../../../src/discord/gateway/session-machine.ts';
import {GatewayControlEncoder} from '../../../src/discord/gateway/control-encoder.ts';
import {NodeGatewayWebSocket,gatewaySendFailureStage} from '../../../src/discord/gateway/node-websocket.ts';
import {sendGatewayControl,GatewayControlOwnershipError} from '../../../src/discord/gateway/control-sender.ts';
const makeEncoder=()=>new GatewayControlEncoder({token:new SecretToken('offline-fixture'),shardNumber:0,shardTotal:1,messageContent:false,os:'linux'});
function identify(){const machine=new GatewaySessionMachine({jitter:()=>0n});machine.connected();machine.processPacket('{"op":10,"d":{"heartbeat_interval":41250}}',0n);machine.identifyGranted(machine.identifyRequest()!);return machine;}
async function fixture(){const server=new WebSocketServer({host:'127.0.0.1',port:0});await once(server,'listening');const accepted=once(server,'connection'),wire=await NodeGatewayWebSocket.connectForTest(`ws://127.0.0.1:${(server.address() as {port:number}).port}`);const [peer]=await accepted;return {wire,peer,close:async()=>{await wire.dispose();for(const client of server.clients)client.terminate();await new Promise<void>(resolve=>server.close(()=>resolve()));}};}
test('actual Identify send clears only its current command after local completion',{timeout:5000},async()=>{const f=await fixture(),machine=identify(),ticket=machine.takeCommand()!;try{const received=once(f.peer,'message');assert.equal(await sendGatewayControl({machine,ticket,encoder:makeEncoder(),wire:f.wire,nowNs:()=>1n}),'TextFlushed');assert.equal(JSON.parse((await received)[0].toString()).op,2);assert.equal(machine.isCurrentCommand(ticket),false);assert.equal(machine.takeCommand(),null);}finally{await f.close();}});
test('foreign ticket is rejected before any native send',{timeout:5000},async()=>{const f=await fixture(),machine=identify(),ticket=machine.takeCommand()!;let messages=0;f.peer.on('message',()=>messages++);try{await assert.rejects(sendGatewayControl({machine,ticket:{...ticket},encoder:makeEncoder(),wire:f.wire,nowNs:()=>1n}),GatewayControlOwnershipError);await tick();assert.equal(messages,0);assert.equal(machine.isCurrentCommand(ticket),true);}finally{await f.close();}});
test('BeforePayload failure retains an unsent Identify for a later connection',{timeout:5000},async()=>{const f=await fixture(),machine=identify(),ticket=machine.takeCommand()!;try{await f.wire.dispose();await assert.rejects(sendGatewayControl({machine,ticket,encoder:makeEncoder(),wire:f.wire,nowNs:()=>1n}),error=>gatewaySendFailureStage(error)==='BeforePayload');assert.equal(machine.phase,'Disconnected');machine.connected();assert.equal(machine.takeCommand()!.command.kind,'Identify');}finally{await f.close();}});
test('actual interrupted Resume becomes FlushOnly and cannot replay authenticated bytes',{timeout:10000},async()=>{const f=await fixture(),machine=new GatewaySessionMachine({jitter:()=>0n,session:{id:'x'.repeat(16*1024*1024),sequence:1n}});machine.connected();machine.processPacket('{"op":10,"d":{"heartbeat_interval":41250}}',0n);const ticket=machine.takeCommand()!;f.peer.pause();try{const sending=sendGatewayControl({machine,ticket,encoder:makeEncoder(),wire:f.wire,nowNs:()=>1n}),rejected=assert.rejects(sending,error=>gatewaySendFailureStage(error)==='AfterPayload');await Promise.all([f.wire.dispose(),rejected]);assert.equal(machine.phase,'Disconnected');machine.connected();assert.deepEqual(machine.takeCommand()!.command,{kind:'FlushOnly',heartbeat:false});assert.equal(f.wire.pendingOperations,0);}finally{await f.close();}});
test('same-machine concurrent sender cannot emit a duplicate pending command',{timeout:5000},async()=>{const f=await fixture(),machine=identify(),ticket=machine.takeCommand()!;try{const first=sendGatewayControl({machine,ticket,encoder:makeEncoder(),wire:f.wire,nowNs:()=>1n});await assert.rejects(sendGatewayControl({machine,ticket,encoder:makeEncoder(),wire:f.wire,nowNs:()=>1n}),GatewayControlOwnershipError);await first;}finally{await f.close();}});
test('heartbeat sent timestamp is recorded after the actual send completes',{timeout:5000},async()=>{const f=await fixture(),machine=new GatewaySessionMachine({jitter:()=>0n});machine.connected();machine.processPacket('{"op":1}',0n);const ticket=machine.takeCommand()!;try{assert.equal(machine.latencySnapshot().sentAtNs,null);await sendGatewayControl({machine,ticket,encoder:makeEncoder(),wire:f.wire,nowNs:()=>9n});assert.equal(machine.latencySnapshot().sentAtNs,9n);}finally{await f.close();}});
test('consumed FlushOnly joins without emitting data on replacement wire',{timeout:5000},async()=>{const f=await fixture(),machine=identify(),old=machine.takeCommand()!;machine.commandFailed(old,'AfterPayload');machine.connected();const ticket=machine.takeCommand()!;let messages=0;f.peer.on('message',()=>messages++);try{assert.equal(await sendGatewayControl({machine,ticket,encoder:makeEncoder(),wire:f.wire,nowNs:()=>1n}),'FlushOnly');await tick();assert.equal(messages,0);}finally{await f.close();}});
test('CloseRequested reports acceptance while caller retains actual handshake ownership',{timeout:5000},async()=>{const f=await fixture(),machine=new GatewaySessionMachine({jitter:()=>0n});machine.connected();machine.requestClose(1000);const ticket=machine.takeCommand()!;try{const closed=once(f.peer,'close');assert.equal(await sendGatewayControl({machine,ticket,encoder:makeEncoder(),wire:f.wire,nowNs:()=>1n}),'CloseRequested');const [code,reason]=await closed;assert.equal(code,1000);assert.equal(reason.toString(),'closing connection');assert.equal((await f.wire.receive())?.kind,'Close');}finally{await f.close();}});
test('closed transport cannot report CloseRequested and preserves the unsent close command',{timeout:5000},async()=>{const f=await fixture(),machine=new GatewaySessionMachine({jitter:()=>0n});machine.connected();machine.requestClose(1000);const ticket=machine.takeCommand()!;try{await f.wire.dispose();await assert.rejects(sendGatewayControl({machine,ticket,encoder:makeEncoder(),wire:f.wire,nowNs:()=>1n}),error=>gatewaySendFailureStage(error)==='BeforePayload');machine.connected();assert.deepEqual(machine.takeCommand()!.command,{kind:'Close',code:1000});}finally{await f.close();}});
test('clock failure after actual send leaves only consumed flush state, never original payload',{timeout:5000},async()=>{const f=await fixture(),machine=identify(),ticket=machine.takeCommand()!,failure=new Error('clock');try{await assert.rejects(sendGatewayControl({machine,ticket,encoder:makeEncoder(),wire:f.wire,nowNs:()=>{throw failure;}}),error=>error===failure);machine.connected();assert.deepEqual(machine.takeCommand()!.command,{kind:'FlushOnly',heartbeat:false});}finally{await f.close();}});
