import assert from 'node:assert/strict';
import {test} from 'node:test';
import {once} from 'node:events';
import {setImmediate as tick} from 'node:timers/promises';
import WebSocket,{WebSocketServer} from 'ws';
import {SecretToken} from '../../../src/config/remote.ts';
import {GatewayMessageDriver,type GatewayDriverClock} from '../../../src/discord/gateway/message-driver.ts';
import {GatewayDecodedShardPort} from '../../../src/discord/gateway/decoded-shard-port.ts';
import {GatewayRuntime} from '../../../src/discord/gateway/runtime.ts';
import {NodeGatewayWebSocket} from '../../../src/discord/gateway/node-websocket.ts';
import {SingleBucketGatewayIdentifyQueue} from '../../../src/discord/gateway/identify-queue.ts';
class Clock implements GatewayDriverClock{
 now=0n;readonly timers=new Set<{at:bigint;finish:()=>void}>();nowNs=()=>this.now;
 sleepUntilNs=(at:bigint,signal:AbortSignal):Promise<void>=>new Promise((resolve,reject)=>{if(signal.aborted){reject(signal.reason);return;}if(at<=this.now){resolve();return;}const finish=()=>{this.timers.delete(item);signal.removeEventListener('abort',abort);resolve();};const abort=()=>{this.timers.delete(item);signal.removeEventListener('abort',abort);reject(signal.reason);};const item={at,finish};this.timers.add(item);signal.addEventListener('abort',abort,{once:true});});
 advance(ms:number){this.now+=BigInt(ms)*1000000n;for(const t of [...this.timers])if(t.at<=this.now)t.finish();}
}
async function turns(){for(let i=0;i<8;i++)await tick();}
async function until(predicate:()=>boolean){for(let i=0;i<1000&&!predicate();i++)await tick();assert.equal(predicate(),true);}
const ready={application:{id:'1',flags:0},guilds:[],resume_gateway_url:'wss://gateway.discord.gg',session_id:'offline',user:{id:'2',username:'bot',discriminator:'0',mfa_enabled:false},v:10};
const message={attachments:[],author:{id:'3',username:'u',discriminator:'1'},channel_id:'7',content:'hello',embeds:[],id:'1',type:0,mention_everyone:false,mention_roles:[],mentions:[],pinned:false,timestamp:'2020-02-02T02:02:02.020000+00:00',tts:false};
const envelope=(t:string,d:unknown)=>JSON.stringify({op:0,t,s:1,d});
async function fixture(){
 const clock=new Clock(),queue=new SingleBucketGatewayIdentifyQueue({clock:{now:()=>Number(clock.now)/1e6,sleepUntil:(at,signal)=>clock.sleepUntilNs(BigInt(Math.round(at*1e6)),signal)}}),server=new WebSocketServer({host:'127.0.0.1',port:0});await once(server,'listening');const peers:WebSocket[]=[];let connects=0;
 server.on('connection',peer=>{peers.push(peer);peer.on('error',()=>{});peer.on('message',data=>{const command=JSON.parse(data.toString());if(command.op===2)peer.send(envelope('READY',ready));if(command.op===1)peer.send('{"op":11}');});peer.send('{"op":10,"d":{"heartbeat_interval":60000}}');});
 const driver=new GatewayMessageDriver({token:new SecretToken('offline'),shardNumber:0,shardTotal:1,messageContent:false,identifyQueue:queue,jitter:interval=>interval,clock,connect:(_url,signal)=>{connects++;return NodeGatewayWebSocket.connectForTest(`ws://127.0.0.1:${(server.address() as {port:number}).port}`,{signal});}}),port=new GatewayDecodedShardPort(driver),signal=new AbortController().signal;
 const start=async()=>{const first=port.nextEvent(signal);await turns();clock.advance(1000);assert.deepEqual(await first,{kind:'Event',event:{kind:'Ignored'}});const value=await port.nextEvent(signal);assert.equal(value?.kind,'Event');if(value?.kind==='Event')assert.equal(value.event.kind,'Ready');};
 const close=async()=>{await port.dispose();await queue.close();for(const peer of server.clients)peer.terminate();await new Promise<void>(resolve=>server.close(()=>resolve()));assert.equal(port.snapshot().pendingRead,false);assert.equal(driver.snapshot().ownedSockets,0);assert.equal(clock.timers.size,0);};
 return {clock,queue,server,driver,port,peers,signal,start,close,connects:()=>connects};
}
test('decoded adapter is lazy, immutable and derives its shard identity from owned driver',{timeout:5000},async()=>{const f=await fixture();try{assert.equal(f.port.shardId,0);assert.equal(Object.isFrozen(f.port),true);await turns();assert.equal(f.connects(),0);assert.throws(()=>new GatewayDecodedShardPort({} as GatewayMessageDriver));}finally{await f.close();}});
test('real wire unknown event burst filters and next complete message retains its identity',{timeout:5000},async()=>{const f=await fixture();try{await f.start();for(let i=0;i<70;i++)f.peers[0]!.send('{"op":42}');f.peers[0]!.send(envelope('MESSAGE_CREATE',message));const item=await f.port.nextEvent(f.signal);assert.equal(item?.kind,'Event');if(item?.kind==='Event'){assert.equal(item.event.kind,'Message');if(item.event.kind==='Message')assert.equal(item.event.event.channel_id,7n);}}finally{await f.close();}});
test('invalid known ignored-event payload reports receive error but does not kill the connection',{timeout:5000},async()=>{const f=await fixture();try{await f.start();f.peers[0]!.send(envelope('MESSAGE_DELETE',{}));f.peers[0]!.send(envelope('MESSAGE_DELETE',{channel_id:'1',id:'2'}));assert.equal((await f.port.nextEvent(f.signal))?.kind,'ReceiveError');assert.deepEqual(await f.port.nextEvent(f.signal),{kind:'Event',event:{kind:'Ignored'}});assert.equal(f.connects(),1);}finally{await f.close();}});
test('cancelled caller does not consume the following message and concurrent reads reject',{timeout:5000},async()=>{const f=await fixture();try{await f.start();const cancel=new AbortController(),reason=new Error('caller stop'),pending=f.port.nextEvent(cancel.signal),rejected=assert.rejects(pending,e=>e===reason);assert.throws(()=>f.port.nextEvent(f.signal),/Concurrent/);cancel.abort(reason);await rejected;f.peers[0]!.send(envelope('MESSAGE_DELETE',{channel_id:'1',id:'2'}));assert.deepEqual(await f.port.nextEvent(f.signal),{kind:'Event',event:{kind:'Ignored'}});}finally{await f.close();}});
test('normal protocol close drains GatewayClose then EOF without another connection',{timeout:5000},async()=>{const f=await fixture();try{await f.start();const closed=once(f.peers[0]!,'close');f.port.requestNormalClose();assert.deepEqual(await f.port.nextEvent(f.signal),{kind:'Event',event:{kind:'GatewayClose'}});assert.equal(await f.port.nextEvent(f.signal),null);const [code,reason]=await closed;assert.equal(code,1000);assert.equal(reason.toString(),'closing connection');assert.equal(f.connects(),1);}finally{await f.close();}});
test('adapter disposal joins its pending read and real socket before resolving',{timeout:5000},async()=>{const f=await fixture();try{await f.start();const read=f.port.nextEvent(f.signal),rejected=assert.rejects(read,/disposed/),first=f.port.dispose();assert.equal(f.port.dispose(),first);await Promise.all([first,rejected]);assert.equal(f.port.snapshot().pendingRead,false);assert.equal(f.port.snapshot().driver.ownedSockets,0);}finally{await f.close();}});
test('paused existing runtime disposes actual adapter without opening a connection',{timeout:5000},async()=>{const f=await fixture(),runtime=GatewayRuntime.fromOwnedPorts([f.port],{reportReceiveErrorDrop:()=>{},reportTriggerFailure:()=>{}});try{await turns();assert.equal(f.connects(),0);assert.equal((await runtime.shutdown(performance.now()+2000)).cleanup.ok,true);assert.equal(runtime.resourcesClosed,true);assert.equal(f.connects(),0);}finally{await f.close();}});
test('real socket driver, full decoder and existing runtime deliver typed lanes then join normal shutdown',{timeout:5000},async()=>{const f=await fixture(),runtime=GatewayRuntime.fromOwnedPorts([f.port],{reportReceiveErrorDrop:()=>{},reportTriggerFailure:()=>{}}),receivers=runtime.takeIngressReceivers(),identity=runtime.subscribeIdentity();try{runtime.activateTypedConsumers();await turns();f.clock.advance(1000);await until(()=>identity.snapshot()!==null);assert.equal(identity.snapshot()?.userId,2n);f.peers[0]!.send(envelope('MESSAGE_CREATE',message));f.peers[0]!.send(envelope('INTERACTION_CREATE',{application_id:'1',authorizing_integration_owners:{},id:'4',token:'offline',type:1}));assert.equal((await receivers.messages.receive())?.event.id,1n);assert.equal((await receivers.normalInteractions.receive())?.event.id,4n);const result=await runtime.shutdown(performance.now()+2000);assert.equal(result.cleanup.ok,true);assert.equal(runtime.resourcesClosed,true);assert.equal(runtime.pendingTasks,0);assert.equal(f.port.snapshot().driver.ownedSockets,0);assert.equal(await runtime.waitForShardExit(),0);}finally{identity.dispose();await runtime.shutdown(performance.now()+2000);await f.close();}});

test('one raw driver cannot be transferred into two decoded owners',{timeout:5000},async()=>{const f=await fixture();try{assert.throws(()=>new GatewayDecodedShardPort(f.driver),/transferred|disposed/);assert.equal(f.connects(),0);}finally{await f.close();}});
test('an already disposed raw driver cannot acquire a new typed owner',async()=>{const queue=new SingleBucketGatewayIdentifyQueue(),driver=new GatewayMessageDriver({token:new SecretToken('offline'),shardNumber:0,shardTotal:1,messageContent:false,identifyQueue:queue,jitter:n=>n});try{await driver.dispose();assert.throws(()=>new GatewayDecodedShardPort(driver),/disposed/);}finally{await driver.dispose();await queue.close();}});
