import assert from 'node:assert/strict';
import {test} from 'node:test';
import {once} from 'node:events';
import {setImmediate as tick} from 'node:timers/promises';
import {zstdCompressSync} from 'node:zlib';
import WebSocket,{WebSocketServer} from 'ws';
import {SecretToken} from '../../../src/config/remote.ts';
import {GatewayMessageDriver,type GatewayDriverClock} from '../../../src/discord/gateway/message-driver.ts';
import {NodeGatewayWebSocket} from '../../../src/discord/gateway/node-websocket.ts';
import {SingleBucketGatewayIdentifyQueue} from '../../../src/discord/gateway/identify-queue.ts';
class Clock implements GatewayDriverClock{
 now=0n;readonly timers=new Set<{at:bigint;finish:()=>void}>();nowNs=()=>this.now;
 sleepUntilNs=(at:bigint,signal:AbortSignal):Promise<void>=>new Promise((resolve,reject)=>{if(signal.aborted){reject(signal.reason);return;}if(at<=this.now){resolve();return;}const finish=()=>{this.timers.delete(item);signal.removeEventListener('abort',abort);resolve();};const abort=()=>{this.timers.delete(item);signal.removeEventListener('abort',abort);reject(signal.reason);};const item={at,finish};this.timers.add(item);signal.addEventListener('abort',abort,{once:true});});
 advance(ms:number){this.now+=BigInt(ms)*1000000n;for(const timer of [...this.timers])if(timer.at<=this.now)timer.finish();}
}
async function turns(n=5){for(let i=0;i<n;i++)await tick();}
async function until(condition:()=>boolean){for(let i=0;i<1000&&!condition();i++)await tick();assert.equal(condition(),true,'condition became ready');}
async function fixture(options:{ack?:boolean;failFirst?:boolean;resume?:boolean}={}){
 const clock=new Clock(),queue=new SingleBucketGatewayIdentifyQueue({clock:{now:()=>Number(clock.now)/1e6,sleepUntil:(deadline,signal)=>clock.sleepUntilNs(BigInt(Math.round(deadline*1e6)),signal)}}),server=new WebSocketServer({host:'127.0.0.1',port:0});await once(server,'listening');const peers:WebSocket[]=[],received:Record<string,unknown>[]=[],urls:string[]=[];
 server.on('connection',peer=>{peers.push(peer);peer.on('error',()=>{});peer.on('message',data=>{const command=JSON.parse(data.toString());received.push(command);if(command.op===2)peer.send(JSON.stringify({op:0,t:'READY',s:1,d:{resume_gateway_url:'wss://gateway.discord.gg',session_id:'offline-session'}}));if(command.op===6)peer.send(JSON.stringify({op:0,t:'RESUMED',s:2,d:{}}));if(command.op===1&&options.ack!==false)peer.send('{"op":11}');});peer.send('{"op":10,"d":{"heartbeat_interval":10000}}');});
 const local=`ws://127.0.0.1:${(server.address() as {port:number}).port}`;
 const driver=new GatewayMessageDriver({token:new SecretToken('offline-fixture'),shardNumber:0,shardTotal:1,messageContent:false,identifyQueue:queue,jitter:interval=>interval,clock,...(options.resume?{session:{id:'old-session',sequence:9n},resumeUrl:'wss://gateway-resume.discord.gg'}:{}),connect:async(url,signal)=>{urls.push(url);if(options.failFirst&&urls.length===1)throw new Error('injected connect failure');return NodeGatewayWebSocket.connectForTest(local,{signal});}});
 const first=async()=>{const pending=driver.nextMessage();await turns();clock.advance(1000);return pending;};
 const ready=async()=>{assert.equal((await first())?.kind,'Text');const next=await driver.nextMessage();assert.equal(next?.kind,'Text');assert.equal(driver.snapshot().phase,'Active');};
 const close=async()=>{await driver.dispose();await queue.close();for(const peer of server.clients)peer.terminate();await new Promise<void>(resolve=>server.close(()=>resolve()));assert.equal(clock.timers.size,0);assert.equal(driver.snapshot().ownedSockets,0);};
 return {clock,queue,server,driver,peers,received,urls,first,ready,close};
}
test('driver is lazy before first receive and closes without starting a socket',{timeout:5000},async()=>{const f=await fixture();try{await turns();assert.equal(f.urls.length,0);assert.equal(f.driver.snapshot().phase,'Disconnected');}finally{await f.close();}});
test('real Hello and Identify lead to Ready through the shared queue',{timeout:5000},async()=>{const f=await fixture();try{await f.ready();assert.equal(f.received.filter(x=>x.op===2).length,1);assert.equal(f.driver.snapshot().hasSession,true);assert.match(f.urls[0]!,/compress=zstd-stream/);}finally{await f.close();}});
test('cancelled consumer retains the connection and does not steal a later packet',{timeout:5000},async()=>{const f=await fixture();try{await f.ready();const cancel=new AbortController(),reason=new Error('cancel read'),pending=f.driver.nextMessage(cancel.signal),rejected=assert.rejects(pending,error=>error===reason);cancel.abort(reason);await rejected;f.peers[0]!.send('{"op":42,"marker":"later"}');assert.deepEqual(await f.driver.nextMessage(),{kind:'Text',text:'{"op":42,"marker":"later"}'});assert.equal(f.urls.length,1);}finally{await f.close();}});
test('normal close sends its source reason, drains close then ends without reconnect',{timeout:5000},async()=>{const f=await fixture();try{await f.ready();const peerClose=once(f.peers[0]!,'close');f.driver.requestNormalClose();const message=await f.driver.nextMessage();assert.equal(message?.kind,'Close');const [code,reason]=await peerClose;assert.equal(code,1000);assert.equal(reason.toString(),'closing connection');assert.equal(await f.driver.nextMessage(),null);f.clock.advance(100000);await turns();assert.equal(f.urls.length,1);}finally{await f.close();}});
test('remote reconnectable close preserves session and emits Resume on next connection',{timeout:5000},async()=>{const f=await fixture();try{await f.ready();f.peers[0]!.close(4000,'retry');assert.equal((await f.driver.nextMessage())?.kind,'Close');const hello=f.driver.nextMessage();await turns();f.clock.advance(1000);assert.equal((await hello)?.kind,'Text');assert.equal((await f.driver.nextMessage())?.kind,'Text');assert.equal(f.received.filter(x=>x.op===2).length,1);assert.equal(f.received.filter(x=>x.op===6).length,1);assert.equal(f.driver.snapshot().phase,'Active');}finally{await f.close();}});
test('fatal Gateway close terminates instead of reconnecting',{timeout:5000},async()=>{const f=await fixture();try{await f.ready();f.peers[0]!.close(4004,'auth');assert.equal((await f.driver.nextMessage())?.kind,'Close');assert.equal(await f.driver.nextMessage(),null);assert.equal(f.driver.snapshot().phase,'FatallyClosed');assert.equal(f.urls.length,1);}finally{await f.close();}});
test('scheduled heartbeat writes once and forwards its ACK',{timeout:5000},async()=>{const f=await fixture();try{await f.ready();const ack=f.driver.nextMessage();await turns();f.clock.advance(10000);assert.deepEqual(await ack,{kind:'Text',text:'{"op":11}'});assert.equal(f.received.filter(x=>x.op===1).length,1);}finally{await f.close();}});
test('missing traffic after sent heartbeat yields abnormal close on next tick',{timeout:5000},async()=>{const f=await fixture({ack:false});try{await f.ready();const next=f.driver.nextMessage();await turns();f.clock.advance(10000);await until(()=>f.received.some(x=>x.op===1));await turns();f.clock.advance(10000);const close=await next;assert.equal(close?.kind,'Close');if(close?.kind==='Close')assert.equal(close.code,1006);assert.equal(f.driver.snapshot().hasSession,true);}finally{await f.close();}});
test('actual compressed wire packet is decoded and corrupt compression requests resumable close',{timeout:5000},async()=>{const f=await fixture();try{await f.ready();f.peers[0]!.send(zstdCompressSync('{"op":42}'));assert.deepEqual(await f.driver.nextMessage(),{kind:'Text',text:'{"op":42}'});const closed=once(f.peers[0]!,'close');f.peers[0]!.send(Buffer.from('bad-zstd'));assert.deepEqual(await f.driver.nextMessage(),{kind:'ReceiveError',message:'binary message could not be decompressed'});assert.equal((await f.driver.nextMessage())?.kind,'Close');assert.equal((await closed)[0],4000);}finally{await f.close();}});
test('failed resume connection clears URL but keeps session and uses increasing backoff',{timeout:5000},async()=>{const f=await fixture({failFirst:true,resume:true});try{assert.deepEqual(await f.first(),{kind:'ReceiveError',message:'failed to reconnect to the gateway'});assert.equal(f.driver.snapshot().attempt,1);const hello=f.driver.nextMessage();await turns();f.clock.advance(1999);await turns();assert.equal(f.urls.length,1);f.clock.advance(1);assert.equal((await hello)?.kind,'Text');assert.equal((await f.driver.nextMessage())?.kind,'Text');assert.match(f.urls[0]!,/gateway-resume/);assert.match(f.urls[1]!,/^wss:\/\/gateway\.discord\.gg\//);assert.equal(f.received.filter(x=>x.op===6).length,1);}finally{await f.close();}});
test('dispose during pending read joins socket, decompressor and timer owners',{timeout:5000},async()=>{const f=await fixture();try{await f.ready();const pending=f.driver.nextMessage(),rejected=assert.rejects(pending,/disposed/);const first=f.driver.dispose();assert.equal(f.driver.dispose(),first);await Promise.all([first,rejected]);assert.equal(f.driver.snapshot().ownedSockets,0);}finally{await f.close();}});
