import assert from 'node:assert/strict';
import {test,type TestContext} from 'node:test';
import {once} from 'node:events';
import http from 'node:http';
import {setImmediate as tick} from 'node:timers/promises';
import WebSocket,{WebSocketServer} from 'ws';
import {NodeGatewayWebSocket,GatewaySocketError} from '../../../src/discord/gateway/node-websocket.ts';
async function server(t:TestContext){const ws=new WebSocketServer({host:'127.0.0.1',port:0,perMessageDeflate:false});await once(ws,'listening');t.after(async()=>{for(const client of ws.clients)client.terminate();await new Promise<void>(resolve=>ws.close(()=>resolve()));});const address=ws.address();assert.equal(typeof address,'object');return {ws,url:`ws://127.0.0.1:${(address as {port:number}).port}`};}
async function connect(t:TestContext,s:Awaited<ReturnType<typeof server>>){const accepted=once(s.ws,'connection');const client=await NodeGatewayWebSocket.connectForTest(s.url);t.after(()=>client.dispose());const [peer]=await accepted as [WebSocket];return {client,peer};}
test('real loopback preserves text/binary and fragmented message boundaries',{timeout:5000},async t=>{const s=await server(t),{client,peer}=await connect(t,s);peer.send('hel',{fin:false});peer.send('lo',{fin:true});peer.send(Buffer.from([0,255,1]));assert.deepEqual(await client.receive(),{kind:'Text',text:'hello'});assert.deepEqual(await client.receive(),{kind:'Binary',bytes:new Uint8Array([0,255,1])});await client.dispose();assert.equal(client.ownedSockets,0);assert.equal(client.pendingOperations,0);});
test('cancelled read consumes no later message and does not dispose connection',{timeout:5000},async t=>{const s=await server(t),{client,peer}=await connect(t,s),cancel=new AbortController(),reason=new Error('reader cancel');const read=client.receive(cancel.signal),rejected=assert.rejects(read,error=>error===reason);cancel.abort(reason);await rejected;peer.send('later');assert.deepEqual(await client.receive(),{kind:'Text',text:'later'});assert.equal(client.disposed,false);});
test('normal close drains queued messages then one close event and EOF',{timeout:5000},async t=>{const s=await server(t),{client,peer}=await connect(t,s);peer.send('before');peer.close(1000,'done');assert.deepEqual(await client.receive(),{kind:'Text',text:'before'});const closed=await client.receive();assert.equal(closed?.kind,'Close');if(closed?.kind==='Close'){assert.equal(closed.code,1000);assert.equal(Buffer.from(closed.reason).toString(),'done');}assert.equal(await client.receive(),null);await client.dispose();assert.equal(client.ownedSockets,0);});
test('client normal close requests actual protocol close rather than immediate terminate',{timeout:5000},async t=>{const s=await server(t),{client,peer}=await connect(t,s),closed=once(peer,'close');client.requestClose();const [code]=await closed;assert.equal(code,1000);assert.equal((await client.receive())?.kind,'Close');});
test('dispose is idempotent, cancels pending read, and joins owned socket',{timeout:5000},async t=>{const s=await server(t),{client}=await connect(t,s),read=client.receive(),rejected=assert.rejects(read,GatewaySocketError);const first=client.dispose();assert.equal(client.dispose(),first);await Promise.all([first,rejected]);assert.equal(client.ownedSockets,0);assert.equal(client.pendingOperations,0);await assert.rejects(client.sendText('after'),GatewaySocketError);await assert.rejects(client.receive(),GatewaySocketError);});
test('text send and binary send snapshot caller bytes before asynchronous transmission',{timeout:5000},async t=>{const s=await server(t),{client,peer}=await connect(t,s);let received=once(peer,'message');await client.sendText('test');let [data,binary]=await received;assert.equal(data.toString(),'test');assert.equal(binary,false);received=once(peer,'message');const bytes=new Uint8Array([1,2,3]),sent=client.sendBinary(bytes);bytes.fill(9);await sent;[data,binary]=await received;assert.deepEqual([...data],[1,2,3]);assert.equal(binary,true);});
test('concurrent read is rejected without interfering with its owner',{timeout:5000},async t=>{const s=await server(t),{client,peer}=await connect(t,s),first=client.receive();await assert.rejects(client.receive(),/Concurrent/);peer.send('owner');assert.deepEqual(await first,{kind:'Text',text:'owner'});});
test('one client cleanup leaves unrelated same-server connection working',{timeout:5000},async t=>{const s=await server(t),a=await connect(t,s),b=await connect(t,s);await a.client.dispose();b.peer.send('alive');assert.deepEqual(await b.client.receive(),{kind:'Text',text:'alive'});assert.equal(b.client.ownedSockets,1);});
test('slow consumer receives a burst in order with stream backpressure',{timeout:5000},async t=>{const s=await server(t),{client,peer}=await connect(t,s);for(let i=0;i<100;i++)peer.send(String(i));await tick();for(let i=0;i<100;i++)assert.deepEqual(await client.receive(),{kind:'Text',text:String(i)});});
test('handshake timeout actually closes the pending upgrade socket',{timeout:5000},async t=>{const listener=http.createServer();const sockets=new Set<import('node:stream').Duplex>();let accepted!:()=>void;const seen=new Promise<void>(resolve=>{accepted=resolve;});let closed!:()=>void;const ended=new Promise<void>(resolve=>{closed=resolve;});listener.on('upgrade',(_req,socket)=>{sockets.add(socket);socket.on('error',()=>{});socket.once('close',()=>{sockets.delete(socket);closed();});socket.once('end',()=>socket.end());socket.resume();accepted();});listener.listen(0,'127.0.0.1');await once(listener,'listening');t.after(async()=>{for(const socket of sockets)socket.destroy();await new Promise<void>(resolve=>listener.close(()=>resolve()));});const port=(listener.address() as {port:number}).port;const connecting=NodeGatewayWebSocket.connectForTest(`ws://127.0.0.1:${port}`,{timeoutMs:1000});const rejected=assert.rejects(connecting,GatewaySocketError);await seen;await rejected;await ended;assert.equal(sockets.size,0);});
test('abort during handshake joins the pending socket and preserves cancellation reason',{timeout:5000},async t=>{const listener=http.createServer(),sockets=new Set<import('node:stream').Duplex>();let accepted!:()=>void;const seen=new Promise<void>(resolve=>{accepted=resolve;});listener.on('upgrade',(_req,socket)=>{sockets.add(socket);socket.on('error',()=>{});socket.once('close',()=>sockets.delete(socket));socket.once('end',()=>socket.end());socket.resume();accepted();});listener.listen(0,'127.0.0.1');await once(listener,'listening');t.after(async()=>{for(const socket of sockets)socket.destroy();await new Promise<void>(resolve=>listener.close(()=>resolve()));});const port=(listener.address() as {port:number}).port,cancel=new AbortController(),reason=new Error('cancel connect');const connecting=NodeGatewayWebSocket.connectForTest(`ws://127.0.0.1:${port}`,{signal:cancel.signal}),rejected=assert.rejects(connecting,error=>error===reason);await seen;cancel.abort(reason);await rejected;});
test('redirect response is not followed to another endpoint',{timeout:5000},async t=>{let hits=0;const listener=http.createServer((_req,res)=>{hits++;res.writeHead(302,{location:'ws://127.0.0.1:9'});res.end();});listener.listen(0,'127.0.0.1');await once(listener,'listening');t.after(()=>new Promise<void>(resolve=>listener.close(()=>resolve())));const port=(listener.address() as {port:number}).port;await assert.rejects(NodeGatewayWebSocket.connectForTest(`ws://127.0.0.1:${port}`),GatewaySocketError);assert.equal(hits,1);});
test('destination/timeout validation and pre-abort reject before opening sockets',async()=>{for(const url of ['ws://gateway.discord.gg','wss://evil.example','wss://gateway.discord.gg:444','wss://name:secret@gateway.discord.gg','wss://gateway.discord.gg/#fragment'])await assert.rejects(NodeGatewayWebSocket.connect(url),TypeError);await assert.rejects(NodeGatewayWebSocket.connectForTest('ws://localhost:1'),TypeError);await assert.rejects(NodeGatewayWebSocket.connectForTest('ws://127.0.0.1:1',{timeoutMs:0}),RangeError);const cancel=new AbortController(),reason=new Error('pre-abort');cancel.abort(reason);await assert.rejects(NodeGatewayWebSocket.connectForTest('ws://127.0.0.1:1',{signal:cancel.signal}),error=>error===reason);});
test('handshake has an absolute deadline even while peer trickles partial headers',{timeout:5000},async t=>{const listener=http.createServer(),owned=new Set<import('node:stream').Duplex>();let timer:ReturnType<typeof setInterval>|undefined,finish:ReturnType<typeof setTimeout>|undefined;listener.on('upgrade',(_req,socket)=>{owned.add(socket);socket.on('error',()=>{});socket.once('end',()=>socket.end());socket.once('close',()=>{owned.delete(socket);clearInterval(timer);clearTimeout(finish);});socket.write('HTTP/1.1 101 Switching Protocols\r\n');timer=setInterval(()=>socket.write('X-Trickle: x\r\n'),20);finish=setTimeout(()=>socket.destroy(),700);socket.resume();});listener.listen(0,'127.0.0.1');await once(listener,'listening');t.after(async()=>{clearInterval(timer);clearTimeout(finish);for(const socket of owned)socket.destroy();await new Promise<void>(resolve=>listener.close(()=>resolve()));});const port=(listener.address() as {port:number}).port,start=performance.now();await assert.rejects(NodeGatewayWebSocket.connectForTest(`ws://127.0.0.1:${port}`,{timeoutMs:100}),GatewaySocketError);assert.ok(performance.now()-start<500,'incoming header bytes must not extend the absolute handshake deadline');});
