import assert from 'node:assert/strict';
import {test} from 'node:test';
import {createServer,type RequestListener} from 'node:http';
import {once} from 'node:events';
import {setImmediate as tick} from 'node:timers/promises';
import WebSocket,{WebSocketServer} from 'ws';
import {RecommendedGateway,GatewayRecommendedStartError} from '../../../src/discord/gateway/recommended.ts';
import {DiscordGatewayModelError,isDiscordGatewayModelError} from '../../../src/discord/model/gateway-info.ts';
import type {GatewayDriverClock} from '../../../src/discord/gateway/message-driver.ts';
class Clock implements GatewayDriverClock{
 now=0n;readonly timers=new Set<{at:bigint;finish:()=>void}>();nowNs=()=>this.now;
 sleepUntilNs=(at:bigint,signal:AbortSignal):Promise<void>=>new Promise((resolve,reject)=>{if(signal.aborted){reject(signal.reason);return;}if(at<=this.now){resolve();return;}const finish=()=>{this.timers.delete(item);signal.removeEventListener('abort',abort);resolve();};const abort=()=>{this.timers.delete(item);signal.removeEventListener('abort',abort);reject(signal.reason);};const item={at,finish};this.timers.add(item);signal.addEventListener('abort',abort,{once:true});});
 advance(ms:number){this.now+=BigInt(ms)*1000000n;for(const t of [...this.timers])if(t.at<=this.now)t.finish();}
}
async function turns(){for(let i=0;i<12;i++)await tick();}
async function until(predicate:()=>boolean){for(let i=0;i<2000&&!predicate();i++)await tick();assert.equal(predicate(),true);}
const info=(shards:number)=>({shards,url:'not-a-network-authority',session_start_limit:{max_concurrency:99,remaining:0,total:0,reset_after:0}});
const ready={application:{id:'1',flags:0},guilds:[],resume_gateway_url:'wss://gateway.discord.gg',session_id:'offline',user:{id:'2',username:'bot',discriminator:'0',mfa_enabled:false},v:10};
async function fixture(shards=1,handler?:RequestListener){
 let requests=0;const http=createServer((req,res)=>{requests++;assert.equal(req.headers.authorization,undefined);if(handler)handler(req,res);else res.end(JSON.stringify(info(shards)));});await new Promise<void>(r=>http.listen(0,'127.0.0.1',r));
 const ws=new WebSocketServer({host:'127.0.0.1',port:0});await once(ws,'listening');const peers:WebSocket[]=[],identifies:unknown[]=[],clock=new Clock();
 ws.on('connection',peer=>{peers.push(peer);peer.on('error',()=>{});peer.on('message',raw=>{const value=JSON.parse(raw.toString());if(value.op===2){identifies.push(value.d.shard);peer.send(JSON.stringify({op:0,t:'READY',s:1,d:ready}));}if(value.op===1)peer.send('{"op":11}');});peer.send('{"op":10,"d":{"heartbeat_interval":60000}}');});
 const options={httpOrigin:`http://127.0.0.1:${(http.address() as {port:number}).port}/api/v10/`,gatewayUrl:`ws://127.0.0.1:${(ws.address() as {port:number}).port}/`,messageContent:false,reportReceiveErrorDrop:()=>{},reportTriggerFailure:()=>{},reportHttpError:()=>{},jitter:(n:bigint)=>n,clock};
 let owner:RecommendedGateway|undefined;
 return {options,clock,peers,identifies,requests:()=>requests,start:async()=>owner=await RecommendedGateway.startPausedForTest(options),close:async()=>{await owner?.close(performance.now()+2000);for(const peer of ws.clients)peer.terminate();await new Promise<void>(r=>ws.close(()=>r()));http.closeAllConnections();await new Promise<void>((r,j)=>http.close(e=>e?j(e):r()));assert.equal(clock.timers.size,0);}};
}
test('recommended discovery opens no Gateway until typed activation and keeps default queue despite metadata',{timeout:5000},async()=>{const f=await fixture();try{const owner=await f.start();await turns();assert.equal(f.requests(),1);assert.equal(f.peers.length,0);assert.equal(owner.snapshot().queue.remaining,1000);assert.throws(()=>owner.runtime.activateTypedConsumers());owner.runtime.takeIngressReceivers();owner.runtime.activateTypedConsumers();await turns();f.clock.advance(1000);await until(()=>f.identifies.length===1);assert.deepEqual(f.identifies,[[0,1]]);}finally{await f.close();}});
test('two recommended shards share one five-second identify queue',{timeout:5000},async()=>{const f=await fixture(2);try{const owner=await f.start();owner.runtime.takeIngressReceivers();owner.runtime.activateTypedConsumers();await turns();f.clock.advance(1000);await until(()=>f.peers.length===2&&f.identifies.length===1);await turns();assert.equal(f.identifies.length,1);f.clock.advance(5000);await until(()=>f.identifies.length===2);assert.deepEqual([...f.identifies].sort(),[[0,2],[1,2]]);}finally{await f.close();}});
test('runtime shutdown preserves shared HTTP until explicit outer close, which is idempotent',{timeout:5000},async()=>{const f=await fixture();try{const owner=await f.start();await owner.runtime.shutdown(performance.now()+2000);assert.equal(owner.runtime.resourcesClosed,true);assert.equal(owner.snapshot().closed,false);assert.equal((await owner.http.getGatewayBot()).shards,1n);assert.equal(f.requests(),2);const first=owner.close();assert.equal(owner.close(),first);await first;assert.equal(owner.snapshot().closed,true);assert.equal(owner.snapshot().httpSockets,0);assert.equal(owner.snapshot().queue.closed,true);await assert.rejects(owner.http.getGatewayBot());}finally{await f.close();}});
test('zero recommended shards are accepted and close all shared resources',{timeout:5000},async()=>{const f=await fixture(0);try{const owner=await f.start();assert.equal(owner.runtime.pendingTasks,0);assert.equal(await owner.runtime.waitForShardExit(),null);await owner.close();assert.equal(owner.snapshot().httpRequests,0);assert.equal(f.peers.length,0);}finally{await f.close();}});
test('discovery request versus model failures retain pinned stage and display',{timeout:5000},async()=>{for(const kind of ['Request','Deserializing'] as const){const f=await fixture(1,(_req,res)=>{res.statusCode=kind==='Request'?500:200;res.end('{}');});try{await assert.rejects(f.start(),e=>e instanceof GatewayRecommendedStartError&&e.kind===kind&&e.message==='failed to start recommended Discord gateway shards: '+(kind==='Request'?'request failed to complete':"payload isn't a recognized type"));assert.equal(f.peers.length,0);}finally{await f.close();}}});
test('pre-aborted startup preserves reason and opens no network connection',{timeout:5000},async()=>{const f=await fixture();try{const cancel=new AbortController(),reason=new Error('preabort');cancel.abort(reason);await assert.rejects(RecommendedGateway.startPausedForTest({...f.options,signal:cancel.signal}),e=>e===reason);assert.equal(f.requests(),0);assert.equal(f.peers.length,0);}finally{await f.close();}});
test('invalid callback and non-loopback gateway are rejected before discovery',{timeout:5000},async()=>{const f=await fixture();try{await assert.rejects(RecommendedGateway.startPausedForTest({...f.options,reportHttpError:async()=>{}}),/synchronous/);await assert.rejects(RecommendedGateway.startPausedForTest({...f.options,gatewayUrl:'wss://example.com/'}),/loopback/);let calls=0;const options={...f.options};Object.defineProperty(options,'messageContent',{get(){calls++;return false;}});await assert.rejects(RecommendedGateway.startPausedForTest(options));assert.equal(calls,0);assert.equal(f.requests(),0);}finally{await f.close();}});
test('model stage brand is passive and cannot be forged by a prototype',()=>{assert.equal(isDiscordGatewayModelError(new DiscordGatewayModelError()),true);assert.equal(isDiscordGatewayModelError(Object.create(DiscordGatewayModelError.prototype)),false);let calls=0;const proxy=new Proxy({}, {getPrototypeOf(){calls++;throw new Error('trap');},get(){calls++;throw new Error('trap');}});assert.equal(isDiscordGatewayModelError(proxy),false);assert.equal(calls,0);});
test('actual discovery and websocket compose into typed runtime identity and interaction lanes',{timeout:5000},async()=>{const f=await fixture();try{const owner=await f.start(),receivers=owner.runtime.takeIngressReceivers(),identity=owner.runtime.subscribeIdentity();try{owner.runtime.activateTypedConsumers();await turns();f.clock.advance(1000);await until(()=>identity.snapshot()!==null);assert.equal(identity.snapshot()?.userId,2n);f.peers[0]!.send(JSON.stringify({op:0,t:'INTERACTION_CREATE',s:2,d:{application_id:'1',authorizing_integration_owners:{},id:'4',token:'offline',type:1}}));assert.equal((await receivers.normalInteractions.receive())?.event.id,4n);await owner.close(performance.now()+2000);assert.equal(owner.runtime.pendingTasks,0);assert.equal(owner.snapshot().httpSockets,0);}finally{identity.dispose();}}finally{await f.close();}});
test('abort before discovery response joins native HTTP sockets without starting Gateway',{timeout:5000},async()=>{let received=false,closed=false;const f=await fixture(1,(req,_res)=>{received=true;req.socket.once('close',()=>{closed=true;});});try{const cancel=new AbortController(),reason=new Error('cancel outstanding discovery'),pending=RecommendedGateway.startPausedForTest({...f.options,signal:cancel.signal}),rejected=assert.rejects(pending,e=>e===reason);await until(()=>received);cancel.abort(reason);await rejected;await until(()=>closed);assert.equal(f.peers.length,0);}finally{await f.close();}});
test('outer owner captures HTTP cleanup before callers can replace the public method',{timeout:5000},async()=>{const f=await fixture();try{const owner=await f.start();let calls=0;Object.defineProperty(owner.http,'close',{value:async()=>{calls++;}});await owner.close();assert.equal(calls,0);assert.equal(owner.snapshot().httpSockets,0);assert.equal(owner.snapshot().closed,true);}finally{await f.close();}});
