import assert from 'node:assert/strict';
import {test} from 'node:test';
import {setImmediate as tick} from 'node:timers/promises';
import {GatewayRuntime} from '../../../src/discord/gateway/runtime.ts';
import type {GatewayShardItem,GatewayShardPort} from '../../../src/discord/gateway/shard-task.ts';
import {GatewayShutdownReportingError} from '../../../src/discord/gateway/shutdown.ts';
type DTO={readonly id:number};
class Port implements GatewayShardPort<DTO>{
 readonly shardId:number;polls=0;closes=0;disposed=0;readonly items:GatewayShardItem<DTO>[]=[];resolve:((value:GatewayShardItem<DTO>|null)=>void)|undefined;
 constructor(id=0){this.shardId=id;}
 nextEvent(signal:AbortSignal):Promise<GatewayShardItem<DTO>|null>{this.polls++;if(this.items.length)return Promise.resolve(this.items.shift()!);return new Promise((resolve,reject)=>{const abort=()=>{this.resolve=undefined;reject(signal.reason);};this.resolve=value=>{signal.removeEventListener('abort',abort);this.resolve=undefined;resolve(value);};signal.addEventListener('abort',abort,{once:true});if(signal.aborted)abort();});}
 requestNormalClose():void{this.closes++;this.resolve?.({kind:'Event',event:{kind:'GatewayClose'}});}
 async dispose():Promise<void>{this.disposed++;this.resolve?.(null);}
}
const options=()=>({reportReceiveErrorDrop:()=>{},reportTriggerFailure:()=>{}});
const deadline=()=>performance.now()+2000;
test('paused owner never polls and shutdown joins disposal',async()=>{const p=new Port(),r=GatewayRuntime.fromOwnedPorts([p],options());await tick();assert.equal(p.polls,0);assert.equal(r.pendingTasks,1);assert.equal((await r.shutdown(deadline())).cleanup.ok,true);assert.equal(p.disposed,1);assert.equal(p.closes,0);assert.equal(r.pendingTasks,0);assert.equal(r.resourcesClosed,true);assert.equal(await r.waitForShardExit(),0);assert.equal(await r.waitForShardExit(),null);assert.throws(()=>r.takeIngressReceivers());});
test('receiver transfer exactly once before activation',async()=>{const p=new Port(),r=GatewayRuntime.fromOwnedPorts([p],options());assert.throws(()=>r.activateTypedConsumers(),/must be taken/);r.takeIngressReceivers();assert.throws(()=>r.takeIngressReceivers(),/already been taken/);r.activateTypedConsumers();assert.throws(()=>r.activateTypedConsumers(),/already been activated/);await tick();assert.equal(p.polls,1);await r.shutdown(deadline());assert.equal(p.closes,1);assert.equal(p.disposed,1);});
test('first shutdown pins promise and cause',async()=>{const p=new Port(),r=GatewayRuntime.fromOwnedPorts([p],options()),first=r.shutdown(deadline());assert.equal(r.shutdownForCause(-1,999),first);assert.equal(r.shutdown(),first);await first;assert.equal(p.disposed,1);assert.equal(r.shutdown(),first);});
test('accepted payload drains after task senders close',async()=>{const p=new Port();p.items.push({kind:'Event',event:{kind:'Interaction',event:Object.freeze({id:7})}});const r=GatewayRuntime.fromOwnedPorts([p],options()),receivers=r.takeIngressReceivers();r.activateTypedConsumers();await tick();await r.shutdown(deadline());assert.equal((await receivers.normalInteractions.receive())?.event.id,7);assert.equal(await receivers.normalInteractions.receive(),null);assert.equal(r.publicationSnapshot().interactionsAccepted,1n);});
test('stop barrier routes later interaction to reserved lane',async()=>{const p=new Port(),r=GatewayRuntime.fromOwnedPorts([p],options()),receivers=r.takeIngressReceivers();r.activateTypedConsumers();await tick();r.beginStopping();p.resolve?.({kind:'Event',event:{kind:'Interaction',event:Object.freeze({id:8})}});await tick();assert.equal(receivers.normalInteractions.tryReceive().kind,'Empty');assert.equal((await receivers.reservedInteractions.receive())?.tag,'Stopping');await r.shutdown(deadline());});
test('trigger error retained and surviving adapter joined',async()=>{const failure=new Error('source failed'),a=new Port(1),b=new Port(2),reported:unknown[]=[];a.nextEvent=async()=>{throw failure;};const r=GatewayRuntime.fromOwnedPorts([a,b],{...options(),reportTriggerFailure:(shard,error)=>{reported.push(shard,error.taskError);}});r.takeIngressReceivers();r.activateTypedConsumers();assert.equal(await r.waitForShardExit(),1);const result=await r.shutdownForCause(deadline(),1);assert.equal(result.trigger?.ok,false);assert.deepEqual(reported,[1,failure]);assert.equal(result.cleanup.ok,true);assert.equal(b.disposed,1);assert.equal(r.pendingTasks,0);assert.equal(await r.waitForShardExit(),2);assert.equal(await r.waitForShardExit(),null);});
test('report failure cannot abandon sibling',async()=>{const failure=new Error('source'),diagnostic=new Error('report'),a=new Port(1),b=new Port(2);a.nextEvent=async()=>{throw failure;};const r=GatewayRuntime.fromOwnedPorts([a,b],{...options(),reportTriggerFailure:()=>{throw diagnostic;}});r.takeIngressReceivers();r.activateTypedConsumers();await r.waitForShardExit();await assert.rejects(r.shutdownForCause(deadline(),1),error=>error instanceof GatewayShutdownReportingError&&error.reportingError===diagnostic);assert.equal(b.disposed,1);assert.equal(r.resourcesClosed,true);});
test('captured port methods resist replacement after transfer',async()=>{const p=new Port(),r=GatewayRuntime.fromOwnedPorts([p],options());p.nextEvent=async()=>{throw new Error('replacement read');};p.dispose=async()=>{throw new Error('replacement disposal');};p.requestNormalClose=()=>{throw new Error('replacement close');};r.takeIngressReceivers();r.activateTypedConsumers();await tick();assert.equal(p.polls,1);assert.equal((await r.shutdown(deadline())).cleanup.ok,true);assert.equal(p.disposed,1);assert.equal(p.closes,1);});
test('invalid later port leaves earlier ownership with caller without invoking getter',async()=>{const p=new Port(),bad=new Port(1);Object.defineProperty(bad,'dispose',{get(){throw new Error('getter executed');}});assert.throws(()=>GatewayRuntime.fromOwnedPorts([p,bad],options()),/Invalid gateway adapter method/);await tick();assert.equal(p.polls,0);assert.equal(p.disposed,0);});
test('duplicate ports, shard ids and invalid capacities reject before transfer',()=>{const p=new Port();assert.throws(()=>GatewayRuntime.fromOwnedPorts([p,p],options()));assert.throws(()=>GatewayRuntime.fromOwnedPorts([p,new Port()],options()));assert.throws(()=>GatewayRuntime.fromOwnedPorts([p],{...options(),ingressConfig:{interactionCapacity:0,reservedInteractionCapacity:1,messageCapacity:1,receiveErrorCapacity:1}}));assert.equal(p.disposed,0);});
test('empty runtime exit stream closes but explicit shutdown still required',async()=>{const r=GatewayRuntime.fromOwnedPorts<DTO>([],options());assert.equal(await r.waitForShardExit(),null);assert.equal(r.resourcesClosed,false);r.takeIngressReceivers();r.activateTypedConsumers();assert.equal((await r.shutdown()).cleanup.ok,true);assert.equal(r.resourcesClosed,true);});
test('invalid shutdown scope leaves runtime usable',async()=>{const p=new Port(),r=GatewayRuntime.fromOwnedPorts([p],options());assert.throws(()=>r.shutdown(-1));assert.equal(p.disposed,0);r.takeIngressReceivers();r.activateTypedConsumers();await r.shutdown(deadline());assert.equal(p.disposed,1);});
test('short deadline forces and joins cooperative pending read before closing resources',async()=>{const p=new Port();p.requestNormalClose=()=>{p.closes++;};const r=GatewayRuntime.fromOwnedPorts([p],options());r.takeIngressReceivers();r.activateTypedConsumers();await tick();const result=await r.shutdown(performance.now()+200);assert.equal(result.cleanup.ok,false);if(!result.cleanup.ok)assert.equal(result.cleanup.error.kind,'Timeout');assert.equal(p.closes,1);assert.equal(p.disposed,1);assert.equal(r.pendingTasks,0);assert.equal(r.resourcesClosed,true);});
test('shutdown does not claim completion until actual disposal promise settles',async()=>{const p=new Port();let release!:()=>void;const disposal=new Promise<void>(resolve=>{release=resolve;});p.dispose=async()=>{p.disposed++;await disposal;};const r=GatewayRuntime.fromOwnedPorts([p],options()),shutdown=r.shutdown(deadline());await tick();assert.equal(p.disposed,1);assert.equal(r.pendingTasks,1);assert.equal(r.resourcesClosed,false);release();assert.equal((await shutdown).cleanup.ok,true);assert.equal(r.resourcesClosed,true);});
test('cancelled exit receive neither stops owner nor consumes next exit',async()=>{const p=new Port(),r=GatewayRuntime.fromOwnedPorts([p],options()),cancel=new AbortController(),reason=new Error('cancel');const waiting=r.waitForShardExit(cancel.signal);cancel.abort(reason);await assert.rejects(waiting,error=>error===reason);assert.equal(r.pendingTasks,1);await r.shutdown(deadline());assert.equal(await r.waitForShardExit(),0);});
test('invalid async synchronous hooks reject before port ownership transfer',()=>{const p=new Port();assert.throws(()=>GatewayRuntime.fromOwnedPorts([p],{...options(),reportTriggerFailure:async()=>{}}));assert.equal(p.disposed,0);assert.equal(p.polls,0);});
test('actual disposal failure remains a join error while settled resources close',async()=>{const p=new Port(),failure=new Error('dispose');p.dispose=async()=>{p.disposed++;throw failure;};const r=GatewayRuntime.fromOwnedPorts([p],options()),result=await r.shutdown(deadline());assert.equal(result.cleanup.ok,false);if(!result.cleanup.ok){assert.equal(result.cleanup.error.kind,'Join');assert.equal(result.cleanup.error.taskError,failure);}assert.equal(r.pendingTasks,0);assert.equal(r.resourcesClosed,true);});
