import assert from 'node:assert/strict';
import {test} from 'node:test';
import * as http from 'node:http';
import {setImmediate as tick} from 'node:timers/promises';
import {DiscordChannelClient} from '../../src/discord/channel-client.ts';
import {DiscordResponseEngine,type DiscordWireRequest} from '../../src/discord/response-engine.ts';
import {NodeDiscordHttpWire} from '../../src/discord/node-http-wire.ts';
import {DiscordChannelRateLimiter} from '../../src/discord/rate-header-adapter.ts';
import {decodeDiscordGatewayBotInfo as decode,DiscordGatewayModelError} from '../../src/discord/model/gateway-info.ts';
const info={session_start_limit:{max_concurrency:1,remaining:999,reset_after:60000,total:1000},shards:2,url:'wss://gateway.discord.gg'};
const deferred=()=>{let resolve!:()=>void;const promise=new Promise<void>(r=>{resolve=r;});return {promise,resolve};};
async function fixture(handler:http.RequestListener,run:(client:DiscordChannelClient,origin:string)=>Promise<void>,globalLimit=50){const server=http.createServer(handler);await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${(server.address() as {port:number}).port}/api/v10/`,client=await DiscordChannelClient.create({token:null,testOrigin:origin,report:()=>{},globalLimit});try{await run(client,origin);}finally{await client.close();server.closeAllConnections();await new Promise<void>((resolve,reject)=>server.close(e=>e?reject(e):resolve()));}}
test('complete BotConnectionInfo validates every required nested field and freezes the result',()=>{const value=decode(JSON.stringify(info));assert.equal(value.shards,2n);assert.equal(Object.isFrozen(value),true);assert.equal(Object.isFrozen(value.session_start_limit),true);for(const key of Object.keys(info)){const missing:Record<string,unknown>={...info};delete missing[key];assert.throws(()=>decode(JSON.stringify(missing)));}for(const key of Object.keys(info.session_start_limit)){const limits:Record<string,unknown>={...info.session_start_limit};delete limits[key];assert.throws(()=>decode(JSON.stringify({...info,session_start_limit:limits})));}});
test('Gateway recommendation model preserves exact integer widths and does not authorize URL or allocation',()=>{const raw='{"session_start_limit":{"max_concurrency":65535,"remaining":4294967295,"reset_after":18446744073709551615,"total":0},"shards":4294967295,"url":"not-a-url"}';const value=decode(raw);assert.equal(value.shards,4294967295n);assert.equal(value.session_start_limit.reset_after,18446744073709551615n);assert.equal(decode(JSON.stringify({...info,shards:0})).shards,0n);for(const limits of [{...info.session_start_limit,max_concurrency:65536},{...info.session_start_limit,remaining:-1},{...info.session_start_limit,total:4294967296}])assert.throws(()=>decode(JSON.stringify({...info,session_start_limit:limits})));assert.throws(()=>decode(JSON.stringify({...info,shards:4294967296})));});
test('Gateway recommendation duplicate fields reject while unknown fields remain ignored',()=>{const raw=JSON.stringify(info);assert.throws(()=>decode(raw.slice(0,-1)+',"shards":2}'));assert.throws(()=>decode(raw.replace('"remaining":999','"remaining":999,"remaining":999')));assert.doesNotThrow(()=>decode(raw.slice(0,-1)+',"future":1e999}'));});
test('actual owned HTTP client performs exact GET gateway/bot with empty body and no test credentials',{timeout:5000},async()=>{const seen:{method:string|undefined;url:string|undefined;auth:string|undefined;body:string}[]=[];await fixture((req,res)=>{let body='';req.on('data',part=>{body+=part;});req.on('end',()=>{seen.push({method:req.method,url:req.url,auth:req.headers.authorization,body});res.end(JSON.stringify(info));});},async client=>{assert.equal((await client.getGatewayBot()).shards,2n);assert.deepEqual(seen,[{method:'GET',url:'/api/v10/gateway/bot',auth:undefined,body:''}]);assert.equal(client.activeRequests,0);});});
test('discovery success status with malformed/invalid UTF8/BOM body is a distinct safe model failure',{timeout:5000},async()=>{for(const bytes of [Buffer.from('{}'),Buffer.from([255]),Buffer.from('\ufeff'+JSON.stringify(info))])await fixture((_req,res)=>res.end(bytes),async client=>{await assert.rejects(client.getGatewayBot(),e=>e instanceof DiscordGatewayModelError&&!e.message.includes('session_start_limit'));assert.equal(client.activeRequests,0);});});
test('discovery 429 retries the same GET through shared rate ownership without decoding rate body',{timeout:5000},async()=>{let calls=0;const methods:string[]=[];await fixture((req,res)=>{methods.push(req.method!);calls++;res.setHeader('x-ratelimit-scope','user');res.setHeader('x-ratelimit-bucket','discovery');res.setHeader('x-ratelimit-limit','1');res.setHeader('x-ratelimit-remaining','0');res.setHeader('x-ratelimit-reset-after','0.02');if(calls===1){res.writeHead(429);res.end('ignored rate body');}else res.end(JSON.stringify(info));},async client=>{assert.equal((await client.getGatewayBot()).shards,2n);assert.deepEqual(methods,['GET','GET']);});});
test('discovery and channel requests share one global limiter and queued cancellation is joined',{timeout:5000},async()=>{let calls=0;await fixture((_req,res)=>{calls++;res.end(JSON.stringify(info));},async client=>{await client.getGatewayBot();const reason=new Error('stop queued'),pending=client.createTyping(1n,new AbortController().signal),rejected=assert.rejects(pending,e=>e===reason);await tick();assert.equal(calls,1);await client.close(reason);await rejected;assert.equal(client.ownedSockets,0);assert.equal(client.activeRequests,0);},1);});
test('identical bucket bytes do not merge gateway no-resource and channel-resource queues',{timeout:5000},async()=>{const paths:string[]=[];await fixture((req,res)=>{paths.push(req.url!);res.setHeader('x-ratelimit-scope','user');res.setHeader('x-ratelimit-bucket','same');res.setHeader('x-ratelimit-limit','1');res.setHeader('x-ratelimit-remaining','0');res.setHeader('x-ratelimit-reset-after','3600');if(req.url?.endsWith('/typing')){res.writeHead(204);res.end();}else res.end(JSON.stringify(info));},async client=>{await client.getGatewayBot();await client.createTyping(1n,AbortSignal.timeout(1000));assert.deepEqual(paths,['/api/v10/gateway/bot','/api/v10/channels/1/typing']);});});
test('discovery stalled body is cancelled and wire sockets are joined on client close',{timeout:5000},async()=>{
 const entered=deferred(),original=NodeDiscordHttpWire.prototype.request;
 // Observe the actual native body-read call, not the server's earlier write.
 NodeDiscordHttpWire.prototype.request=async function(this:NodeDiscordHttpWire,input,timeout,signal){const response=await original.call(this,input,timeout,signal);return {...response,bytes(){const work=response.bytes();entered.resolve();return work;}};};
 try{await fixture((_req,res)=>{res.writeHead(200);res.write('{');},async client=>{const pending=client.getGatewayBot(),rejected=assert.rejects(pending,e=>e instanceof DiscordGatewayModelError);await entered.promise;await client.close();await rejected;assert.equal(client.activeRequests,0);assert.equal(client.ownedSockets,0);});}finally{NodeDiscordHttpWire.prototype.request=original;}
});
test('discovery pre-abort opens no socket and preserves exact cancellation identity',{timeout:5000},async()=>{let calls=0;await fixture((_req,res)=>{calls++;res.end(JSON.stringify(info));},async client=>{const cancel=new AbortController(),reason=new Error('cancel discovery');cancel.abort(reason);await assert.rejects(client.getGatewayBot(cancel.signal),e=>e===reason);assert.equal(calls,0);});});
test('wire and rate allow only GET gateway/bot, not arbitrary GET or method/path combinations',{timeout:5000},async()=>{let calls=0;await fixture((_req,res)=>{calls++;res.end(JSON.stringify(info));},async(_client,origin)=>{const wire=new NodeDiscordHttpWire(origin),rate=new DiscordChannelRateLimiter({report:()=>{}}),signal=new AbortController().signal;try{for(const request of [{method:'GET',path:'channels/1/typing',body:null},{method:'POST',path:'gateway/bot',body:null},{method:'GET',path:'gateway/bot?x',body:null},{method:'GET',path:'gateway/bot',body:'{}'}] as const)await assert.rejects(wire.request({...request,authorization:null},1000,signal));await assert.rejects(rate.acquire('GET','channels/1/typing',signal));await assert.rejects(rate.acquire('POST','gateway/bot',signal));assert.equal(calls,0);}finally{await rate.close();await wire.close();}});});
test('discovery unauthorized status invalidates the same engine before body parsing and later typing',async()=>{const seen:DiscordWireRequest[]=[];let complete=0,released=0;const engine=new DiscordResponseEngine({token:'offline-fixture',decoder:{decode:()=>1n},rateLimiter:{acquire:async()=>({complete(){complete++;},release(){}})},wire:{request:async request=>{seen.push(request);return {status:401,headers:new Map(),bytes:async()=>Buffer.from('bad body'),release:async()=>{released++;}};}}});try{await assert.rejects(engine.getGatewayBot(),/unconfirmed/);assert.equal(engine.authorizationInvalidated,true);await assert.rejects(engine.createTyping(1n,new AbortController().signal),/invalidated/);assert.equal(seen.length,1);assert.equal(seen[0]!.method,'GET');assert.equal(seen[0]!.authorization,'Bot offline-fixture');assert.equal(complete,1);assert.equal(released,1);}finally{await engine.close();}});
