import assert from 'node:assert/strict';import {test} from 'node:test';
import {DiscordChannelRateState,type RateClock} from '../../src/discord/channel-rate-state.ts';import {interactionCallbackRequest,isInteractionCallbackPath} from '../../src/discord/interaction-callback-request.ts';import {pongResponse} from '../../src/discord/interaction-response.ts';
class Clock implements RateClock{value=0;next=0;timers=new Map<number,{at:number;run:()=>void}>();now=()=>this.value;schedule=(at:number,run:()=>void)=>{const id=++this.next;this.timers.set(id,{at,run});return()=>{this.timers.delete(id);};};advance(ms:number){const end=this.value+ms;for(let i=0;i<1000;i++){const next=[...this.timers].sort((a,b)=>a[1].at-b[1].at)[0];if(next===undefined||next[1].at>end){this.value=end;return;}this.value=next[1].at;this.timers.delete(next[0]);next[1].run();}throw new Error('timer spin');}}
const signal=()=>new AbortController().signal,callback=(id=1)=>`interactions/${id}/offline_token/callback`,flush=async()=>{await Promise.resolve();await Promise.resolve();};
test('callback request preserves exact route/body and never carries bot authorization',()=>{assert.deepEqual(interactionCallbackRequest(1n,'offline_token',pongResponse()),{method:'POST',path:callback(),body:'{"type":1}',authorization:null});assert.equal(isInteractionCallbackPath(callback()),true);});
test('unsupported tokens and route normalization tricks fail before IO',()=>{for(const token of ['', '.', '..','a/b','a?b','a#b','a%2fb','a\n','한글']){assert.throws(()=>interactionCallbackRequest(1n,token,pongResponse()));assert.equal(isInteractionCallbackPath(`interactions/1/${token}/callback`),false);}for(const path of ['interactions/0/t/callback','interactions/01/t/callback','interactions/18446744073709551616/t/callback',callback()+'?x',callback()+'\n'])assert.equal(isInteractionCallbackPath(path),false);assert.equal(isInteractionCallbackPath('interactions/18446744073709551615/a.b-c_d/callback'),true);});
test('interaction permit bypasses exhausted global window without consuming a slot',async()=>{const clock=new Clock(),rate=new DiscordChannelRateState(1,clock),ordinary=await rate.acquire('channels/1/typing',signal());ordinary.complete(null);assert.equal(rate.globalRemaining,0);const permit=await rate.acquire(callback(),signal());assert.equal(rate.globalRemaining,0);permit.complete(null);assert.equal(rate.globalRemaining,0);await rate.close();assert.equal(clock.timers.size,0);});
test('fresh exempt request can start in idle queue despite older global-blocked normal request',async()=>{const clock=new Clock(),rate=new DiscordChannelRateState(1,clock),ordinary=await rate.acquire('channels/1/typing',signal());ordinary.complete(null);let normalGranted=false;const pending=rate.acquire('gateway/bot',signal()).then(p=>{normalGranted=true;return p;});const exempt=await rate.acquire(callback(),signal());assert.equal(normalGranted,false);exempt.complete(null);await flush();assert.equal(normalGranted,false);clock.advance(1000);const normal=await pending;normal.complete(null);await rate.close();});
test('callback remains subject to learned bucket reset despite global exemption',async()=>{const clock=new Clock(),rate=new DiscordChannelRateState(1,clock),first=await rate.acquire(callback(),signal());first.complete({bucket:Buffer.from('callback'),limit:1,remaining:0,resetAtMs:500});let granted=false;const pending=rate.acquire(callback(),signal()).then(p=>{granted=true;return p;});clock.advance(499);await flush();assert.equal(granted,false);clock.advance(1);const next=await pending;assert.equal(rate.globalRemaining,1);next.complete(null);await rate.close();});
test('source cancelled normal tombstone ahead of queued exempt request preserves FIFO eligibility',async()=>{const clock=new Clock(),rate=new DiscordChannelRateState(1,clock),ordinary=await rate.acquire('channels/1/typing',signal());ordinary.complete(null);const first=await rate.acquire(callback(1),signal()),cancel=new AbortController(),reason=new Error('cancel normal'),normal=rate.acquire('gateway/bot',cancel.signal),rejected=assert.rejects(normal,e=>e===reason);let granted=false;const exempt=rate.acquire(callback(2),signal()).then(p=>{granted=true;return p;});cancel.abort(reason);await rejected;assert.equal(rate.pendingCount,1);first.complete(null);await flush();assert.equal(granted,false);clock.advance(1000);const next=await exempt;assert.equal(rate.globalRemaining,1);next.complete(null);await rate.close();});
test('source cancellation refund applies even to exempt active permit when global window was spent',async()=>{const clock=new Clock(),rate=new DiscordChannelRateState(2,clock),ordinary=await rate.acquire('channels/1/typing',signal());ordinary.complete(null);assert.equal(rate.globalRemaining,1);const exempt=await rate.acquire(callback(),signal());assert.equal(rate.globalRemaining,1);exempt.release();assert.equal(rate.globalRemaining,2);exempt.release();assert.equal(rate.globalRemaining,2);await rate.close();});
