import assert from 'node:assert/strict';import {it} from 'node:test';import {writeFile,mkdir,unlink,readFile} from 'node:fs/promises';import {dirname,join} from 'node:path';
import {storeFixture} from '../../helpers/store-fixture.ts';
import {DrainFenceKey} from '../../../src/admission/owned-key.ts';
import {DrainGateError} from '../../../src/admission/drain-gate.ts';
import {PosixDrainMarkerStore as Store,DRAIN_MARKER_NAMES as names,encodeRuntimeAckMarker as encodeAck,encodeRuntimeIdentityMarker,type DrainMarkerStore} from '../../../src/runtime/restart-readiness/drain-marker.ts';
import {RuntimeDrainController as Controller,posixDrainMarkerPort as portOf,DrainProtocolError} from '../../../src/runtime/restart-readiness/drain-controller.ts';
const identity={runtimeId:'runtime-a',processId:123},key=DrainFenceKey.create('runtime-a','123|456','nonce-a');
const deferred=<T>()=>{let resolve!:(value:T)=>void;const promise=new Promise<T>(r=>resolve=r);return {promise,resolve};};
async function ready(root:string,port?:DrainMarkerStore){const store=new Store(root),controller=await Controller.initialize(port??portOf(store),identity);await writeFile(join(root,names.prepare),encodeAck(key));assert.equal(key.equals(await controller.claimPrepare()),true);return {store,controller};}
it('orphan prepare or ack blocks initialization without replacing identity',()=>storeFixture(async file=>{
 const root=dirname(file),store=new Store(root);await writeFile(join(root,names.prepare),'old');await assert.rejects(Controller.initialize(portOf(store),identity),e=>e instanceof DrainProtocolError&&e.kind==='OrphanedState');assert.equal(await store.readIdentity(),null);await unlink(join(root,names.prepare));await mkdir(join(root,names.ack));await assert.rejects(Controller.initialize(portOf(store),identity),/orphaned/);assert.equal(await store.readIdentity(),null);
}));
it('prepare runtime and exact PID prefix must match; ACK waits for all in-flight admissions',()=>storeFixture(async file=>{
 const root=dirname(file),store=new Store(root),c=await Controller.initialize(portOf(store),identity);try{for(const wrong of [DrainFenceKey.create('other','123|456','n'),DrainFenceKey.create('runtime-a','1234|456','n')]){await writeFile(join(root,names.prepare),encodeAck(wrong));await assert.rejects(c.claimPrepare(),/different runtime/);assert.equal(c.admissionGate.isSealed(),false);}const permit=c.admissionGate.tryEnter();await writeFile(join(root,names.prepare),encodeAck(key));await c.claimPrepare();await assert.rejects(c.acknowledge(key),/prepare changed/);assert.equal(await store.readAck(),null);permit.release();c.admissionGate.closeControls(key);await c.acknowledge(key);assert.equal(key.equals(await store.readAck()),true);}finally{await c.dispose();}
}));
it('async prepare read cannot turn a newly active control admission into a drained ACK',()=>storeFixture(async file=>{
 const root=dirname(file),store=new Store(root),base=portOf(store);let c!:Controller,count=0,permit:ReturnType<Controller['admissionGate']['tryEnterControl']>|null=null;const port={...base,async readPrepare(){const value=await base.readPrepare();if(++count===2)permit=c.admissionGate.tryEnterControl();return value;}};c=await Controller.initialize(port,identity);try{await writeFile(join(root,names.prepare),encodeAck(key));await c.claimPrepare();await assert.rejects(c.acknowledge(key),/prepare changed/);assert.equal(await store.readAck(),null);}finally{(permit as {release():void}|null)?.release();await c.dispose();}
}));
it('prepare replacement after publication removes only its exact ACK and retains a foreign ACK',()=>storeFixture(async file=>{
 const root=dirname(file),store=new Store(root),base=portOf(store),foreign=DrainFenceKey.create('runtime-a','123|456','foreign');let foreignAck=false;const port={...base,async publishAck(k:DrainFenceKey){await base.publishAck(k);await writeFile(join(root,names.prepare),encodeAck(foreign));if(foreignAck)await base.publishAck(foreign);}};const {controller:c}=await ready(root,port);try{await assert.rejects(c.acknowledge(key),/prepare changed/);assert.equal(await store.readAck(),null);await writeFile(join(root,names.prepare),encodeAck(key));foreignAck=true;await assert.rejects(c.acknowledge(key),/prepare changed/);assert.equal(foreign.equals(await store.readAck()),true);}finally{await c.dispose();}
}));
it('untrusted prepare quarantine stays sealed and cannot be replaced by a different fence',()=>storeFixture(async file=>{
 const root=dirname(file),store=new Store(root),c=await Controller.initialize(portOf(store),identity);try{c.quarantineUntrustedPrepare();assert.equal(c.admissionGate.isSealed(),true);await writeFile(join(root,names.prepare),encodeAck(key));await assert.rejects(c.claimPrepare(),DrainGateError);assert.throws(()=>c.admissionGate.tryEnter(),DrainGateError);}finally{await c.dispose();}
}));
it('malformed restart is retried while sealed and only an exact restart transitions', {timeout:5000},()=>storeFixture(async file=>{
 const root=dirname(file),{controller:c}=await ready(root),stop=new AbortController(),reported=deferred<void>();c.admissionGate.closeControls(key);await c.acknowledge(key);await writeFile(join(root,names.restart),'malformed');const waiter=c.waitForTransition(key,false,stop.signal,()=>reported.resolve());try{await reported.promise;assert.equal(c.admissionGate.isDrainedFor(key),true);await writeFile(join(root,names.restart),encodeAck(key));assert.equal(await waiter,'Restart');assert.equal(c.admissionGate.isSealed(),true);}finally{stop.abort();await waiter.catch(()=>undefined);await c.dispose();}
}));
it('ACK failure cannot be bypassed by a restart marker; explicit stop remains responsive', {timeout:5000},()=>storeFixture(async file=>{
 const root=dirname(file),store=new Store(root),base=portOf(store);let restartReads=0;const {controller:c}=await ready(root,{...base,async readRestart(){restartReads++;return base.readRestart();}});c.admissionGate.closeControls(key);await mkdir(join(root,names.ack));await writeFile(join(root,names.restart),encodeAck(key));const stop=new AbortController(),reported=deferred<void>(),waiter=c.waitForTransition(key,true,stop.signal,()=>reported.resolve());try{await reported.promise;assert.equal(restartReads,0);await writeFile(join(root,names.stop),'stop');assert.equal(await waiter,'Stop');assert.equal(c.admissionGate.isDrainedFor(key),true);}finally{stop.abort();await waiter.catch(()=>undefined);await c.dispose();}
}));
it('stale nonce remains pending and a successful later exact ACK permits restart', {timeout:5000},()=>storeFixture(async file=>{
 const root=dirname(file),store=new Store(root),base=portOf(store),read=deferred<void>();const {controller:c}=await ready(root,{...base,async readRestart(){const value=await base.readRestart();read.resolve();return value;}});c.admissionGate.closeControls(key);await writeFile(join(root,names.restart),encodeAck(DrainFenceKey.create('runtime-a','123|456','stale')));const stop=new AbortController();let settled=false;const waiter=c.waitForTransition(key,true,stop.signal).then(v=>{settled=true;return v;});try{await read.promise;assert.equal(settled,false);await writeFile(join(root,names.restart),encodeAck(key));assert.equal(await waiter,'Restart');assert.equal(key.equals(await store.readAck()),true);}finally{stop.abort();await waiter.catch(()=>undefined);await c.dispose();}
}));
it('stop cancellation waits for current owned IO and disallows concurrent disposal or waiting', {timeout:5000},()=>storeFixture(async file=>{
 const root=dirname(file),base=portOf(new Store(root)),entered=deferred<void>(),finish=deferred<boolean>();const {controller:c}=await ready(root,{...base,async stopRequested(){entered.resolve();return finish.promise;}});const stop=new AbortController();let settled=false;const waiter=c.waitForTransition(key,false,stop.signal).then(v=>{settled=true;return v;});try{await entered.promise;await assert.rejects(c.waitForTransition(key,false,stop.signal),/already active/);assert.throws(()=>c.dispose(),/already active/);stop.abort();await Promise.resolve();assert.equal(settled,false);finish.resolve(false);assert.equal(await waiter,'Stop');}finally{stop.abort();finish.resolve(false);await waiter.catch(()=>undefined);await c.dispose();}
}));
it('unclaimed transition is refused and disposal retains a replaced foreign identity',()=>storeFixture(async file=>{
 const root=dirname(file),store=new Store(root),c=await Controller.initialize(portOf(store),identity);await assert.rejects(c.waitForTransition(key,false,new AbortController().signal),/prepare changed/);await store.publishIdentity({runtimeId:'replacement',processId:456});await c.dispose();assert.equal(await readFile(join(root,names.identity),'utf8'),encodeRuntimeIdentityMarker({runtimeId:'replacement',processId:456}));assert.throws(()=>c.claimPrepare(),/disposed/);await c.dispose();
}));
it('port accessors and non-native promises are rejected without executing hooks',async()=>{
 let calls=0;const port=portOf(new Store('/unused'));await assert.rejects(Controller.initialize({...port,get prepareExists(){calls++;return port.prepareExists;}},identity),TypeError);await assert.rejects(Controller.initialize({...port,prepareExists:()=>({then(){calls++;}}) as never},identity),TypeError);assert.equal(calls,0);
});
it('already requested stop returns Stop without re-opening a sealed gate',()=>storeFixture(async file=>{const {controller:c}=await ready(dirname(file));const stop=new AbortController();stop.abort();try{assert.equal(await c.waitForTransition(key,true,stop.signal),'Stop');assert.equal(c.admissionGate.isSealed(),true);}finally{await c.dispose();}}));
