import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';
import {checkLiveDrain,checkRuntimeQuiescence,type LiveDrainPorts,type DrainLifecycle} from '../../../src/runtime/restart-readiness/live-drain.ts';
import {PortableResidentLifecycle} from '../../../src/app-server/portable-resident-lifecycle.ts';
import {storeFixture} from '../../helpers/store-fixture.ts';
const healthy=():DrainLifecycle=>({generation:1n,healthy:true,quarantined:false,restartPending:false,processId:123});
const empty=()=>({targetThreadIds:['a','b'],blockers:[],observations:[]});
function ports(overrides:Partial<LiveDrainPorts>={},events:string[]=[]):LiveDrainPorts{return {snapshot:async()=>{events.push('snapshot');return empty();},lifecycle:async()=>{events.push('lifecycle');return healthy();},unsettled:async()=>{events.push('unsettled');return false;},activeTurn:async t=>{events.push(t);return null;},...overrides};}
test('stable double observation preserves exact durable/lifecycle/unsettled/target order',async()=>{const events:string[]=[];assert.deepEqual(await checkLiveDrain(ports({},events)),{kind:'Ready'});assert.deepEqual(events,['snapshot','lifecycle','unsettled','a','b','snapshot','lifecycle','unsettled','a','b']);});
test('first durable blocker masks all live operations',async()=>{let calls=0;const r=await checkLiveDrain(ports({snapshot:async()=>({...empty(),blockers:['held']}),lifecycle:async()=>{calls++;throw Error('must not read');}}));assert.deepEqual(r,{kind:'Blocked',reason:'held'});assert.equal(calls,0);});
test('unhealthy lifecycle still observes unsettled and targets, then outranks their blockers',async()=>{const events:string[]=[];let reads=0;const r=await checkLiveDrain(ports({snapshot:async()=>{reads++;return empty();},lifecycle:async()=>({...healthy(),healthy:false}),unsettled:async()=>{events.push('unsettled');return true;},activeTurn:async t=>{events.push(t);return 'turn';}}));assert.equal(r.kind,'Blocked');assert.ok(r.kind==='Blocked'&&r.reason.includes('not stably healthy'));assert.deepEqual(events,['unsettled','a','b']);assert.equal(reads,1);});
test('quarantine, pending restart and missing process each block',async()=>{for(const delta of [{quarantined:true},{restartPending:true},{processId:null}]){const r=await checkLiveDrain(ports({lifecycle:async()=>({...healthy(),...delta})}));assert.equal(r.kind,'Blocked');}});
test('unsettled outranks active, and first sorted active target wins',async()=>{for(const unsettled of [true,false]){const r=await checkLiveDrain(ports({unsettled:async()=>unsettled,activeTurn:async()=> 'v'}));assert.ok(r.kind==='Blocked'&&r.reason.includes(unsettled?'unsettled':'thread a'));}});
test('durable change blocks before second live observation even if no new blocker',async()=>{let reads=0,live=0;const r=await checkLiveDrain(ports({snapshot:async()=>({...empty(),observations:++reads===1?[]:['changed']}),lifecycle:async()=>{live++;return healthy();}}));assert.ok(r.kind==='Blocked'&&r.reason.includes('durable'));assert.equal(live,1);});
test('every live lifecycle field, unsettled and active change refuses Ready',async()=>{for(const field of ['generation','healthy','quarantined','restartPending','processId','unsettled','active']){let n=0;const r=await checkLiveDrain(ports({lifecycle:async()=>{n++;return n===1?healthy():{...healthy(),...(field==='generation'?{generation:2n}:field==='healthy'?{healthy:false}:field==='quarantined'?{quarantined:true}:field==='restartPending'?{restartPending:true}:field==='processId'?{processId:124}:{})};},unsettled:async()=>field==='unsettled'&&n===2,activeTurn:async()=>field==='active'&&n===2?'turn':null}));assert.ok(r.kind==='Blocked'&&r.reason.includes('changed'),field);}});
test('snapshot, unsettled and active errors retain exact identity, never Ready',async()=>{for(const field of ['snapshot','unsettled','activeTurn'] as const){const sentinel={field};await assert.rejects(checkLiveDrain(ports({[field]:async()=>{throw sentinel;}})),e=>e===sentinel);}});
test('snapshot ownership prevents mutation during live observation from erasing durable drift',async()=>{const first=empty();let n=0;const r=await checkLiveDrain(ports({snapshot:async()=>++n===1?first:{...empty(),observations:['new']},lifecycle:async()=>{(first.observations as string[]).push('new');return healthy();}}));assert.ok(r.kind==='Blocked'&&r.reason.includes('durable'));});
test('active accessors, thenables, duplicate targets and invalid lifecycle are rejected',async()=>{let hooks=0;const p=ports();Object.defineProperty(p,'snapshot',{get(){hooks++;return async()=>empty();}});await assert.rejects(checkLiveDrain(p),TypeError);assert.equal(hooks,0);await assert.rejects(checkLiveDrain(ports({snapshot:(()=>({then(){hooks++;}})) as never})),TypeError);assert.equal(hooks,0);await assert.rejects(checkLiveDrain(ports({snapshot:async()=>({...empty(),targetThreadIds:['a','a']})})),TypeError);await assert.rejects(checkLiveDrain(ports({lifecycle:async()=>({...healthy(),generation:1 as never})})),TypeError);});
test('cancellation after awaited operation propagates, never observes later targets',async()=>{const a=new AbortController(),reason={stop:true};let active=0;await assert.rejects(checkLiveDrain(ports({unsettled:async()=>{a.abort(reason);return false;},activeTurn:async()=>{active++;return null;}}),a.signal),e=>e===reason);assert.equal(active,0);});
test('actual central DB worker and owned native resident transition from Ready to unsettled Blocked',{timeout:10000},async t=>storeFixture(async path=>{
 const db=new DatabaseSync(path);db.exec('CREATE TABLE mirror_threads(codex_thread_id);CREATE TABLE codex_turn_queue(job_id,target_thread_id,state,turn_id,last_error);');db.close();
 const code=`import readline from 'node:readline';const emit=v=>process.stdout.write(JSON.stringify(v)+'\\n');readline.createInterface({input:process.stdin}).on('line',line=>{const m=JSON.parse(line);if(m.method==='initialize')emit({id:m.id,result:{}});else if(m.method==='ask'){emit({id:'approval',method:'approval',params:{threadId:'t',turnId:'v'}});emit({id:m.id,result:{}});}});`;
 const owner=await PortableResidentLifecycle.start({process:{executable:process.execPath,arguments:['--input-type=module','-e',code],environment:{}},clientInfo:{name:'live-drain',title:'fixture',version:'1'}},()=> 'fixture',{persistDeadWork(){},oldChildExited(){}},t.signal);
 try{assert.equal(owner.hasUnsettledServerRequests(),false);assert.deepEqual(await checkRuntimeQuiescence(path,owner,t.signal),{kind:'Ready'});const admission=owner.admitRequest();try{await admission.client.requestAdmitted(admission.permit,'ask',{},2000,undefined,t.signal);}finally{admission.release();}assert.equal(owner.hasUnsettledServerRequests(),true);const result=await checkRuntimeQuiescence(path,owner,t.signal);assert.ok(result.kind==='Blocked'&&result.reason.includes('unsettled'));}finally{await owner.dispose();}
}));
