import {it} from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {dirname,join} from 'node:path';
import {storeFixture} from '../../helpers/store-fixture.ts';import {openInitialized} from '../../../src/store/owned-driver.ts';import {StateAccessFacade as state} from '../../../src/store/state-access-facade.ts';import {BridgeState} from '../../../src/runtime/bridge-state.ts';import {QueueStartCoordinator} from '../../../src/runtime/queue-runner/start-coordinator.ts';import {RuntimeCommandExecutor} from '../../../src/runtime/action-executor/command-executor.ts';import {PortableResidentLifecycle} from '../../../src/app-server/portable-resident-lifecycle.ts';import {AppServerTurnBackend} from '../../../src/runtime/app-server-turn-backend.ts';import {createMutationCustodyFence} from '../../../src/runtime/mutation-custody-fence.ts';import {INTERVIEW_HEADER} from '../../../src/runtime/action-executor/interview-header.ts';import {actionExecutionErrorInfo} from '../../../src/runtime/action-executor/action-error.ts';import {joinDiagnosticReaders} from '../../../src/runtime/diagnostic-report.ts';
const actor={channelId:42n,userId:3n,discordMessageId:5n,autoQueueWhenBusy:false};
const code=`import readline from 'node:readline';const seen=[];const emit=x=>process.stdout.write(JSON.stringify(x)+'\\n');readline.createInterface({input:process.stdin}).on('line',line=>{const m=JSON.parse(line),reply=result=>emit({id:m.id,result});if(m.method==='initialized')return;if(m.method==='initialize'){reply({});return;}if(m.method==='fixture/seen'){reply(seen);return;}seen.push({method:m.method,params:m.params});if(m.method==='thread/start')reply({thread:{id:'created'}});else if(m.method==='thread/resume')reply({thread:{id:m.params.threadId}});else if(m.method==='thread/read')reply({thread:{id:m.params.threadId,status:{type:'idle'},turns:[]}});else if(m.method==='turn/start')reply({turn:{id:'turn'}});else emit({id:m.id,error:{code:-9,message:'unsupported fixture call'}});});`;
async function fixture(native:boolean,run:(f:{path:string;bridge:BridgeState;queue:QueueStartCoordinator;executor:RuntimeCommandExecutor;starts:string[];notifications:()=>number;seen:()=>Promise<any[]>})=>Promise<void>){await storeFixture(async path=>{
 const codex=join(dirname(path),'codex.sqlite'),bridgePath=join(dirname(path),'bridge.json'),bridge=new BridgeState(bridgePath);bridge.setSelectedThreadId('root');const cd=new DatabaseSync(codex);try{cd.exec("CREATE TABLE threads(id TEXT PRIMARY KEY,title TEXT,cwd TEXT,updated_at INTEGER,rollout_path TEXT,model TEXT,reasoning_effort TEXT,tokens_used INTEGER,archived INTEGER,archived_at INTEGER);INSERT INTO threads(id,title,cwd,updated_at,archived,archived_at) VALUES('root','Root','/tmp',1,0,0)");}finally{cd.close();}
 const db=await openInitialized(path);try{db.exec("INSERT INTO codex_mutation_runtime VALUES(1,'runtime');INSERT INTO codex_app_server_runtime VALUES(1,'runtime')");}finally{db.close();}
 const render=(e:unknown)=>e instanceof Error?e.message:'fixture error';const server=native?await PortableResidentLifecycle.start({process:{executable:process.execPath,arguments:['--input-type=module','-e',code],environment:{}},clientInfo:{name:'command',title:'fixture',version:'1'}},render,{persistDeadWork(){},oldChildExited(){}},undefined,{renderError:render,fence:createMutationCustodyFence(path,'runtime',render)}):null;
 const backend=server===null?null:new AppServerTurnBackend(server,render,{resumeTimeoutMs:1000,historyTimeoutMs:1000}),starts:string[]=[];let notifications=0;
 const queue=new QueueStartCoordinator(path,backend??{generation:()=>1n,residentInstanceId:()=> 'resident',activeTurnId:async()=>null,resumeThread:async()=>{},readTurns:async()=>[],startClaimedTurn:async(claim:{prompt:string})=>{starts.push(claim.prompt);return 'turn';}},{notifyDeliveryReady:()=>{notifications++;}});
 const executor=new RuntimeCommandExecutor({paths:{state:codex,mirror:path,bridge:bridgePath},bridge,server,backend,queue,render,preparePrompt:async p=>p+' enriched',mirror:null,reportNewAttempt:()=>{},resumeTimeoutMs:2000});
 const seen=async()=>{if(server===null)return [];const a=server.admitResponse(server.generation());try{return await a.client.requestAdmitted(a.permit,'fixture/seen',{},1000) as any[];}finally{a.release();}};
 try{await run({path,bridge,queue,executor,starts,notifications:()=>notifications,seen});}finally{await server?.dispose();await joinDiagnosticReaders();}
});}
async function admit(path:string,kind:'Resume'|'Stop'|'Repair'|'Archive',event=5n){await state.admitIngress(path,{ingressId:`message:${event}`,kind:'message',eventId:event,applicationId:null,channelId:42n,ownerUserId:3n,sourceMessageId:event,targetThreadId:'root',canonicalOwner:null,now:1,payload:{version:1n,content:'!'+kind.toLowerCase(),plan:{Execute:{[kind]:{reference:null}}},lifecycle_binding:{target:'root',route:'Selected',command:{[kind]:{reference:null}}},stop_origin:{target:'root',stopRevision:0n}}});const db=await openInitialized(path);try{db.prepare("UPDATE discord_ingress_journal SET state='executing',phase='processing' WHERE ingress_id=?").run(`message:${event}`);}finally{db.close();}}
it('concrete message service functions invoke durable Ask queue and repeated message never dispatches twice',async()=>fixture(false,async f=>{
 const service=f.executor.messageServices();for(const name of ['targetThreadId','executeWithIngressContext','notifyDeliveryReady'])assert.equal(typeof Object.getOwnPropertyDescriptor(service,name)?.value,'function');assert.ok(Object.isFrozen(service));assert.equal(await service.targetThreadId(42n),'root');
 const first=await service.executeWithIngressContext({Ask:{prompt:'raw'}},actor,'message:5');assert.match(first.text,/In progress/);await service.executeWithIngressContext({Ask:{prompt:'raw'}},actor,'message:5');assert.deepEqual(f.starts,['raw enriched']);assert.equal((await state.listQueueJobs(f.path)).length,1);service.notifyDeliveryReady();assert.ok(f.notifications()>0);
}));
it('Interview reaches same durable queue with exact pinned header',async()=>fixture(false,async f=>{
 await f.executor.executeWithIngressContext({Interview:{prompt:'question'}},actor,'message:5');assert.deepEqual(f.starts,[INTERVIEW_HEADER+'question enriched']);
}));
it('New composition executes real native creation and first turn once with preserved origin',async()=>fixture(true,async f=>{
 const action={New:{prompt:'raw'}};await f.executor.executeWithIngressContext(action,actor,'message:5');await f.executor.executeWithIngressContext(action,actor,'message:5');assert.deepEqual((await f.seen()).map(x=>x.method),['thread/start','turn/start']);assert.equal(f.bridge.selectedThreadId(),'created');const saved=await state.ingressByOrigin(f.path,5n);assert.equal(saved?.ownerUserId,3n);assert.equal(saved?.channelId,42n);assert.equal(saved?.state,'owned');
}));
it('admitted Resume dispatch reads exact original target without replaying prompt',async()=>fixture(true,async f=>{
 await admit(f.path,'Resume');const result=await f.executor.executeWithIngressContext({Resume:{reference:null}},actor,'message:5');assert.match(result.text,/already loaded/);assert.deepEqual((await f.seen()).map(x=>[x.method,x.params.threadId]),[['thread/read','root']]);
}));
it('Archive Resume Repair Stop route custody rejection before native effect for wrong actor or command',async()=>fixture(true,async f=>{
 await admit(f.path,'Resume');for(const action of [{Resume:{reference:null}},{Archive:{reference:null}},{Repair:{reference:null}},{Stop:{reference:null}}])await assert.rejects(f.executor.executeWithIngressContext(action,{...actor,userId:4n},'message:5'));assert.deepEqual(await f.seen(),[]);
}));
it('Stop shares queue lock registry and records acceptance without waiting on that busy lock',async()=>fixture(false,async f=>{
 await admit(f.path,'Stop');const lease=await f.queue.locks.acquire('root');try{const result=await f.executor.executeWithIngressContext({Stop:{reference:null}},actor,'message:5');assert.match(result.text,/Stop accepted for root/);assert.match(result.text,/Execution end is not confirmed/);lease.requireTarget('root');}finally{lease.release();}
}));
it('settings mutation cannot bypass missing frozen admission via ordinary settings execution',async()=>fixture(true,async f=>{
 await assert.rejects(f.executor.executeWithIngressContext({Settings:{reference:null,model:'m',effort:null,speed:null}},actor,'missing'),/admission record is missing/);assert.deepEqual(await f.seen(),[]);
}));
it('discard remains message processor-only and unimplemented recover/host paths never succeed silently',async()=>fixture(true,async f=>{
 await assert.rejects(f.executor.executeWithIngressContext({DiscardRequest:{job_id:'j'}},actor,'message:5'),/authenticated message custody/);for(const action of [{Recover:{reference:null}},'HostReboot','ForceRestartCodex'] as const)await assert.rejects(f.executor.executeWithIngressContext(action,actor,'message:5'),e=>actionExecutionErrorInfo(e)?.kind==='Unsupported');assert.deepEqual(await f.seen(),[]);
}));
it('preabort prevents queue and native effects, preserving exact reason',async()=>fixture(true,async f=>{
 const c=new AbortController(),reason=new Error('cancel');c.abort(reason);await assert.rejects(f.executor.executeWithIngressContext({New:{prompt:'raw'}},actor,'message:5',c.signal),e=>e===reason);assert.deepEqual(await f.seen(),[]);assert.deepEqual(await state.listQueueJobs(f.path),[]);
}));
it('admitted adapter refuses absent event identity instead of creating a new unrelated action admission',async()=>fixture(true,async f=>{
 await assert.rejects(f.executor.executeWithIngressContext({New:{prompt:'raw'}},{...actor,discordMessageId:null} as never,'message:5'),/event identity is required/);assert.deepEqual(await f.seen(),[]);assert.deepEqual(await state.listQueueJobs(f.path),[]);
}));
