import {it} from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {dirname,join} from 'node:path';
import {RuntimeCommandExecutor} from '../../../src/runtime/action-executor/command-executor.ts';import {BridgeState} from '../../../src/runtime/bridge-state.ts';import {QueueStartCoordinator} from '../../../src/runtime/queue-runner/start-coordinator.ts';import {AppServerTurnBackend} from '../../../src/runtime/app-server-turn-backend.ts';import {createInteractionProcessor} from '../../../src/runtime/interaction-worker/processor.ts';import {runInteractionWorker} from '../../../src/runtime/interaction-worker/worker.ts';import {createInteractionWorkQueue} from '../../../src/runtime/discord-dispatch/interaction-work.ts';import {AdmissionGate} from '../../../src/admission/drain-gate.ts';import {requestFingerprint,threadFingerprint} from '../../../src/discord/components.ts';import {StateAccessFacade as state} from '../../../src/store/state-access-facade.ts';import {componentWorkerErrorInfo} from '../../../src/runtime/component-worker/errors.ts';import {createBusyChoice,getBusyChoice} from '../../../src/store/busy-choice-store.ts';import {promptFixture,callPromptFixture} from '../../helpers/server-prompt-fixture.ts';import {work,stage,enqueue,httpFixture,fence} from '../../helpers/interaction-worker-fixture.ts';
async function fixture(run:(f:any)=>Promise<void>){await promptFixture(async(database,server,request)=>httpFixture(async(http,seen)=>{
 const codex=join(dirname(database),'codex.sqlite'),bridgePath=join(dirname(database),'bridge.json'),db=new DatabaseSync(codex);try{db.exec("CREATE TABLE threads(id TEXT PRIMARY KEY,title TEXT,cwd TEXT,updated_at INTEGER,rollout_path TEXT,model TEXT,reasoning_effort TEXT,tokens_used INTEGER,archived INTEGER,archived_at INTEGER);INSERT INTO threads(id,title,cwd,updated_at,archived,archived_at) VALUES('t','Target','/tmp',1,0,0)");}finally{db.close();}
 const bridge=new BridgeState(bridgePath);bridge.setSelectedThreadId('t');const backend=new AppServerTurnBackend(server,()=> 'fixture',{resumeTimeoutMs:1000,historyTimeoutMs:1000});let notifications=0;const queue=new QueueStartCoordinator(database,backend,{notifyDeliveryReady:()=>{notifications++;}}),executor=new RuntimeCommandExecutor({paths:{state:codex,mirror:database,bridge:bridgePath},bridge,server,backend,queue,render:()=> 'fixture',preparePrompt:async p=>p+' prepared',mirror:null,reportNewAttempt:()=>{},resumeTimeoutMs:1000});
 const custom=`codex_approval:v2:${threadFingerprint('t')}:${requestFingerprint(1n,request.occurrence.asBytes(),request.id)}:1`;await run({database,server,http,seen,queue,executor,custom,notifications:()=>notifications});
}),{enableResponses:true});}
it('one concrete executor supplies bound approval handler through real worker, native response and durable confirmation',async()=>fixture(async f=>{
 const gate=new AdmissionGate(),seal=fence(),w=work(f.database,3n,gate,f.custom),q=createInteractionWorkQueue();await stage(w);enqueue(q,w);q.sender.dispose();gate.seal(seal);const services=f.executor.interactionServices(f.http);assert.ok(Object.isFrozen(services));for(const name of ['executeWithIngressContext','prepareComponent'])assert.equal(typeof Object.getOwnPropertyDescriptor(services,name)?.value,'function');
 const process=createInteractionProcessor(f.database,f.server,f.http,services),reports:string[]=[];await runInteractionWorker(q,f.database,f.http,{process,notifyDeliveryReady:f.executor.messageServices().notifyDeliveryReady,report(_code,detail){reports.push(detail);}});
 assert.deepEqual(reports,[]);assert.deepEqual(await callPromptFixture(f.server,'answers'),[{id:'approval',result:{decision:'accept'}}]);assert.deepEqual(f.seen,['POST','PATCH']);assert.equal((await state.getIngress(f.database,w.custodyIngressId))!.confirmationDelivered,true);assert.equal(gate.isDrainedFor(seal),true);assert.ok(f.notifications()>0);
}));
it('concrete prepared confirmation retry cannot replay the already submitted native approval',async()=>fixture(async f=>{
 const w=work(f.database,3n,new AdmissionGate(),f.custom);await stage(w);try{assert.ok('Component'in w.work);const services=f.executor.interactionServices(f.http),confirmation=await services.prepareComponent(w,w.work.Component);assert.deepEqual(f.seen,[]);await confirmation.deliver();await confirmation.deliver();assert.deepEqual(f.seen,['POST','PATCH','PATCH']);assert.equal((await callPromptFixture(f.server,'answers') as unknown[]).length,1);}finally{w.admissionPermit!.release();}
}));
it('concrete component actor mismatch is refused before native response or HTTP confirmation',async()=>fixture(async f=>{
 const w=work(f.database,3n,new AdmissionGate(),f.custom);try{assert.ok('Component'in w.work);await assert.rejects(f.executor.interactionServices(f.http).prepareComponent({...w,userId:7n},w.work.Component),e=>componentWorkerErrorInfo(e)?.kind==='Authority');assert.deepEqual(await callPromptFixture(f.server,'answers'),[]);assert.deepEqual(f.seen,[]);}finally{w.admissionPermit!.release();}
}));
it('slash business adapter uses same selected and mapped target without another executor',async()=>fixture(async f=>{
 const result=await f.executor.interactionServices(f.http).executeWithIngressContext('Identity',{channelId:1n,userId:2n,discordMessageId:3n,autoQueueWhenBusy:false},'interaction:3');assert.equal(result.text,'Discord identity\nuser_id: 2\nchannel_id: 1\nthread_id: t');assert.equal(result.waitsForFinal,false);assert.deepEqual(f.seen,[]);assert.deepEqual(await callPromptFixture(f.server,'answers'),[]);
}));
it('Busy Queue composition uses real prompt intake once and leaves running target undisturbed',async()=>fixture(async f=>{
 const now=Date.now()/1000,id=await createBusyChoice(f.database,{ownerUserId:2n,channelId:1n,targetThreadId:'t',prompt:'later',allowSteer:false,now,timeToLive:1800}),choice=(await getBusyChoice(f.database,id,now))!,base=work(f.database,8n,new AdmissionGate(),`codex_busy:${id}:queue`),w=Object.freeze({...base,authorizedBusyChoice:choice});try{assert.ok('Component'in w.work);const services=f.executor.interactionServices(f.http);await services.prepareComponent(w,w.work.Component);const first=await state.listQueueJobs(f.database);assert.equal(first.length,2);assert.equal(first.filter(j=>j.prompt==='later prepared').length,1);await services.prepareComponent({...w,processingMode:'ConfirmationOnly'},w.work.Component);assert.equal((await state.listQueueJobs(f.database)).length,2);assert.deepEqual(await callPromptFixture(f.server,'controls'),[]);assert.deepEqual(f.seen,[]);}finally{w.admissionPermit!.release();}
}));
