import {it} from 'node:test';import assert from 'node:assert/strict';import {createServer} from 'node:http';import {DatabaseSync} from 'node:sqlite';import {dirname,join} from 'node:path';import {writeFileSync,readFileSync} from 'node:fs';
import {storeFixture} from '../../helpers/store-fixture.ts';import {BridgeState} from '../../../src/runtime/bridge-state.ts';import {QueueStartCoordinator} from '../../../src/runtime/queue-runner/start-coordinator.ts';import {RuntimeCommandExecutor} from '../../../src/runtime/action-executor/command-executor.ts';import {DiscordChannelClient} from '../../../src/discord/channel-client.ts';import {DiscordNewMirrorTransport} from '../../../src/runtime/mirror-sync/new-mirror-http.ts';import {MirrorInspector,joinMirrorInspectionReader} from '../../../src/runtime/mirror-sync/inspection.ts';import {TargetLocks} from '../../../src/core/keyed-locks.ts';import {actionExecutionErrorInfo} from '../../../src/runtime/action-executor/action-error.ts';
const actor={channelId:42n,userId:3n,discordMessageId:5n,autoQueueWhenBusy:false};
async function fixture(run:(f:{executor:RuntimeCommandExecutor;inspector:MirrorInspector;remote:DiscordNewMirrorTransport;calls:{method:string;url:string}[];mirror:string;codex:string;setFailure:()=>void})=>Promise<void>){await storeFixture(async mirror=>{
 const codex=join(dirname(mirror),'codex.sqlite'),bridgePath=join(dirname(mirror),'bridge.json'),rollout=join(dirname(mirror),'rollout.jsonl');writeFileSync(rollout,'{}');let db=new DatabaseSync(mirror);try{db.exec("CREATE TABLE mirror_threads(codex_thread_id,thread_title,discord_channel_id,discord_thread_id,project_key);CREATE TABLE mirror_projects(project_key,discord_channel_id);INSERT INTO mirror_threads VALUES('root','Root',10,20,'/p');INSERT INTO mirror_projects VALUES('/p',10)");}finally{db.close();}
 db=new DatabaseSync(codex);try{db.exec("CREATE TABLE threads(id TEXT,title TEXT,cwd TEXT,updated_at INTEGER,rollout_path TEXT,model TEXT,reasoning_effort TEXT,tokens_used INTEGER,archived INTEGER,archived_at INTEGER,source TEXT,thread_source TEXT)");db.prepare("INSERT INTO threads VALUES('root','Root','/p',1,?,NULL,NULL,0,0,0,'vscode','user')").run(rollout);}finally{db.close();}
 const calls:{method:string;url:string}[]=[];let failure=false;const local=createServer((req,res)=>{req.resume();req.on('end',()=>{calls.push({method:req.method!,url:req.url!});if(failure&&req.url!.endsWith('/20')){res.statusCode=403;res.end(JSON.stringify({code:50001,message:'Missing Access'}));return;}const parent=req.url!.endsWith('/10');res.end(JSON.stringify({id:parent?'10':'20',guild_id:'9',parent_id:parent?'99':'10',type:parent?0:11,name:parent?'project':'root',...(parent?{}:{thread_metadata:{archived:false,auto_archive_duration:10080,archive_timestamp:'2020-01-01T00:00:00+00:00',locked:false}})}));});});await new Promise<void>(r=>local.listen(0,'127.0.0.1',r));
 const http=await DiscordChannelClient.create({token:null,testOrigin:`http://127.0.0.1:${(local.address() as {port:number}).port}/api/v10/`,report:()=>{}}),remote=new DiscordNewMirrorTransport(http),bridge=new BridgeState(bridgePath),queue=new QueueStartCoordinator(mirror,{generation:()=>1n,residentInstanceId:()=> 'fixture',activeTurnId:async()=>null,resumeThread:async()=>{},readTurns:async()=>[],startClaimedTurn:async()=>{assert.fail('read-only command cannot start a turn');}}),executor=new RuntimeCommandExecutor({paths:{state:codex,mirror,bridge:bridgePath},bridge,server:null,backend:null,queue,render:()=> 'fixture',preparePrompt:async p=>p,mirror:null,reportNewAttempt:()=>{},resumeTimeoutMs:1000}),inspector=new MirrorInspector(codex,mirror,remote,new TargetLocks(),9n);
 try{await run({executor,inspector,remote,calls,mirror,codex,setFailure:()=>{failure=true;}});}finally{await joinMirrorInspectionReader();await http.close();local.closeAllConnections();await new Promise<void>((r,j)=>local.close(e=>e?j(e):r()));assert.equal(http.activeRequests,0);assert.equal(http.ownedSockets,0);}
});}
it('unconfigured inspection remains explicit unsupported with zero HTTP calls',async()=>fixture(async f=>{
 await assert.rejects(f.executor.executeWithIngressContext('MirrorCheck',actor,'message:5'),e=>actionExecutionErrorInfo(e)?.kind==='Unsupported');assert.deepEqual(f.calls,[]);
}));
it('concrete MirrorCheck and MirrorInspect dispatch only real HTTP GET and preserve database bytes',async()=>fixture(async f=>{
 f.executor.configureMirrorInspection(f.inspector);const before=readFileSync(f.mirror),check=await f.executor.executeWithIngressContext('MirrorCheck',actor,'message:5');assert.match(check.text,/status: ok/);assert.equal(check.waitsForFinal,false);assert.equal(check.ui,null);
 const list=await f.executor.executeWithIngressContext({MirrorInspect:{limit:0n,list:true}},actor,'message:6');assert.match(list.text,/details: 0\/1/);assert.deepEqual(f.calls.map(x=>[x.method,x.url]),[['GET','/api/v10/channels/10'],['GET','/api/v10/channels/20'],['GET','/api/v10/channels/10'],['GET','/api/v10/channels/20']]);assert.deepEqual(readFileSync(f.mirror),before);
}));
it('HTTP access error is an observed issue despite display limit zero, never a healthy check',async()=>fixture(async f=>{
 f.executor.configureMirrorInspection(f.inspector);f.setFailure();const result=await f.executor.executeWithIngressContext({MirrorInspect:{limit:0n,list:false}},actor,'message:5');assert.match(result.text,/status: issues_found/);assert.match(result.text,/remote_errors: 1/);assert.match(result.text,/details: 0\/1/);assert.equal(f.calls.length,2);
}));
it('configuration cannot replace a previous inspector or cross database scope',async()=>fixture(async f=>{
 const other=new MirrorInspector(f.codex,f.mirror+'.other',f.remote,new TargetLocks(),9n);assert.throws(()=>f.executor.configureMirrorInspection(other),/scope differs/);f.executor.configureMirrorInspection(f.inspector);assert.throws(()=>f.executor.configureMirrorInspection(f.inspector),/already configured/);assert.deepEqual(f.calls,[]);
}));
