import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {dirname,join} from 'node:path';
import {storeFixture} from '../../helpers/store-fixture.ts';import {queueJob} from '../../helpers/queue-job.ts';import {openInitialized} from '../../../src/store/owned-driver.ts';import {StateAccessFacade as state} from '../../../src/store/state-access-facade.ts';import {BridgeState} from '../../../src/runtime/bridge-state.ts';import {ActionThreadSelection} from '../../../src/runtime/action-executor/thread-selection.ts';import {RetractAction} from '../../../src/runtime/action-executor/retract-action.ts';
async function fixture(run:(f:{path:string;action:RetractAction;bridge:BridgeState;selection:ActionThreadSelection})=>Promise<void>){await storeFixture(async path=>{const db=await openInitialized(path);db.close();const file=join(dirname(path),'codex.sqlite'),codex=new DatabaseSync(file);try{codex.exec("CREATE TABLE threads(id TEXT PRIMARY KEY,title TEXT,cwd TEXT,updated_at INTEGER,rollout_path TEXT,model TEXT,reasoning_effort TEXT,tokens_used INTEGER,archived INTEGER,archived_at INTEGER);INSERT INTO threads(id,title,cwd,updated_at,archived) VALUES('target','Original','/p',1,0)");}finally{codex.close();}const bridge=new BridgeState(join(dirname(path),'bridge.json'));bridge.setSelectedThreadId('target');const selection=new ActionThreadSelection(file,path,bridge),action=new RetractAction(path,selection,()=>123);await run({path,action,bridge,selection});});}
const queue=(path:string,id:string,time:number,owner=2n)=>state.enqueue(path,queueJob({jobId:id,ownerUserId:owner,createdAt:time}));
test('retract cancels only latest eligible original-actor request and persists a replay fence',async()=>fixture(async f=>{await queue(f.path,'older',1);await queue(f.path,'newer',2);await queue(f.path,'foreign',3,8n);assert.equal(await f.action.retract(1n,2n,null),'Retracted unstarted request newer for target.');await assert.rejects(queue(f.path,'newer',4),/cancelled/);assert.equal(await f.action.retract(1n,2n,'target'),'Retracted unstarted request older for target.');assert.equal(await f.action.retract(1n,2n,null),'No unstarted request found for target.');assert.equal((await state.listQueueJobs(f.path)).length,1);}));
test('started request is not interrupted or removed by retract',async()=>fixture(async f=>{await queue(f.path,'running',1);const db=await openInitialized(f.path);try{db.exec("UPDATE codex_turn_queue SET state='running',turn_id='turn'");}finally{db.close();}await assert.rejects(f.action.retract(1n,2n,null),/started or its outcome is unknown/);assert.equal((await state.listQueueJobs(f.path))[0]?.state,'Running');}));
test('explicit reference can target original thread without global selected fallback',async()=>fixture(async f=>{await queue(f.path,'original',1);f.bridge.setSelectedThreadId('other');assert.equal(await f.action.retract(1n,2n,'target'),'Retracted unstarted request original for target.');await assert.rejects(f.action.retract(1n,2n,'missing'));}));
test('preabort and invalid actor do not remove pending work',async()=>fixture(async f=>{await queue(f.path,'job',1);const a=new AbortController(),reason=new Error('pre');a.abort(reason);await assert.rejects(f.action.retract(1n,2n,null,a.signal),e=>e===reason);await assert.rejects(f.action.retract(1n,1n<<63n,null));assert.equal((await state.listQueueJobs(f.path)).length,1);}));
test('invalid clock fails before cancellation receipt or deletion',async()=>fixture(async f=>{await queue(f.path,'job',1);await assert.rejects(new RetractAction(f.path,f.selection,()=>NaN).retract(1n,2n,null));assert.equal((await state.listQueueJobs(f.path)).length,1);}));
