import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {dirname,join} from 'node:path';
import {storeFixture} from '../../helpers/store-fixture.ts';import {openInitialized} from '../../../src/store/owned-driver.ts';
import {PortableResidentLifecycle} from '../../../src/app-server/portable-resident-lifecycle.ts';import {createMutationCustodyFence} from '../../../src/runtime/mutation-custody-fence.ts';
import {SettingsAction,type SettingsChange} from '../../../src/runtime/action-executor/settings-action.ts';import {SettingsTargetResolver} from '../../../src/runtime/settings-binding.ts';import {ActionThreadSelection} from '../../../src/runtime/action-executor/thread-selection.ts';import {ControlTurnVerifier} from '../../../src/runtime/action-executor/control-turn.ts';import {TargetLocks} from '../../../src/core/keyed-locks.ts';import {BridgeState} from '../../../src/runtime/bridge-state.ts';
const change=(model:string|null='new',effort:string|null=null,speed:string|null=null):SettingsChange=>({reference:null,model,effort,speed});
async function fixture(mode:string,run:(f:{action:SettingsAction;bridge:BridgeState;resolver:SettingsTargetResolver;locks:TargetLocks;call(method:string):Promise<any>})=>Promise<void>,budget=1000){await storeFixture(async path=>{
 const db=await openInitialized(path);try{db.exec("INSERT INTO codex_mutation_runtime VALUES(1,'runtime');INSERT INTO codex_app_server_runtime VALUES(1,'runtime')");}finally{db.close();}
 const state=join(dirname(path),'codex.sqlite'),codex=new DatabaseSync(state);try{codex.exec("CREATE TABLE threads(id TEXT PRIMARY KEY,title TEXT,cwd TEXT,updated_at INTEGER,rollout_path TEXT,model TEXT,reasoning_effort TEXT,tokens_used INTEGER,archived INTEGER,archived_at INTEGER);INSERT INTO threads(id,title,cwd,updated_at,model,reasoning_effort,archived) VALUES('t','Original','/p',1,'saved','low',0),('other','Other','/p',2,'other','high',0)");}finally{codex.close();}
 const code=`import readline from 'node:readline';const mode=${JSON.stringify(mode)},seen=[];let pending=null,current={model:'old',reasoningEffort:'medium',serviceTier:null};const emit=x=>process.stdout.write(JSON.stringify(x)+'\\n'),observe=()=>emit({method:'thread/settings/updated',params:{threadId:'t',threadSettings:{model:current.model,effort:current.reasoningEffort,serviceTier:current.serviceTier}}});const models={data:['old','new','gpt-luna'].map(model=>({model,defaultReasoningEffort:'medium',supportedReasoningEfforts:[{reasoningEffort:'medium'},{reasoningEffort:'xhigh'}]}))};readline.createInterface({input:process.stdin}).on('line',l=>{const m=JSON.parse(l),reply=result=>emit({id:m.id,result});if(m.method==='initialize')reply({});else if(m.method==='initialized'){}else if(m.method==='seen')reply(seen);else if(m.method==='seed'){observe();reply({});}else if(m.method==='release'){if(pending){pending();pending=null;}reply({});}else{seen.push({method:m.method,params:m.params});if(m.method==='model/list'){if(mode==='catalog-pause')pending=()=>reply(models);else reply(models);}else if(m.method==='account/rateLimits/read')reply({rateLimitsByLimitId:{a:{limitName:'gpt-reserve',normalModelSlug:'gpt-luna',primary:{usedPercent:1}}}});else if(m.method==='thread/resume'){if(mode==='owner-error')emit({id:m.id,error:{code:-32600,message:'already has an active writer'}});else reply({thread:{id:mode==='wrong'?'other':'t'},...current});}else if(m.method==='thread/settings/update'){const apply=()=>{if('model' in m.params)current.model=m.params.model;if('effort' in m.params)current.reasoningEffort=m.params.effort;if('serviceTier' in m.params)current.serviceTier=m.params.serviceTier;if(mode==='mismatch')current.model='wrong';observe();reply({});};if(mode==='hang')return;else if(mode==='update-pause')pending=apply;else apply();}else emit({id:m.id,error:{code:-9,message:'unexpected'}});}});`;
 const render=(e:unknown)=>e instanceof Error?e.message:'opaque',server=await PortableResidentLifecycle.start({process:{executable:process.execPath,arguments:['--input-type=module','-e',code],environment:{}},clientInfo:{name:'settings-action',title:'fixture',version:'1'}},render,{persistDeadWork(){},oldChildExited(){}},undefined,{renderError:render,fence:createMutationCustodyFence(path,'runtime',render)});
 const bridge=new BridgeState(join(dirname(path),'bridge.json'));bridge.setSelectedThreadId('t');const locks=new TargetLocks(),resolver=new SettingsTargetResolver(state,path,bridge),action=new SettingsAction(new ActionThreadSelection(state,path,bridge),resolver,bridge,server,new ControlTurnVerifier(path,server,bridge,locks),budget);
 const call=async(method:string)=>{const a=server.admitResponse(server.generation());try{return await a.client.requestAdmitted(a.permit,method,{},1000);}finally{a.release();}};
 try{await run({action,bridge,resolver,locks,call});}finally{await server.dispose();}
});}
async function until(f:{call(method:string):Promise<any>},method:string){for(let i=0;i<100;i++){if((await f.call('seen')).some((x:any)=>x.method===method))return;await new Promise(r=>setTimeout(r,5));}assert.fail(`fixture did not receive ${method}`);}
test('query shows uncertainty or last server observation without resuming or changing settings',async()=>fixture('ok',async f=>{const unknown=await f.action.settings(42n,change(null));assert.ok(unknown.text.includes('현재 실행값 미확인'));assert.ok(unknown.text.includes('마지막 저장 모델: saved'));await f.call('seed');const observed=await f.action.settings(42n,change(null));assert.ok(observed.text.includes('마지막 서버 확인값'));assert.ok(observed.text.includes('모델: old'));assert.deepEqual(await f.call('seen'),[]);}));
test('model mutation resumes exact original, verifies fresh observation, then records only requested fields',async()=>fixture('ok',async f=>{const out=await f.action.settings(42n,change());assert.equal(out.text,'모델이 변경되었습니다: new');assert.deepEqual((await f.call('seen')).map((x:any)=>x.method),['model/list','thread/resume','thread/settings/update']);assert.deepEqual(f.bridge.threadSettings('t'),{model:'new',reasoning:null,speed:null});assert.equal(f.locks.activeTargetCount,0);}));
test('already matching fresh resume sends no update but records verified requested selection',async()=>fixture('ok',async f=>{const out=await f.action.settings(42n,change('old'));assert.ok(out.text.includes('이미 적용된 설정 확인'));assert.deepEqual((await f.call('seen')).map((x:any)=>x.method),['model/list','thread/resume']);assert.equal(f.bridge.threadSettings('t').model,'old');}));
test('manual Reserve uses account alias, compatible effort and explicit default tier with no failed-request retry',async()=>fixture('ok',async f=>{const out=await f.action.settings(42n,change('reserve'));assert.ok(out.text.includes('이전 실패 요청은 재실행하지 않음'));const calls=await f.call('seen'),last=calls.at(-1);assert.deepEqual(last.params,{threadId:'t',model:'gpt-reserve',effort:'medium',serviceTier:'default'});assert.deepEqual(f.bridge.threadSettings('t'),{model:'gpt-reserve',reasoning:'medium',speed:'standard'});}));
test('Reserve fast and unsupported effort fail without settings update or local persistence',async()=>{await fixture('ok',async f=>{await assert.rejects(f.action.settings(42n,change('reserve',null,'fast')),/uses standard/);assert.ok(!(await f.call('seen')).some((x:any)=>x.method==='thread/settings/update'));assert.equal(f.bridge.threadSettings('t').model,null);});await fixture('ok',async f=>{await assert.rejects(f.action.settings(42n,change('new','bad')),/not supported/);assert.ok(!(await f.call('seen')).some((x:any)=>x.method==='thread/settings/update'));});});
test('wrong resume target and original active-writer conflict never fork or update',async()=>{for(const mode of ['wrong','owner-error'])await fixture(mode,async f=>{await assert.rejects(f.action.settings(42n,change()),mode==='wrong'?/different or missing/:/owns original thread t/);assert.deepEqual((await f.call('seen')).map((x:any)=>x.method),['model/list','thread/resume']);assert.equal(f.bridge.threadSettings('t').model,null);});});
test('selected route drift while catalog is pending prevents resume and any replacement target',async()=>fixture('catalog-pause',async f=>{const task=f.action.settings(42n,change()),rejected=assert.rejects(task,/target changed/);await until(f,'model/list');f.bridge.setSelectedThreadId('other');await f.call('release');await rejected;assert.deepEqual((await f.call('seen')).map((x:any)=>x.method),['model/list']);}));
test('route drift after actual update blocks local success recording even if server applied it',async()=>fixture('update-pause',async f=>{const task=f.action.settings(42n,change()),rejected=assert.rejects(task,/target changed/);await until(f,'thread/settings/update');f.bridge.setSelectedThreadId('other');await f.call('release');await rejected;assert.equal(f.bridge.threadSettings('t').model,null);assert.equal(f.bridge.threadSettings('other').model,null);}));
test('shared control lease timeout sends nothing and releases only its own waiter',async()=>fixture('ok',async f=>{const held=await f.locks.acquire('t');try{await assert.rejects(f.action.settings(42n,change()),/control wait timed out/);assert.deepEqual(await f.call('seen'),[]);assert.equal(f.locks.activeTargetCount,1);}finally{held.release();}},30));
test('post-dispatch deadline labels outcome unverified and records no settings',async()=>fixture('hang',async f=>{await assert.rejects(f.action.settings(42n,change()),/outcome is unverified/);assert.equal(f.bridge.threadSettings('t').model,null);assert.equal(f.locks.activeTargetCount,0);assert.ok((await f.call('seen')).some((x:any)=>x.method==='thread/settings/update'));},1000));
test('admitted selected binding cannot redirect after selection changes',async()=>fixture('ok',async f=>{const input=change(),binding=await f.resolver.bind({Settings:input},42n);assert.ok(binding);f.bridge.setSelectedThreadId('other');await assert.rejects(f.action.settings(42n,input,binding),/target changed/);assert.deepEqual(await f.call('seen'),[]);}));
test('fresh mismatch and preabort do not persist success',async()=>{await fixture('mismatch',async f=>{await assert.rejects(f.action.settings(42n,change()),/observed values do not match/);assert.equal(f.bridge.threadSettings('t').model,null);});await fixture('ok',async f=>{const a=new AbortController(),reason=new Error('pre');a.abort(reason);await assert.rejects(f.action.settings(42n,change(),null,a.signal),e=>e===reason);assert.deepEqual(await f.call('seen'),[]);});});
