import test from 'node:test';import assert from 'node:assert/strict';
import {storeFixture} from '../../helpers/store-fixture.ts';
import {openInitialized} from '../../../src/store/owned-driver.ts';
import {PortableResidentLifecycle} from '../../../src/app-server/portable-resident-lifecycle.ts';
import {createMutationCustodyFence} from '../../../src/runtime/mutation-custody-fence.ts';
import {applyOrConfirmSettings} from '../../../src/runtime/action-executor/settings-verification.ts';
import {DEFAULT_THREAD_SETTINGS_UPDATE} from '../../../src/app-server/requests.ts';
const current={model:'old',reasoningEffort:null,serviceTier:null},update={...DEFAULT_THREAD_SETTINGS_UPDATE,model:'new'};
async function fixture(mode:string,run:(server:PortableResidentLifecycle,call:(method:string)=>Promise<any>)=>Promise<void>){await storeFixture(async path=>{
 const db=await openInitialized(path);try{db.exec("INSERT INTO codex_mutation_runtime VALUES(1,'runtime');INSERT INTO codex_app_server_runtime VALUES(1,'runtime')");}finally{db.close();}
 const code=`import readline from 'node:readline';const seen=[],mode=${JSON.stringify(mode)};const emit=x=>process.stdout.write(JSON.stringify(x)+'\\n');const settings=value=>emit({method:'thread/settings/updated',params:{threadId:'t',threadSettings:value}});readline.createInterface({input:process.stdin}).on('line',l=>{const m=JSON.parse(l),reply=result=>emit({id:m.id,result});if(m.method==='initialize')reply({});else if(m.method==='initialized'){}else if(m.method==='seen')reply(seen);else if(m.method==='seed'){settings({model:'new',effort:null,serviceTier:null});reply({});}else{seen.push(m.method);if(mode==='fresh')settings({model:'new',effort:null,serviceTier:null});if(mode==='mismatch')settings({model:'other',effort:null,serviceTier:null});if(mode==='malformed')settings({model:'new'});if(mode==='wrong-thread')emit({method:'thread/settings/updated',params:{threadId:'other',threadSettings:{model:'new',effort:null,serviceTier:null}}});reply({});}});`;
 const render=(e:unknown)=>e instanceof Error?e.message:'opaque',server=await PortableResidentLifecycle.start({process:{executable:process.execPath,arguments:['--input-type=module','-e',code],environment:{}},clientInfo:{name:'settings-verify',title:'fixture',version:'1'}},render,{persistDeadWork(){},oldChildExited(){}},undefined,{renderError:render,fence:createMutationCustodyFence(path,'runtime',render)});
 const call=async(method:string)=>{const a=server.admitResponse(server.generation());try{return await a.client.requestAdmitted(a.permit,method,{},1000);}finally{a.release();}};
 try{await run(server,call);}finally{await server.dispose();}
});}
test('fresh matching native observation after writer admission confirms exactly one update',async()=>fixture('fresh',async(server,call)=>{const out=await applyOrConfirmSettings(server,'t',1n,current,update);assert.equal(out.alreadyApplied,false);assert.equal(out.settings.model,'new');assert.deepEqual(await call('seen'),['thread/settings/update']);assert.ok(Object.isFrozen(out));}));
test('complete current resume already matching is confirmed without sending an update',async()=>fixture('ack',async(server,call)=>{const out=await applyOrConfirmSettings(server,'t',1n,{...current,model:'new'},update);assert.equal(out.alreadyApplied,true);assert.deepEqual(await call('seen'),[]);}));
test('pre-dispatch matching cache and ACK are insufficient; three-second failure never retries',async()=>fixture('ack',async(server,call)=>{await call('seed');const start=performance.now();await assert.rejects(applyOrConfirmSettings(server,'t',1n,current,update),/no fresh matching.*unverified/);assert.ok(performance.now()-start>=2900);assert.deepEqual(await call('seen'),['thread/settings/update']);}));
test('fresh mismatched or incomplete observation cannot produce verified success',async()=>{await fixture('mismatch',async server=>{await assert.rejects(applyOrConfirmSettings(server,'t',1n,current,update),/observed values do not match/);});await fixture('malformed',async server=>{await assert.rejects(applyOrConfirmSettings(server,'t',1n,current,update),/setting field missing or malformed/);});});
test('wrong-thread notification does not satisfy observation and caller cancellation joins receive',async()=>fixture('wrong-thread',async(server,call)=>{const a=new AbortController(),reason=new Error('cancel verification'),task=applyOrConfirmSettings(server,'t',1n,current,update,a.signal);for(let i=0;i<100&&(await call('seen')).length===0;i++)await new Promise(r=>setTimeout(r,5));a.abort(reason);await assert.rejects(task,e=>e===reason);assert.equal(server.observedThreadSettings('t',1n),null);assert.deepEqual(await call('seen'),['thread/settings/update']);}));
test('generation mismatch and incomplete current snapshot fail before any update',async()=>fixture('fresh',async(server,call)=>{await assert.rejects(applyOrConfirmSettings(server,'t',2n,current,update),/connection changed/);await assert.rejects(applyOrConfirmSettings(server,'t',1n,{model:'old'},update),/setting field missing/);assert.deepEqual(await call('seen'),[]);}));
