import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {dirname,join} from 'node:path';
import {storeFixture} from '../../helpers/store-fixture.ts';import {openInitialized} from '../../../src/store/owned-driver.ts';
import {PortableResidentLifecycle} from '../../../src/app-server/portable-resident-lifecycle.ts';import {SettingsOptionsAction} from '../../../src/runtime/action-executor/settings-options.ts';import {ActionThreadSelection} from '../../../src/runtime/action-executor/thread-selection.ts';import {BridgeState} from '../../../src/runtime/bridge-state.ts';
async function fixture(mode:string,run:(f:{action:SettingsOptionsAction;bridge:BridgeState;call(method:string):Promise<any>})=>Promise<void>,budget=3000){await storeFixture(async path=>{
 const db=await openInitialized(path);db.close();const state=join(dirname(path),'codex.sqlite'),codex=new DatabaseSync(state);try{codex.exec("CREATE TABLE threads(id TEXT PRIMARY KEY,title TEXT,cwd TEXT,updated_at INTEGER,rollout_path TEXT,model TEXT,reasoning_effort TEXT,tokens_used INTEGER,archived INTEGER,archived_at INTEGER);INSERT INTO threads(id,title,cwd,updated_at,model,reasoning_effort,archived) VALUES('t','Original','/p',1,'old','medium',0),('other','Other','/p',2,'new','xhigh',0)");}finally{codex.close();}
 const code=`import readline from 'node:readline';const seen=[],mode=${JSON.stringify(mode)};let pending=null;const emit=x=>process.stdout.write(JSON.stringify(x)+'\\n'),models={data:[{model:'old',supportedReasoningEfforts:[{reasoningEffort:'medium'}]},{model:'new',defaultReasoningEffort:'xhigh',supportedReasoningEfforts:[{reasoningEffort:'xhigh'}]}]};readline.createInterface({input:process.stdin}).on('line',l=>{const m=JSON.parse(l),reply=result=>emit({id:m.id,result});if(m.method==='initialize')reply({});else if(m.method==='initialized'){}else if(m.method==='seen')reply(seen);else if(m.method==='seed'){emit({method:'thread/settings/updated',params:{threadId:'t',threadSettings:{model:mode==='malformed'?' ':mode==='reserve'?'gpt-reserve':'new'}}});reply({});}else if(m.method==='release'){pending?.();pending=null;reply({});}else{seen.push(m.method);if(m.method==='model/list'){if(mode==='pause')pending=()=>reply(models);else reply(models);}else if(m.method==='account/rateLimits/read'){if(mode==='hang')return;if(mode==='error')emit({id:m.id,error:{code:-8,message:'quota unavailable'}});else reply({rateLimitsByLimitId:{a:{limitName:'gpt-reserve',normalModelSlug:'new',primary:{usedPercent:1}}}});}else emit({id:m.id,error:{code:-9,message:'unexpected mutation'}});}});`;
 const server=await PortableResidentLifecycle.start({process:{executable:process.execPath,arguments:['--input-type=module','-e',code],environment:{}},clientInfo:{name:'settings-options',title:'fixture',version:'1'}},()=> 'safe',{persistDeadWork(){},oldChildExited(){}},undefined,{fence:null,renderError:()=> 'safe'});
 const bridge=new BridgeState(join(dirname(path),'bridge.json'));bridge.setSelectedThreadId('t');const action=new SettingsOptionsAction(new ActionThreadSelection(state,path,bridge),server,budget),call=async(method:string)=>{const a=server.admitResponse(server.generation());try{return await a.client.requestAdmitted(a.permit,method,{},1000);}finally{a.release();}};
 try{await run({action,bridge,call});}finally{await server.dispose();}
});}
test('general model catalog includes explicit observed Reserve alias without targeting or resuming',async()=>fixture('ok',async f=>{f.bridge.setSelectedThreadId(null);const out=await f.action.options(42n,null,'model');assert.ok(out.text.startsWith('old\nnew\ngpt-reserve'));assert.ok(out.text.includes('standard; 일반 Luna와 별도'));assert.deepEqual(await f.call('seen'),['model/list','account/rateLimits/read']);}));
test('optional quota failure does not turn normal catalog into an outage',async()=>fixture('error',async f=>{const out=await f.action.options(42n,null,'model');assert.equal(out.text,'old\nnew');assert.ok(!out.text.includes('gpt-reserve'));}));
test('optional quota timeout joins after two seconds then returns ordinary models',async()=>fixture('hang',async f=>{const start=performance.now(),out=await f.action.options(42n,null,'model');assert.ok(performance.now()-start>=1900);assert.equal(out.text,'old\nnew');assert.deepEqual(await f.call('seen'),['model/list','account/rateLimits/read']);}));
test('effort options use last saved model with uncertainty, then exact observed model without resume',async()=>fixture('ok',async f=>{const saved=await f.action.options(42n,null,'effort');assert.ok(saved.text.includes('마지막 저장 모델 · 현재 실행값 미확인: old\nmedium'));await f.call('seed');const observed=await f.action.options(42n,null,'reasoning');assert.ok(observed.text.includes('마지막 서버 확인 모델: new\nxhigh'));assert.deepEqual(await f.call('seen'),['model/list','model/list']);}));
test('observed Reserve effort requires usable current quota and ordinary metadata',async()=>fixture('reserve',async f=>{await f.call('seed');const out=await f.action.options(42n,null,'effort');assert.ok(out.text.includes('마지막 서버 확인 모델: gpt-reserve\nxhigh'));assert.deepEqual(await f.call('seen'),['model/list','account/rateLimits/read']);}));
test('malformed observed model is not replaced by locally saved model',async()=>fixture('malformed',async f=>{await f.call('seed');await assert.rejects(f.action.options(42n,null,'effort'),/observed model is malformed/);}));
test('selected target change during catalog read invalidates effort response',async()=>fixture('pause',async f=>{const task=f.action.options(42n,null,'effort'),rejected=assert.rejects(task,/option target changed/);for(let i=0;i<100&&(await f.call('seen')).length===0;i++)await new Promise(r=>setTimeout(r,5));f.bridge.setSelectedThreadId('other');await f.call('release');await rejected;}));
test('overall deadline and caller cancellation cannot be swallowed by optional quota fallback',async()=>{await fixture('hang',async f=>{await assert.rejects(f.action.options(42n,null,'model'),/lookup cancelled/);},60);await fixture('ok',async f=>{const a=new AbortController(),reason=new Error('pre');a.abort(reason);await assert.rejects(f.action.options(42n,null,'model',a.signal),e=>e===reason);assert.deepEqual(await f.call('seen'),[]);});});
