import test from 'node:test';import assert from 'node:assert/strict';
import {ObservedSettings} from '../../../src/runtime/action-executor/settings-observation.ts';
import {DEFAULT_THREAD_SETTINGS_UPDATE,type ThreadSettingsUpdate} from '../../../src/app-server/requests.ts';
const value=()=>({model:'gpt-reserve',effort:'xhigh',serviceTier:'default'});
const update:ThreadSettingsUpdate={model:'gpt-reserve',effort:'xhigh',effortClear:false,serviceTier:{kind:'Set',value:'default'}};
test('complete explicit nulls are defaults; absent resume fields are never guessed',()=>{
 for(const input of [{model:'a'},{model:'a',reasoningEffort:null},{model:'a',serviceTier:null},{model:'a',effort:'xhigh',serviceTier:null}])assert.throws(()=>ObservedSettings.fromResume(input),/missing or malformed/);
 const s=ObservedSettings.fromResume({model:'a',reasoningEffort:null,serviceTier:null});assert.equal(s.effort,null);assert.equal(s.tier,null);assert.ok(s.display('t','verified').includes('추론: 모델 기본값\n속도: standard'));assert.ok(Object.isFrozen(s));
});
test('resume uses reasoningEffort even if conflicting notification-shaped effort exists',()=>{const s=ObservedSettings.fromResume({model:'a',reasoningEffort:'medium',effort:'xhigh',serviceTier:'priority'});assert.equal(s.effort,'medium');assert.ok(s.display('t','verified').endsWith('속도: fast'));});
test('explicit standard default tier is exact, not interchangeable with null or priority',()=>{const s=ObservedSettings.parse(value());assert.equal(s.matches(update),true);assert.ok(s.display('thread','verified').includes('속도: standard'));for(const [field,different] of [['model','gpt-luna'],['effort','high'],['serviceTier','priority'],['serviceTier',null]])assert.equal(ObservedSettings.parse({...value(),[field!]:different}).matches(update),false);});
test('unchanged fields do not constrain observations while explicit null clears do',()=>{const s=ObservedSettings.parse(value());assert.equal(s.matches(DEFAULT_THREAD_SETTINGS_UPDATE),true);assert.equal(s.matches({...DEFAULT_THREAD_SETTINGS_UPDATE,effortClear:true}),false);assert.equal(s.matches({...DEFAULT_THREAD_SETTINGS_UPDATE,serviceTier:{kind:'Clear'}}),false);const cleared=ObservedSettings.parse({model:'a',effort:null,serviceTier:null});assert.equal(cleared.matches({...DEFAULT_THREAD_SETTINGS_UPDATE,effort:'ignored',effortClear:true,serviceTier:{kind:'Clear'}}),true);});
test('empty or malformed fields reject, Rust trimming tests without normalizing saved text',()=>{for(const input of [null,[],{model:'\u0085',effort:null,serviceTier:null},{model:'a',effort:' ',serviceTier:null},{model:'a',effort:4n,serviceTier:null}])assert.throws(()=>ObservedSettings.parse(input));const s=ObservedSettings.parse({model:' a ',effort:'\ufeff',serviceTier:'custom'});assert.equal(s.model,' a ');assert.equal(s.effort,'\ufeff');assert.ok(s.display('t','x').endsWith('속도: custom'));});
test('hostile source/update getters cannot execute and later input mutation cannot change snapshot',()=>{let calls=0;assert.throws(()=>ObservedSettings.parse({get model(){calls++;return 'x';},effort:null,serviceTier:null}));assert.equal(calls,0);const input=value(),s=ObservedSettings.parse(input);input.model='changed';assert.equal(s.model,'gpt-reserve');const hostile={...update,get model(){calls++;return 'gpt-reserve';}};assert.throws(()=>s.matches(hostile));assert.equal(calls,0);});
