import test from 'node:test';
import assert from 'node:assert/strict';
import {PortableResidentLifecycle} from '../../../src/app-server/portable-resident-lifecycle.ts';
import {UsageAction} from '../../../src/runtime/action-executor/usage-action.ts';
import {MissingActionAppServerError} from '../../../src/runtime/action-executor/errors.ts';
async function fixture(mode:string,run:(server:PortableResidentLifecycle,seen:()=>Promise<string[]>)=>Promise<void>){
 const code=`import readline from 'node:readline';const mode=${JSON.stringify(mode)},seen=[];const emit=x=>process.stdout.write(JSON.stringify(x)+'\\n');readline.createInterface({input:process.stdin}).on('line',l=>{const m=JSON.parse(l),reply=result=>emit({id:m.id,result});if(m.method==='initialize')reply({});else if(m.method==='initialized'){}else if(m.method==='seen')reply(seen);else{seen.push(m.method);if(mode==='hang')return;if(mode==='error'){emit({id:m.id,error:{code:-9,message:'account denied'}});return;}if(m.method==='account/rateLimits/read')reply({rateLimits:{planType:'pro',primary:{usedPercent:25,windowDurationMins:60}}});else if(m.method==='account/usage/read')reply(mode==='empty'?{}:{dailyUsageBuckets:[{startDate:new Date().toISOString().slice(0,10),tokens:23}],summary:{lifetimeTokens:42}});else emit({id:m.id,error:{code:-10,message:'unexpected method'}});}});`;
 const server=await PortableResidentLifecycle.start({process:{executable:process.execPath,arguments:['--input-type=module','-e',code],environment:{}},clientInfo:{name:'usage',title:'fixture',version:'1'}},()=> 'safe',{persistDeadWork(){},oldChildExited(){}},undefined,{fence:null,renderError:()=> 'safe'});
 const seen=async()=>{const a=server.admitRequest();try{return await a.client.requestAdmitted(a.permit,'seen',{},1000) as string[];}finally{a.release();}};
 try{await run(server,seen);}finally{await server.dispose();}
}
test('actual native account observations execute rates then usage and render final immutable reply',async()=>fixture('ok',async(server,seen)=>{const out=await new UsageAction(server).usage(7);assert.deepEqual(await seen(),['account/rateLimits/read','account/usage/read']);assert.ok(out.text.includes('total_tokens: 23'));assert.ok(out.text.includes('primary: used=25% window=1h'));assert.equal(out.waitsForFinal,false);assert.equal(out.ui,null);assert.ok(Object.isFrozen(out));}));
test('empty account usage remains unknown instead of successful zero usage',async()=>fixture('empty',async server=>{const out=await new UsageAction(server).usage(0);assert.ok(out.text.includes('Codex usage (1d live)'));assert.ok(out.text.includes('usage data unavailable'));assert.ok(!out.text.includes('total_tokens: 0'));}));
test('native rate failure stops before usage without manufacturing partial success',async()=>fixture('error',async(server,seen)=>{await assert.rejects(new UsageAction(server).usage(1));assert.deepEqual(await seen(),['account/rateLimits/read']);}));
test('caller cancellation interrupts native wait and joins request ownership without usage followup',async()=>fixture('hang',async(server,seen)=>{const a=new AbortController(),reason=new Error('cancel usage'),task=new UsageAction(server).usage(1,a.signal);for(let i=0;i<100&&(await seen()).length===0;i++)await new Promise(r=>setTimeout(r,5));a.abort(reason);await assert.rejects(task,e=>e===reason);assert.deepEqual(await seen(),['account/rateLimits/read']);}));
test('missing server and invalid input fail explicitly; preabort produces no native call',async()=>{await assert.rejects(new UsageAction(null).usage(1),MissingActionAppServerError);await fixture('ok',async(server,seen)=>{const action=new UsageAction(server),a=new AbortController(),reason=new Error('pre');a.abort(reason);await assert.rejects(action.usage(1,a.signal),e=>e===reason);for(const days of [-1,0.1,4294967296])await assert.rejects(action.usage(days),TypeError);assert.deepEqual(await seen(),[]);});});
