import assert from 'node:assert/strict';
import {test} from 'node:test';
import {createServer,type RequestListener} from 'node:http';
import {dirname} from 'node:path';
import {storeFixture} from '../helpers/store-fixture.ts';
import {AttachmentHttpClient} from '../../src/runtime/attachment-client.ts';
import {downloadAttachment} from '../../src/runtime/attachment-download.ts';
import {enrichMessageAttachments} from '../../src/runtime/attachments.ts';
import {decodeGatewayMessage} from '../../src/discord/gateway/decoded-message.ts';
async function fixture(handler:RequestListener,run:(base:string,client:AttachmentHttpClient)=>Promise<void>){const server=createServer(handler);await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const client=new AttachmentHttpClient();try{await run(`http://127.0.0.1:${(server.address() as {port:number}).port}`,client);}finally{await client.close();server.closeAllConnections();await new Promise<void>((r,j)=>server.close(e=>e?j(e):r()));assert.equal(client.activeRequests,0);assert.equal(client.ownedSockets,0);}}
async function body(client:AttachmentHttpClient,url:string){const response=await client.get(url);try{let text='';for await(const chunk of response.chunks)text+=Buffer.from(chunk).toString();return text;}finally{await response.release();}}
test('pre-aborted attachment request opens no connection and preserves exact abort identity',()=>fixture((_req,res)=>res.end('ok'),async(base,client)=>{const controller=new AbortController(),reason=new Error('stop');controller.abort(reason);await assert.rejects(client.get(base,controller.signal),e=>e===reason);assert.equal(client.activeRequests,0);assert.equal(client.ownedSockets,0);assert.equal(await body(client,base),'ok');}));
test('per-request header cancellation joins one request while unrelated client work remains usable',()=>fixture((req,res)=>{if(req.url==='/ok')res.end('ok');},async(base,client)=>{const controller=new AbortController(),reason=new Error('header stop'),pending=client.get(base+'/hang',controller.signal),failed=assert.rejects(pending,e=>e===reason);controller.abort(reason);await failed;assert.equal(client.activeRequests,0);assert.equal(await body(client,base+'/ok'),'ok');}));
test('per-request body cancellation joins stream and keeps concurrent response ownership intact',()=>fixture((req,res)=>{if(req.url==='/hang'){res.writeHead(200);res.write('a');}else res.end('ok');},async(base,client)=>{const controller=new AbortController(),reason=new Error('body stop'),response=await client.get(base+'/hang',controller.signal),iterator=response.chunks[Symbol.asyncIterator]();await iterator.next();const other=client.get(base+'/ok'),failed=assert.rejects(iterator.next(),e=>e===reason);controller.abort(reason);await failed;await response.release();const ok=await other;let text='';for await(const chunk of ok.chunks)text+=Buffer.from(chunk).toString();await ok.release();assert.equal(text,'ok');assert.equal(client.activeRequests,0);}));
test('aborted file stream closes partial output and releases transport without succeeding',()=>storeFixture(path=>fixture((_req,res)=>{res.writeHead(200);res.write('abc');},async(base,client)=>{const controller=new AbortController(),reason=new Error('file stop');let observed!:()=>void;const started=new Promise<void>(r=>observed=r);const transport={async get(url:string,signal?:AbortSignal){const response=await client.get(url,signal);return {...response,chunks:(async function*(){for await(const chunk of response.chunks){yield chunk;observed();}})()};}};const pending=downloadAttachment(1n,{filename:'a.txt',size:3n,url:base,contentType:'text/plain'},dirname(path),100n,100n,transport,true,controller.signal),failed=assert.rejects(pending,e=>e===reason);await started;controller.abort(reason);await failed;assert.equal(client.activeRequests,0);}))); 
test('ordinary enrichment never converts cancellation into failed-attachment text or starts next download',()=>storeFixture(async path=>{
 const controller=new AbortController(),reason=new Error('envelope stop');let gets=0,releases=0,reports=0;const m=decodeGatewayMessage(JSON.stringify({attachments:[1,2].map(id=>({id:String(id),filename:`a${id}.txt`,size:0,url:'https://example.invalid/unused',proxy_url:'https://example.invalid/unused'})),author:{id:'2',username:'u',discriminator:'0'},channel_id:'1',content:'ask',embeds:[],id:'3',mention_everyone:false,mention_roles:[],mentions:[],pinned:false,timestamp:'2020-01-01T00:00:00+00:00',tts:false,type:0}));
 const transport={async get(_url:string,signal?:AbortSignal){assert.equal(signal,controller.signal);gets++;return {contentLength:null,chunks:(async function*(){yield Buffer.from('a');controller.abort(reason);throw reason;})(),async release(){releases++;}};}};
 await assert.rejects(enrichMessageAttachments(m,'ask',{attachmentsEnabled:true,attachmentMaxBytes:100n,attachmentTextInlineMaxBytes:100n},dirname(path),transport,false,()=>{reports++;},controller.signal),e=>e===reason);assert.equal(gets,1);assert.equal(releases,1);assert.equal(reports,0);
}));
