import {PortableResidentLifecycle} from '../../src/app-server/portable-resident-lifecycle.ts';
import {readThread} from '../../src/app-server/requests.ts';
import test from 'node:test';import assert from 'node:assert/strict';import {OwnedWorkerSlot,OwnedWorkerBusyError,OwnedWorkerTimeoutError} from '../../src/runtime/owned-worker-slot.ts';
const worker=(source:string)=>new URL('data:text/javascript,'+encodeURIComponent(source));
const blocked=worker(`import {parentPort,workerData} from 'node:worker_threads';const a=new Int32Array(workerData);Atomics.store(a,1,1);Atomics.notify(a,1);Atomics.wait(a,0,0,10000);parentPort.postMessage('late snapshot');parentPort.close();`);
test('actual worker timeout retains singleton ownership until joined exit and never blocks main-loop timers',{timeout:8000},async()=>{
 const slot=new OwnedWorkerSlot(),shared=new SharedArrayBuffer(8),a=new Int32Array(shared);let ticks=0;const timer=setInterval(()=>ticks++,20);const started=performance.now();const pending=slot.run(blocked,shared,3000);try{await assert.rejects(pending,OwnedWorkerTimeoutError);assert.ok(performance.now()-started>=2900);assert.ok(ticks>30);assert.equal(slot.busy,true);assert.equal(Atomics.load(a,1),1);for(let i=0;i<16;i++)await assert.rejects(slot.run(blocked,shared,3000),OwnedWorkerBusyError);const code="import readline from 'node:readline';readline.createInterface({input:process.stdin}).on('line',line=>{const m=JSON.parse(line);if(m.id!==undefined)process.stdout.write(JSON.stringify({id:m.id,result:m.method==='thread/read'?{thread:{id:m.params.threadId,status:{type:'idle'}}}:{}})+'\\n');});";const server=await PortableResidentLifecycle.start({process:{executable:process.execPath,arguments:['--input-type=module','-e',code],environment:{}},clientInfo:{name:'context-isolation',title:'fixture',version:'1'}},()=> 'safe',{persistDeadWork(){},oldChildExited(){}},undefined,{fence:null,renderError:()=> 'safe'});try{assert.deepEqual(await server.execute(readThread('unrelated-target',false),server.generation()),{thread:{id:'unrelated-target',status:{type:'idle'}}});assert.equal(slot.busy,true);}finally{await server.dispose();}}finally{Atomics.store(a,0,1);Atomics.notify(a,0);clearInterval(timer);await slot.join();}assert.equal(slot.busy,false);assert.equal(await slot.run(worker("import {parentPort} from 'node:worker_threads';parentPort.postMessage('fresh');parentPort.close();"),null,1000),'fresh');
});
test('caller abort rejects promptly but cannot admit another worker until original exits',async()=>{const slot=new OwnedWorkerSlot(),shared=new SharedArrayBuffer(8),a=new Int32Array(shared),controller=new AbortController(),reason=new Error('cancel original');const pending=slot.run(blocked,shared,3000,controller.signal);controller.abort(reason);try{await assert.rejects(pending,e=>e===reason);assert.equal(slot.busy,true);await assert.rejects(slot.run(blocked,shared,3000),OwnedWorkerBusyError);}finally{Atomics.store(a,0,1);Atomics.notify(a,0);await slot.join();}assert.equal(slot.busy,false);});
test('native crash and missing result release owner and fail rather than deliver a snapshot',async()=>{for(const code of ["throw new Error('fixture crash')",'']){const slot=new OwnedWorkerSlot();await assert.rejects(slot.run(worker(code),null,1000));assert.equal(slot.busy,false);}});
test('pre-aborted caller creates no owner',()=>{const slot=new OwnedWorkerSlot(),a=new AbortController();a.abort(new Error('already stopped'));assert.throws(()=>slot.run(blocked,null,1000,a.signal),/already stopped/);assert.equal(slot.busy,false);});
