import test from 'node:test';import assert from 'node:assert/strict';import {OwnedWorkerSlot,OwnedWorkerBudgetError,OwnedWorkerTimeoutError,ownedWorkerUsage,OWNED_WORKER_LIMITS} from '../../src/runtime/owned-worker-slot.ts';
const worker=(s:string)=>new URL('data:text/javascript,'+encodeURIComponent(s));
const blocked=worker("import{parentPort,workerData}from'node:worker_threads';Atomics.wait(new Int32Array(workerData),0,0,10000);parentPort.postMessage('finished');parentPort.close();");
const fresh=worker("import{parentPort}from'node:worker_threads';parentPort.postMessage('fresh');parentPort.close();");
test('three actual background workers cannot consume reserved control capacity and timeout does not release slots',async()=>{const slots=Array.from({length:3},()=>new OwnedWorkerSlot()),shared=new SharedArrayBuffer(4),a=new Int32Array(shared);const pending=slots.map(slot=>slot.run(blocked,shared,10).catch(e=>e));try{assert.deepEqual(ownedWorkerUsage(),{Background:3,Control:0});await assert.rejects(new OwnedWorkerSlot().run(fresh,null,1000),OwnedWorkerBudgetError);assert.equal(await new OwnedWorkerSlot('Control').run(fresh,null,2000),'fresh');for(const result of await Promise.all(pending))assert.ok(result instanceof OwnedWorkerTimeoutError);assert.deepEqual(ownedWorkerUsage(),{Background:3,Control:0});await assert.rejects(new OwnedWorkerSlot().run(fresh,null,1000),OwnedWorkerBudgetError);}finally{Atomics.store(a,0,1);Atomics.notify(a,0,3);await Promise.all(slots.map(s=>s.join()));}assert.deepEqual(ownedWorkerUsage(),{Background:0,Control:0});});
test('control ownership remains exclusive until actual worker exit after abort',async()=>{const slot=new OwnedWorkerSlot('Control'),shared=new SharedArrayBuffer(4),a=new Int32Array(shared),c=new AbortController(),reason={cancel:true};const pending=slot.run(blocked,shared,1000,c.signal);c.abort(reason);try{await assert.rejects(pending,e=>e===reason);assert.equal(ownedWorkerUsage().Control,1);await assert.rejects(new OwnedWorkerSlot('Control').run(fresh,null,1000),OwnedWorkerBudgetError);assert.equal(await new OwnedWorkerSlot().run(fresh,null,2000),'fresh');}finally{Atomics.store(a,0,1);Atomics.notify(a,0);await slot.join();}assert.equal(ownedWorkerUsage().Control,0);});
test('constructor clone failure and native crash return global capacity exactly once',async()=>{const slot=new OwnedWorkerSlot();assert.throws(()=>slot.run(fresh,()=>{},1000));assert.equal(slot.busy,false);assert.deepEqual(ownedWorkerUsage(),{Background:0,Control:0});await assert.rejects(slot.run(worker("throw new Error('crash')"),null,1000),/crash/);assert.deepEqual(ownedWorkerUsage(),{Background:0,Control:0});assert.equal(await slot.run(fresh,null,1000),'fresh');assert.deepEqual(ownedWorkerUsage(),{Background:0,Control:0});});
test('native child cannot create an independent nested budget island',async()=>{const url=new URL('../../src/runtime/owned-worker-slot.ts',import.meta.url).href;const child=worker(`import{parentPort}from'node:worker_threads';import{OwnedWorkerSlot}from ${JSON.stringify(url)};try{new OwnedWorkerSlot().run(new URL('data:text/javascript,'),null,1000);parentPort.postMessage('unexpected');}catch(e){parentPort.postMessage(e.message);}parentPort.close();`);assert.match(String(await new OwnedWorkerSlot().run(child,null,2000)),/main runtime owner/);assert.deepEqual(ownedWorkerUsage(),{Background:0,Control:0});});
test('invalid lane cannot corrupt counters and callers cannot mutate usage snapshots',()=>{assert.throws(()=>new OwnedWorkerSlot('unexpected' as any),TypeError);assert.ok(Object.isFrozen(ownedWorkerUsage()));assert.ok(Object.isFrozen(OWNED_WORKER_LIMITS));assert.deepEqual(ownedWorkerUsage(),{Background:0,Control:0});});
