import test from 'node:test';import assert from 'node:assert/strict';import {dirname,join} from 'node:path';import {readFile,writeFile,access,readdir,mkdir} from 'node:fs/promises';import {setTimeout as sleep} from 'node:timers/promises';
import {storeFixture} from '../helpers/store-fixture.ts';
import {runRuntimeHeartbeat,posixRuntimeHeartbeatPort,encodeRuntimeHeartbeat,RUNTIME_HEARTBEAT_NAME} from '../../src/runtime/runtime-heartbeat.ts';
import {writePosixAtomicMarker} from '../../src/runtime/atomic-marker.ts';
async function until(p:()=>boolean){const end=performance.now()+2000;while(!p()){assert.ok(performance.now()<end);await sleep(1);}}
test('heartbeat wire matches integer pid/time and rejects non-u64 values',()=>{assert.equal(encodeRuntimeHeartbeat(123,456n),'pid=123\nupdated_at=456\n');assert.equal(encodeRuntimeHeartbeat(0,0n),'pid=0\nupdated_at=0\n');for(const v of [-1n,1n<<64n,1 as never])assert.throws(()=>encodeRuntimeHeartbeat(1,v));assert.throws(()=>encodeRuntimeHeartbeat(-1,0n));});
test('actual POSIX heartbeat publishes immediately and removes last owned marker after stop',async()=>storeFixture(async p=>{const path=join(dirname(p),RUNTIME_HEARTBEAT_NAME),port=posixRuntimeHeartbeatPort(path),stop=new AbortController();let writes=0;const task=runRuntimeHeartbeat({publish:async text=>{await port.publish(text);writes++;},removeIfOwned:port.removeIfOwned},stop.signal,{pid:123,seconds:()=>456n,periodMs:5,report(){}});try{await until(()=>writes>=1);assert.equal(await readFile(path,'utf8'),'pid=123\nupdated_at=456\n');stop.abort();await task;await assert.rejects(access(path));assert.ok(!(await readdir(dirname(p))).some(n=>n.endsWith('.tmp')));}finally{stop.abort();await task;}}));
test('stop does not return before outstanding marker publication and exact cleanup complete',async()=>{const stop=new AbortController();let started=false,finished=false,removed=false,release!:()=>void;const blocked=new Promise<void>(r=>{release=r;});const task=runRuntimeHeartbeat({publish:async()=>{started=true;await blocked;},removeIfOwned:async text=>{assert.equal(text,'pid=1\nupdated_at=2\n');removed=true;}},stop.signal,{pid:1,seconds:()=>2n,periodMs:2,report(){}}).then(()=>{finished=true;});await until(()=>started);stop.abort();await sleep(3);assert.equal(finished,false);release();await task;assert.equal(removed,true);});
test('write errors are reported and retried serially; clock failure writes zero',async()=>{const stop=new AbortController(),error={write:true};let writes=0,active=0,max=0,reported=0;const task=runRuntimeHeartbeat({publish:async text=>{active++;max=Math.max(max,active);try{assert.equal(text,'pid=7\nupdated_at=0\n');if(++writes===1)throw error;stop.abort();}finally{active--; }},removeIfOwned:async()=>{}},stop.signal,{pid:7,seconds:()=>{throw Error('clock');},periodMs:2,report(e,x){assert.equal(e,'runtime_heartbeat_write_failed');assert.equal(x,error);reported++;}});await task;assert.equal(writes,2);assert.equal(reported,1);assert.equal(max,1);});
test('foreign changed, BOM-prefixed and oversized markers are never removed as owned',async()=>storeFixture(async p=>{const path=join(dirname(p),'heartbeat'),port=posixRuntimeHeartbeatPort(path),expected=encodeRuntimeHeartbeat(1,2n);for(const foreign of ['pid=2\nupdated_at=2\n','\ufeff'+expected,expected+'x'.repeat(200)]){await writeFile(path,foreign);await port.removeIfOwned(expected);assert.equal(await readFile(path,'utf8'),foreign);}}));
test('no successful publication means no cleanup of an existing foreign marker',async()=>{const stop=new AbortController();let removed=0;await runRuntimeHeartbeat({publish:async()=>{stop.abort();throw Error('write');},removeIfOwned:async()=>{removed++;}},stop.signal,{report(){}});assert.equal(removed,0);});
test('prestop performs no write/remove and active optional getter is rejected',async()=>{const stop=new AbortController();stop.abort();let calls=0;const p={publish:async()=>{calls++;},removeIfOwned:async()=>{calls++;}};await runRuntimeHeartbeat(p,stop.signal,{report(){}});assert.equal(calls,0);let getters=0;const options={report(){}};Object.defineProperty(options,'pid',{get(){getters++;return 1;}});await assert.rejects(runRuntimeHeartbeat(p,stop.signal,options),TypeError);assert.equal(getters,0);});
test('cleanup report failure is visible after IO joined, rather than silently claiming success',async()=>{const stop=new AbortController(),error={report:true};await assert.rejects(runRuntimeHeartbeat({publish:async()=>{stop.abort();},removeIfOwned:async()=>{throw Error('cleanup');}},stop.signal,{report(){throw error;}}),e=>e===error);});
test('atomic replacement failure preserves existing target directory and removes only owned temporary',async()=>storeFixture(async p=>{await mkdir(p);await writeFile(join(p,'sentinel'),'keep');await assert.rejects(writePosixAtomicMarker(p,'value'));assert.equal(await readFile(join(p,'sentinel'),'utf8'),'keep');assert.ok(!(await readdir(dirname(p))).some(n=>n.endsWith('.tmp')));}));
