import test from 'node:test';import assert from 'node:assert/strict';
import {storeFixture} from '../helpers/store-fixture.ts';
import {openInitialized} from '../../src/store/owned-driver.ts';
import {PortableResidentLifecycle} from '../../src/app-server/portable-resident-lifecycle.ts';
import {createMutationCustodyFence} from '../../src/runtime/mutation-custody-fence.ts';
import {DEFAULT_THREAD_SETTINGS_UPDATE,rateLimits} from '../../src/app-server/requests.ts';
const update={...DEFAULT_THREAD_SETTINGS_UPDATE,model:'model-b'};
async function fixture(mode:string,run:(server:PortableResidentLifecycle,call:(method:string,params?:unknown)=>Promise<unknown>,path:string)=>Promise<void>){await storeFixture(async path=>{
 const db=await openInitialized(path);db.exec("INSERT INTO codex_mutation_runtime VALUES(1,'runtime');INSERT INTO codex_app_server_runtime VALUES(1,'runtime')");db.close();
 const code=`import readline from 'node:readline';const mode=${JSON.stringify(mode)},seen=[];const emit=x=>process.stdout.write(JSON.stringify(x)+'\\n');const settings=()=>emit({method:'thread/settings/updated',params:{threadId:'t',threadSettings:{model:'model-b',effort:null,serviceTier:null}}});readline.createInterface({input:process.stdin}).on('line',l=>{const m=JSON.parse(l),reply=result=>emit({id:m.id,result});if(m.method==='initialize')reply({});else if(m.method==='initialized'){}else if(m.method==='seen')reply(seen);else if(m.method==='seed'){settings();reply({});}else if(m.method==='unload'){emit({method:'thread/status/changed',params:{threadId:'t',status:{type:'notLoaded'}}});reply({});}else if(m.method==='pause'){reply({});process.stdin.pause();setTimeout(settings,250);setTimeout(()=>process.stdin.resume(),650);}else if(m.method==='hold')reply({});else{seen.push({method:m.method,params:m.params});if(mode==='hang')return;if(mode==='error')emit({id:m.id,error:{code:-8,message:'denied'}});else{if(mode==='fresh')settings();reply({});}}});`;
 const render=(e:unknown)=>e instanceof Error?e.message:'opaque';const server=await PortableResidentLifecycle.start({process:{executable:process.execPath,arguments:['--input-type=module','-e',code],environment:{}},clientInfo:{name:'watermark',title:'fixture',version:'1'}},render,{persistDeadWork(){},oldChildExited(){}},undefined,{renderError:render,fence:createMutationCustodyFence(path,'runtime',render)});
 const call=async(method:string,params:unknown={})=>{const a=server.admitResponse(server.generation());try{return await a.client.requestAdmitted(a.permit,method,params,2500);}finally{a.release();}};
 try{await run(server,call,path);}finally{await server.dispose();}
});}
test('native fresh settings revision is after writer watermark while earlier same value is not',async()=>fixture('fresh',async(server,call)=>{await call('seed');const old=server.observedThreadSettings('t',1n)!;assert.equal(old[0],1n);const before=await server.updateSettingsWithWatermark('t',update,1n);const fresh=server.observedThreadSettings('t',1n)!;assert.equal(before,old[0]);assert.ok(fresh[0]>before);assert.equal(server.observedThreadSettings('other',1n),null);assert.throws(()=>server.observedThreadSettings('t',2n),/generation/i);await call('unload');assert.equal(server.observedThreadSettings('t',1n),null);}));
test('native writer backpressure excludes a matching notification arriving while settings waits',async()=>fixture('ack',async(server,call)=>{await call('pause');assert.equal(server.observedThreadSettings('t',1n),null);const blocker=call('hold',{padding:'x'.repeat(4*1024*1024)}),task=server.updateSettingsWithWatermark('t',update,1n);const [before]=await Promise.all([task,blocker]);const old=server.observedThreadSettings('t',1n)!;assert.ok(old!==null);assert.ok(before>=old[0],'notification received during writer wait must not count as post-dispatch evidence');}));
test('ACK without a fresh notification does not synthesize observed settings',async()=>fixture('ack',async(server,call)=>{const before=await server.updateSettingsWithWatermark('t',update,1n);assert.equal(before,0n);assert.equal(server.observedThreadSettings('t',1n),null);const seen=await call('seen') as any[];assert.deepEqual(seen.map(x=>x.method),['thread/settings/update']);assert.equal(seen[0].params.threadId,'t');assert.equal(seen[0].params.model,'model-b');}));
test('remote failure preserves native error and generation mismatch dispatches nothing',async()=>fixture('error',async(server,call)=>{await assert.rejects(server.updateSettingsWithWatermark('t',update,2n),/generation/i);assert.deepEqual(await call('seen'),[]);await assert.rejects(server.updateSettingsWithWatermark('t',update,1n),/denied/);}));
test('preabort and durable runtime fence rejection cannot reach native settings writer',async()=>fixture('ack',async(server,call,path)=>{const a=new AbortController(),reason=new Error('pre');a.abort(reason);await assert.rejects(server.updateSettingsWithWatermark('t',update,1n,a.signal),e=>e===reason);const db=await openInitialized(path);try{db.exec("UPDATE codex_mutation_runtime SET runtime_id='other'");}finally{db.close();}await assert.rejects(server.updateSettingsWithWatermark('t',update,1n));assert.deepEqual(await call('seen'),[]);}));

test('ordinary requests ignore inherited watermark hook without executing a getter',async()=>fixture('ack',async(server)=>{let calls=0;const old=Object.getOwnPropertyDescriptor(Object.prototype,'writeWatermark');Object.defineProperty(Object.prototype,'writeWatermark',{configurable:true,get(){calls++;throw new Error('inherited hook');}});try{await server.execute(rateLimits(),1n);}finally{if(old)Object.defineProperty(Object.prototype,'writeWatermark',old);else Reflect.deleteProperty(Object.prototype,'writeWatermark');}assert.equal(calls,0);}));
