import assert from 'node:assert/strict';
import {PortableResidentLifecycle} from '../../src/app-server/portable-resident-lifecycle.ts';
import type {AsyncChoiceIdentity} from '../../src/runtime/component-worker/async-choice-preflight.ts';
export interface Config {active?: string | null; latest?: unknown; goal?: unknown; history?: unknown; fail?: string; dispatch?: 'missing' | 'wrong' | 'remote' | 'usage' | 'close'; changeSecondList?: boolean}
export async function asyncChoiceServer(config: Config, run: (server: PortableResidentLifecycle, q: AsyncChoiceIdentity, seen: () => Promise<any[]>) => Promise<void>) {
  const initial={active:null,latest:{data:[{id:'v',status:'completed'}]},goal:{goal:null},history:{thread:{id:'t',turns:[{id:'v',status:'completed'},{id:'old',status:'failed'}]}},...config};
  const code=`import readline from 'node:readline';const c=${JSON.stringify(initial)},seen=[];let lists=0;const emit=x=>process.stdout.write(JSON.stringify(x)+'\\n');readline.createInterface({input:process.stdin}).on('line',line=>{const m=JSON.parse(line),reply=result=>emit({id:m.id,result});if(m.method==='initialize')reply({});else if(m.method==='initialized'){}else if(m.method==='seed'){emit(c.active===null?{method:'turn/completed',params:{threadId:'t',turnId:'v'}}:{method:'turn/started',params:{threadId:'t',turnId:c.active}});reply({});}else if(m.method==='seen')reply(seen);else {seen.push({method:m.method,params:m.params});if(c.fail===m.method)emit({id:m.id,error:{code:-7,message:'fixture rejected'}});else if(m.method==='thread/turns/list'){lists++;reply(c.changeSecondList&&lists===2?{data:[{id:'successor',status:'completed'}]}:c.latest);}else if(m.method==='thread/goal/get')reply(c.goal);else if(m.method==='thread/read')reply(c.history);else if(m.method==='turn/steer'||m.method==='turn/start'){if(c.dispatch==='close')process.exit(0);else if(c.dispatch==='remote'||c.dispatch==='usage')emit({id:m.id,error:{code:-7,message:'dispatch rejected',data:c.dispatch==='usage'?{type:'usageLimitExceeded'}:null}});else if(c.dispatch==='missing')reply({});else reply(m.method==='turn/steer'?{turnId:c.dispatch==='wrong'?'wrong':'v'}:{turn:{id:c.dispatch==='wrong'?'v':'next'}});}else emit({id:m.id,error:{code:-8,message:'unexpected method'}});}});`;
  const server=await PortableResidentLifecycle.start({process:{executable:process.execPath,arguments:['--input-type=module','-e',code],environment:{}},clientInfo:{name:'preflight',title:'fixture',version:'1'}},()=> 'fixture error',{persistDeadWork(){},oldChildExited(){}},undefined,{fence:null,renderError:()=> 'fixture error'});
  const call=async(method:string)=>{const a=server.admitRequest();try{return await a.client.requestAdmitted(a.permit,method,{},2000);}finally{a.release();}};
  try {await call('seed');await run(server,{runtimeId:server.instanceId,generation:1n,threadId:'t',turnId:'v'},async()=>await call('seen') as any[]);} finally {await server.dispose();assert.equal(server.lifecycleSnapshot().healthy,false);}
}
