import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {join,dirname} from 'node:path';
import {storeFixture} from '../../helpers/store-fixture.ts';import {startRuntimeResident} from '../../../src/runtime/discord-runtime/resident-startup.ts';import {loadRuntimeAutocomplete} from '../../../src/runtime/discord-runtime/autocomplete-bootstrap.ts';
import {decodeGatewayInteraction} from '../../../src/discord/gateway/decoded-interaction.ts';import {routeGatewayCommand} from '../../../src/discord/interaction-routing.ts';
const render=(e:unknown)=>e instanceof Error?e.message:'native error';
function work(){return routeGatewayCommand(decodeGatewayInteraction(JSON.stringify({application_id:'2',authorizing_integration_owners:{},channel_id:'10',id:'4',token:'offline',type:4,user:{id:'20',username:'tester',discriminator:'0001'},data:{id:'3',name:'settings',type:1,options:[{name:'model',type:3,value:'',focused:true}]}})),false).work;}
async function fixture(response:unknown,run:(server:Awaited<ReturnType<typeof startRuntimeResident>>,log:string)=>Promise<void>){await storeFixture(async path=>{
 const log=join(dirname(path),'methods.jsonl'),code=`import readline from 'node:readline';import{appendFileSync}from'node:fs';readline.createInterface({input:process.stdin}).on('line',l=>{const m=JSON.parse(l);appendFileSync(${JSON.stringify(log)},JSON.stringify(m)+'\\n');if(m.id!==undefined)process.stdout.write(JSON.stringify({id:m.id,...(m.method==='model/list'?${JSON.stringify(response)}:{result:{}})})+'\\n');});`;
 const server=await startRuntimeResident({process:{executable:process.execPath,arguments:['--input-type=module','-e',code],environment:{}},clientInfo:{name:'catalog-test',title:'fixture',version:'1'}},path,'runtime',null,render);try{await run(server,log);}finally{await server.dispose();}
});}
async function calls(log:string){return(await readFile(log,'utf8')).trim().split('\n').map(x=>JSON.parse(x)).filter(x=>x.method==='model/list');}
test('native model/list builds original filtered catalog once without replacing its resident',async()=>fixture({result:{data:[{model:' alpha '},{model:'hidden',hidden:true},{id:'fallback'},{model:'alpha'}]}},async(server,log)=>{const pid=server.lifecycleSnapshot().processId,catalog=await loadRuntimeAutocomplete(server);assert.deepEqual(catalog.choices(work()).map(x=>x.name),['alpha','fallback']);const requests=await calls(log);assert.equal(requests.length,1);assert.deepEqual(requests[0].params,{});assert.equal(server.lifecycleSnapshot().processId,pid);assert.equal(server.generation(),1n);}));
test('native model/list error propagates without successful empty catalog fallback',async()=>fixture({error:{code:-32000,message:'catalog denied'}},async(server,log)=>{await assert.rejects(loadRuntimeAutocomplete(server),/catalog denied/);assert.equal((await calls(log)).length,1);assert.equal(server.lifecycleSnapshot().healthy,true);}));
test('successful schema without models preserves source empty catalog semantics',async()=>fixture({result:{other:'value'}},async(server,log)=>{assert.deepEqual((await loadRuntimeAutocomplete(server)).choices(work()),[]);assert.equal((await calls(log)).length,1);}));
test('pre-aborted bootstrap preserves exact reason and emits no native model/list',async()=>fixture({result:{}},async(server,log)=>{const reason={cancelled:true},controller=new AbortController();controller.abort(reason);await assert.rejects(loadRuntimeAutocomplete(server,controller.signal),e=>e===reason);assert.equal((await calls(log)).length,0);}));
test('quarantined native generation is not silently restarted to populate catalog',async()=>fixture({result:{}},async(server,log)=>{server.markTimeout(1n);await assert.rejects(loadRuntimeAutocomplete(server));assert.equal((await calls(log)).length,0);assert.equal(server.generation(),1n);}));
