import test from 'node:test';import assert from 'node:assert/strict';import {setTimeout as sleep} from 'node:timers/promises';
import {AdmissionGate,DrainFenceKey,type AdmissionPermit} from '../../../src/admission/drain-gate.ts';
import {drainUntilQuiescent,type GatewayDrainPorts} from '../../../src/runtime/discord-runtime/gateway-drain.ts';
const timing={admissionTimeoutMs:20,pollMs:2,errorRetryMs:4};
function setup(){const gate=new AdmissionGate(),key=DrainFenceKey.create('runtime','123|456','nonce'),stop=new AbortController();gate.seal(key);return {gate,key,stop};}
function ports(overrides:Partial<GatewayDrainPorts>={}):GatewayDrainPorts{return {stopRequested:async()=>false,inspect:async()=>({kind:'Ready'}),report(){},...overrides};}
async function until(check:()=>boolean){const deadline=performance.now()+2000;while(!check()){assert.ok(performance.now()<deadline,'fixture signal timeout');await sleep(1);}}
test('two successful inspections close controls and return exact key without unsealing',async()=>{const {gate,key,stop}=setup();let checks=0;const result=await drainUntilQuiescent(gate,key,ports({inspect:async()=>{if(++checks===1){const p=gate.tryEnterControl();p.release();}else assert.throws(()=>gate.tryEnterControl());return {kind:'Ready'};}}),stop.signal,timing);assert.deepEqual(result,{kind:'Drained',key});assert.equal(checks,2);assert.equal(gate.isSealed(),true);assert.throws(()=>gate.tryEnterControl());});
test('admission timeout logs and continues, never Shutdown, then succeeds after actual release',async()=>{const {gate,key,stop}=setup(),permit=gate.tryEnterControl();let timed=0,finished=false;const task=drainUntilQuiescent(gate,key,ports({report(e){if(e==='restart_drain_still_waiting')timed++;}}),stop.signal,timing).then(x=>{finished=true;return x;});try{await until(()=>timed>0);assert.equal(finished,false);assert.equal(gate.isSealed(),true);permit.release();assert.equal((await task).kind,'Drained');}finally{permit.release();stop.abort();await task;}});
test('final admission timeout reopens controls while ordinary ingress stays sealed',async()=>{const {gate,key,stop}=setup();let held:AdmissionPermit|undefined,reopened=false,checks=0;const task=drainUntilQuiescent(gate,key,ports({inspect:async()=>{if(++checks===1)held=gate.tryEnterControl();return {kind:'Ready'};},report(e){if(e==='restart_drain_controls_reopened'){reopened=true;const p=gate.tryEnterControl();p.release();assert.throws(()=>gate.tryEnter());held?.release();}}}),stop.signal,timing);try{assert.equal((await task).kind,'Drained');assert.equal(reopened,true);assert.ok(checks>=3);}finally{held?.release();stop.abort();await task;}});
test('final blocked inspection reopens controls and rechecks whole sequence',async()=>{const {gate,key,stop}=setup();let n=0,reopens=0;const result=await drainUntilQuiescent(gate,key,ports({inspect:async()=>++n===2?{kind:'Blocked',reason:'late work'}:{kind:'Ready'},report(e){if(e==='restart_drain_controls_reopened')reopens++;}}),stop.signal,timing);assert.equal(result.kind,'Drained');assert.equal(n,4);assert.equal(reopens,1);});
test('initial and final inspection errors retry while sealed, preserving exact diagnostic error',async()=>{for(const failAt of [1,2]){const {gate,key,stop}=setup(),sentinel={failAt};let n=0,seen=false;const r=await drainUntilQuiescent(gate,key,ports({inspect:async()=>{if(++n===failAt)throw sentinel;return {kind:'Ready'};},report(e,d){if(e.includes('live_check_failed')){assert.equal(d,sentinel);seen=true;assert.equal(gate.isSealed(),true);}}}),stop.signal,timing);assert.equal(r.kind,'Drained');assert.equal(seen,true);}});
test('explicit stop exits admission waiting without releasing outstanding permit',async()=>{const {gate,key,stop}=setup(),p=gate.tryEnterControl();const task=drainUntilQuiescent(gate,key,ports(),stop.signal,timing);stop.abort();assert.equal((await task).kind,'Shutdown');assert.equal(gate.isDrainedFor(key),false);p.release();});
test('stop marker during blocked live inspection aborts and joins before returning',async()=>{const {gate,key,stop}=setup();let marker=false,started=false,aborted=false,finished=false;let release!:()=>void;const blocked=new Promise<void>(r=>{release=r;});const task=drainUntilQuiescent(gate,key,ports({stopRequested:async()=>marker,inspect:async signal=>{started=true;signal.addEventListener('abort',()=>{aborted=true;},{once:true});await blocked;return {kind:'Ready'};}}),stop.signal,timing).then(x=>{finished=true;return x;});try{await until(()=>started);marker=true;await until(()=>aborted);assert.equal(finished,false);release();assert.equal((await task).kind,'Shutdown');}finally{release();stop.abort();await task;}});
test('stop during error backoff is responsive and never returns Drained',async()=>{const {gate,key,stop}=setup();let marker=false;const r=await drainUntilQuiescent(gate,key,ports({inspect:async()=>{throw Error('read');},report(){marker=true;},stopRequested:async()=>marker}),stop.signal,{...timing,errorRetryMs:1000});assert.equal(r.kind,'Shutdown');});
test('wrong existing fence is preserved until stop, not released or replaced',async()=>{const {gate,key,stop}=setup(),wrong=DrainFenceKey.create('other','123|456','nonce');let errors=0;const result=await drainUntilQuiescent(gate,wrong,ports({report(e){if(e==='restart_drain_admission_check_failed'){errors++;stop.abort();}}}),stop.signal,timing);assert.equal(result.kind,'Shutdown');assert.equal(errors,1);assert.equal(gate.isDrainedFor(key),true);});
test('prestop and malformed owned ports fail before inspection',async()=>{const {gate,key,stop}=setup();stop.abort();let calls=0;assert.equal((await drainUntilQuiescent(gate,key,ports({inspect:async()=>{calls++;return {kind:'Ready'};}}),stop.signal,timing)).kind,'Shutdown');assert.equal(calls,0);let getter=0;const p=ports();Object.defineProperty(p,'inspect',{get(){getter++;return async()=>({kind:'Ready'});}});await assert.rejects(drainUntilQuiescent(gate,key,p,stop.signal,timing),TypeError);assert.equal(getter,0);});
