import assert from 'node:assert/strict';import {test} from 'node:test';import {createServer} from 'node:http';import {once} from 'node:events';import {setImmediate as tick} from 'node:timers/promises';import WebSocket,{WebSocketServer} from 'ws';
import {RecommendedGateway} from '../../../src/discord/gateway/recommended.ts';import {runReadySetup} from '../../../src/runtime/discord-runtime/ready-setup.ts';import {readyHttpPort} from '../../../src/runtime/discord-runtime/ready-http-port.ts';import {RuntimeGatewayIdentityConflictError} from '../../../src/runtime/discord-runtime/identity-wait.ts';import {runReceiveErrorConsumer} from '../../../src/runtime/discord-runtime/receive-error-consumer.ts';
class Clock{now=0n;timers=new Set<{at:bigint;finish:()=>void}>();nowNs=()=>this.now;sleepUntilNs=(at:bigint,signal:AbortSignal):Promise<void>=>new Promise((resolve,reject)=>{if(signal.aborted){reject(signal.reason);return;}if(at<=this.now){resolve();return;}const finish=()=>{clean();resolve();},abort=()=>{clean();reject(signal.reason);},clean=()=>{this.timers.delete(item);signal.removeEventListener('abort',abort);},item={at,finish};this.timers.add(item);signal.addEventListener('abort',abort,{once:true});});advance(ms:number){this.now+=BigInt(ms)*1000000n;for(const t of [...this.timers])if(t.at<=this.now)t.finish();}}
async function turns(){for(let i=0;i<10;i++)await tick();}async function until(predicate:()=>boolean){for(let i=0;i<3000&&!predicate();i++)await tick();assert.equal(predicate(),true);}
const ready={application:{id:'1',flags:0},guilds:[],resume_gateway_url:'wss://gateway.discord.gg',session_id:'offline',user:{id:'2',username:'bot',discriminator:'0',mfa_enabled:false},v:10};const packet=(data:unknown)=>JSON.stringify({op:0,t:'READY',s:1,d:data});
async function fixture(initial:unknown=ready){const requests:string[]=[],errors:string[]=[],http=createServer((req,res)=>{assert.equal(req.headers.authorization,undefined);requests.push(req.method+' '+req.url);req.resume();req.on('end',()=>{res.end(req.url?.endsWith('/gateway/bot')?JSON.stringify({shards:1,url:'ignored',session_start_limit:{max_concurrency:1,remaining:1000,total:1000,reset_after:86400000}}):'{}');});});await new Promise<void>(r=>http.listen(0,'127.0.0.1',r));const ws=new WebSocketServer({host:'127.0.0.1',port:0});await once(ws,'listening');const peers:WebSocket[]=[];ws.on('connection',peer=>{peers.push(peer);peer.on('error',()=>{});peer.on('message',raw=>{const event=JSON.parse(raw.toString());if(event.op===2)peer.send(packet(initial));if(event.op===1)peer.send('{"op":11}');});peer.send('{"op":10,"d":{"heartbeat_interval":60000}}');});const clock=new Clock(),owner=await RecommendedGateway.startPausedForTest({httpOrigin:`http://127.0.0.1:${(http.address() as {port:number}).port}/api/v10/`,gatewayUrl:`ws://127.0.0.1:${(ws.address() as {port:number}).port}/`,clock,jitter:n=>n,messageContent:false,reportReceiveErrorDrop:()=>{},reportTriggerFailure:()=>{},reportHttpError:()=>{}}),receivers=owner.runtime.takeIngressReceivers(),identity=owner.runtime.subscribeIdentity(),conflict=owner.runtime.subscribeIdentityConflict(),shutdown=new AbortController(),force=new AbortController();
 const readyWork=runReadySetup(identity,conflict,shutdown.signal,force.signal,{port:readyHttpPort(owner.http),guildId:null,qaCommands:false,startupNotify:true,startupChannelId:91n,bootKey:()=> 'integration-boot',report:()=>{}});const readyOutcome=readyWork.then(()=>({ok:true as const}),error=>({ok:false as const,error}));const errorWork=runReceiveErrorConsumer(receivers.receiveErrors,shutdown.signal,force.signal,item=>{errors.push(item.message);});
 return {owner,clock,requests,errors,peers,readyOutcome,activate:async()=>{owner.runtime.activateTypedConsumers();await turns();clock.advance(1000);},close:async()=>{shutdown.abort();await readyOutcome;await owner.runtime.shutdown(performance.now()+2000);assert.deepEqual(await errorWork,{ok:true});await owner.close();identity.dispose();conflict.dispose();for(const [name,receiver] of Object.entries(receivers))if(name!=='receiveErrors')receiver.dispose();for(const peer of ws.clients)peer.terminate();await new Promise<void>(r=>ws.close(()=>r()));http.closeAllConnections();await new Promise<void>((r,j)=>http.close(e=>e?j(e):r()));assert.equal(owner.snapshot().httpSockets,0);assert.equal(owner.runtime.pendingTasks,0);assert.equal(clock.timers.size,0);}};
}
test('actual discovery to WebSocket READY to HTTP registration/notice joins complete owned chain',{timeout:5000},async()=>{const f=await fixture();try{await turns();assert.deepEqual(f.requests,['GET /api/v10/gateway/bot']);assert.equal(f.peers.length,0);await f.activate();await until(()=>f.requests.length===3&&f.owner.http.activeRequests===0);assert.deepEqual(new Set(f.requests),new Set(['GET /api/v10/gateway/bot','PUT /api/v10/applications/1/commands','POST /api/v10/channels/91/messages']));assert.equal(f.errors.length,0);}finally{await f.close();}});
test('invalid full READY cannot authorize registration even when raw session control was parseable',{timeout:5000},async()=>{const {user:_user,...invalid}=ready;const f=await fixture(invalid);try{await f.activate();await until(()=>f.errors.length===1);assert.equal(f.requests.length,1);f.peers[0]!.send(packet(ready));await until(()=>f.requests.length===3&&f.owner.http.activeRequests===0);}finally{await f.close();}});
test('later conflicting READY fails actual Ready consumer without another registration or notice',{timeout:5000},async()=>{const f=await fixture();try{await f.activate();await until(()=>f.requests.length===3&&f.owner.http.activeRequests===0);f.peers[0]!.send(packet({...ready,user:{...ready.user,id:'3'}}));const result=await f.readyOutcome;assert.ok(!result.ok);assert.ok(result.error instanceof RuntimeGatewayIdentityConflictError);await turns();assert.equal(f.requests.length,3);}finally{await f.close();}});
