import test from 'node:test';import assert from 'node:assert/strict';import {writeFileSync} from 'node:fs';import {dirname,join} from 'node:path';import {setTimeout as sleep} from 'node:timers/promises';
import {storeFixture} from '../../helpers/store-fixture.ts';
import {runGatewayControlLoop} from '../../../src/runtime/discord-runtime/gateway-control.ts';
import {RuntimeDrainController,posixDrainMarkerPort} from '../../../src/runtime/restart-readiness/drain-controller.ts';
import {PosixDrainMarkerStore,DRAIN_MARKER_NAMES} from '../../../src/runtime/restart-readiness/drain-marker.ts';
import {DrainFenceKey} from '../../../src/admission/owned-key.ts';
import type {GatewayDrainPorts} from '../../../src/runtime/discord-runtime/gateway-drain.ts';
const time={admissionTimeoutMs:20,pollMs:2,errorRetryMs:4};
async function until(p:()=>boolean){const end=performance.now()+2000;while(!p()){assert.ok(performance.now()<end,'fixture signal timeout');await sleep(1);}}
async function fixture(run:(c:RuntimeDrainController,s:PosixDrainMarkerStore,root:string)=>Promise<void>){await storeFixture(async p=>{const root=dirname(p),s=new PosixDrainMarkerStore(root),c=await RuntimeDrainController.initialize(posixDrainMarkerPort(s),{runtimeId:'runtime',processId:123});try{await run(c,s,root);}finally{await c.dispose();}});}
function ports(s:PosixDrainMarkerStore,report:GatewayDrainPorts['report']=()=>{}):GatewayDrainPorts{return {stopRequested:()=>s.stopRequested(),inspect:async()=>({kind:'Ready'}),report};}
test('exact prepare reaches Drained with its key and keeps ordinary/control ingress sealed',async()=>fixture(async(c,s,root)=>{writeFileSync(join(root,DRAIN_MARKER_NAMES.prepare),'version=1\nruntime_id=runtime\nprocess_identity=123|456\nnonce=exact\n');const a=new AbortController();const r=await runGatewayControlLoop(c,ports(s),a.signal,time);assert.equal(r.kind,'Drained');if(r.kind==='Drained')assert.equal(r.key.equals(DrainFenceKey.create('runtime','123|456','exact')),true);assert.throws(()=>c.admissionGate.tryEnter());assert.throws(()=>c.admissionGate.tryEnterControl());}));
test('malformed prepare quarantines ingress without exiting and deduplicates unchanged reports',async()=>fixture(async(c,s,root)=>{writeFileSync(join(root,DRAIN_MARKER_NAMES.prepare),'not a marker');const a=new AbortController();let errors=0,done=false;const task=runGatewayControlLoop(c,ports(s,e=>{if(e==='restart_drain_prepare_claim_failed')errors++;}),a.signal,time).then(r=>{done=true;return r;});try{await until(()=>errors>0);await sleep(12);assert.equal(done,false);assert.equal(errors,1);assert.throws(()=>c.admissionGate.tryEnter());const p=c.admissionGate.tryEnterControl();p.release();writeFileSync(join(root,DRAIN_MARKER_NAMES.stop),'stop');assert.equal((await task).kind,'Shutdown');}finally{a.abort();await task;}}));
test('foreign prepare cannot replace existing exact seal',async()=>fixture(async(c,s,root)=>{const existing=DrainFenceKey.create('existing','42|99','old');c.admissionGate.seal(existing);writeFileSync(join(root,DRAIN_MARKER_NAMES.prepare),'version=1\nruntime_id=foreign\nprocess_identity=42|99\nnonce=foreign\n');const a=new AbortController();let errors=0;const task=runGatewayControlLoop(c,ports(s,e=>{if(e==='restart_drain_prepare_claim_failed')errors++;}),a.signal,time);try{await until(()=>errors===1);assert.equal(c.admissionGate.isDrainedFor(existing),true);a.abort();assert.equal((await task).kind,'Shutdown');assert.equal(c.admissionGate.isDrainedFor(existing),true);}finally{a.abort();await task;}}));
test('stop marker wins over exact prepare without claiming or sealing it',async()=>fixture(async(c,s,root)=>{writeFileSync(join(root,DRAIN_MARKER_NAMES.stop),'stop');writeFileSync(join(root,DRAIN_MARKER_NAMES.prepare),'version=1\nruntime_id=runtime\nprocess_identity=123|456\nnonce=exact\n');const r=await runGatewayControlLoop(c,ports(s),new AbortController().signal,time);assert.equal(r.kind,'Shutdown');assert.equal(c.admissionGate.isSealed(),false);}));
test('one control loop per owner; abort closes delayed tick and permits later fresh owner invocation',async()=>fixture(async(c,s)=>{const a=new AbortController(),task=runGatewayControlLoop(c,ports(s),a.signal,time);try{await assert.rejects(runGatewayControlLoop(c,ports(s),new AbortController().signal,time),/already active/);a.abort();assert.equal((await task).kind,'Shutdown');const b=new AbortController();b.abort();assert.equal((await runGatewayControlLoop(c,ports(s),b.signal,time)).kind,'Shutdown');}finally{a.abort();await task;}}));
test('report failure propagates after quarantine and keeps gate sealed',async()=>fixture(async(c,s,root)=>{writeFileSync(join(root,DRAIN_MARKER_NAMES.prepare),'malformed');const sentinel={report:true};await assert.rejects(runGatewayControlLoop(c,ports(s,()=>{throw sentinel;}),new AbortController().signal,time),e=>e===sentinel);assert.equal(c.admissionGate.isSealed(),true);}));
test('active port getter is rejected before marker access',async()=>fixture(async(c,s)=>{let reads=0;const p=ports(s);Object.defineProperty(p,'inspect',{get(){reads++;return async()=>({kind:'Ready'});}});await assert.rejects(runGatewayControlLoop(c,p,new AbortController().signal,time),TypeError);assert.equal(reads,0);assert.equal(c.admissionGate.isSealed(),false);}));
