import assert from 'node:assert/strict';import {test} from 'node:test';import {setImmediate as tick} from 'node:timers/promises';
import {GatewayIdentityTracker} from '../../../src/discord/gateway/identity.ts';import {guardGatewayIdentity as guard,RuntimeIdentityGuardCleanupError} from '../../../src/runtime/discord-runtime/identity-guard.ts';import {RuntimeGatewayIdentityConflictError} from '../../../src/runtime/discord-runtime/identity-wait.ts';import {RuntimeTypedIngressError} from '../../../src/runtime/discord-runtime/receive-error-consumer.ts';
function fixture(){const tracker=new GatewayIdentityTracker(),conflict=tracker.subscribeConflict(),shutdown=new AbortController(),force=new AbortController();return {tracker,conflict,shutdown,force,close:()=>{tracker.close();conflict.dispose();}};}
const waiting=(signal:AbortSignal)=>new Promise<void>((_r,j)=>{signal.throwIfAborted();signal.addEventListener('abort',()=>j(signal.reason),{once:true});});
test('guard returns completed undefined distinctly from stopped',async()=>{const f=fixture();try{assert.deepEqual(await guard(async()=>undefined,f.conflict,f.shutdown.signal,f.force.signal),{completed:true,value:undefined});f.shutdown.abort();let calls=0;assert.deepEqual(await guard(async()=>{calls++;},f.conflict,f.shutdown.signal,f.force.signal),{completed:false});assert.equal(calls,0);}finally{f.close();}});
test('existing conflict prevents operation start',async()=>{const f=fixture();try{f.tracker.observe({userId:1n,applicationId:2n});f.tracker.observe({userId:3n,applicationId:4n});let calls=0;await assert.rejects(guard(async()=>{calls++;},f.conflict,f.shutdown.signal,f.force.signal),e=>e instanceof RuntimeGatewayIdentityConflictError);assert.equal(calls,0);}finally{f.close();}});
test('shutdown joins actual asynchronous finally cleanup before returning',async()=>{const f=fixture();let release!:()=>void,cleaned=false;const cleanup=new Promise<void>(r=>{release=r;});try{const pending=guard(async signal=>{try{await waiting(signal);}finally{await cleanup;cleaned=true;}},f.conflict,f.shutdown.signal,f.force.signal);await tick();f.shutdown.abort();let settled=false;void pending.then(()=>{settled=true;});await tick();assert.equal(settled,false);release();assert.deepEqual(await pending,{completed:false});assert.equal(cleaned,true);const next=f.conflict.changed();f.tracker.observe({userId:1n,applicationId:2n});f.tracker.observe({userId:3n,applicationId:4n});assert.notEqual(await next,null);}finally{release();f.close();}});
test('conflict during operation aborts and joins it before reporting conflict',async()=>{const f=fixture();let cleaned=false;try{const pending=guard(async signal=>{try{await waiting(signal);}finally{cleaned=true;}},f.conflict,f.shutdown.signal,f.force.signal),rejected=assert.rejects(pending,e=>e instanceof RuntimeGatewayIdentityConflictError);await tick();f.tracker.observe({userId:1n,applicationId:2n});f.tracker.observe({userId:3n,applicationId:4n});await rejected;assert.equal(cleaned,true);}finally{f.close();}});
test('force cancellation preserves exact reason after joining operation',async()=>{const f=fixture(),reason=new Error('force');try{const pending=guard(waiting,f.conflict,f.shutdown.signal,f.force.signal),rejected=assert.rejects(pending,e=>e===reason);await tick();f.force.abort(reason);await rejected;}finally{f.close();}});
test('operation error preserves identity and borrowed conflict read remains usable',async()=>{const f=fixture(),error=new Error('operation');try{await assert.rejects(guard(async()=>{throw error;},f.conflict,f.shutdown.signal,f.force.signal),e=>e===error);const next=f.conflict.changed();f.tracker.observe({userId:1n,applicationId:2n});f.tracker.observe({userId:3n,applicationId:4n});assert.notEqual(await next,null);}finally{f.close();}});
test('distinct cleanup error is retained alongside primary conflict',async()=>{const f=fixture(),cleanup=new Error('cleanup');try{const pending=guard(async signal=>{try{await waiting(signal);}finally{throw cleanup;}},f.conflict,f.shutdown.signal,f.force.signal),rejected=assert.rejects(pending,e=>e instanceof RuntimeIdentityGuardCleanupError&&e.primary instanceof RuntimeGatewayIdentityConflictError&&e.cleanupError===cleanup);await tick();f.tracker.observe({userId:1n,applicationId:2n});f.tracker.observe({userId:3n,applicationId:4n});await rejected;}finally{f.close();}});
test('closed conflict channel prevents first operation poll',async()=>{const f=fixture();try{f.tracker.close();let calls=0;await assert.rejects(guard(async()=>{calls++;},f.conflict,f.shutdown.signal,f.force.signal),e=>e instanceof RuntimeTypedIngressError);assert.equal(calls,0);}finally{f.close();}});
test('conflict arriving before deferred first poll is one primary error, not cleanup failure',async()=>{const f=fixture();try{let calls=0;const pending=guard(async()=>{calls++;},f.conflict,f.shutdown.signal,f.force.signal),rejected=assert.rejects(pending,e=>e instanceof RuntimeGatewayIdentityConflictError);f.tracker.observe({userId:1n,applicationId:2n});f.tracker.observe({userId:3n,applicationId:4n});await rejected;assert.equal(calls,0);}finally{f.close();}});
test('conflict-channel closure wins over simultaneous operation completion',async()=>{const f=fixture();let finish!:()=>void;try{const pending=guard(()=>new Promise<void>(r=>{finish=r;}),f.conflict,f.shutdown.signal,f.force.signal),rejected=assert.rejects(pending,e=>e instanceof RuntimeTypedIngressError&&e.lane==='identity-conflict');await tick();f.tracker.close();finish();await rejected;}finally{f.close();}});
test('same-turn completed operation cannot bypass subsequently closed conflict hint',async()=>{const f=fixture();let finish!:()=>void;try{const pending=guard(()=>new Promise<void>(r=>{finish=r;}),f.conflict,f.shutdown.signal,f.force.signal),rejected=assert.rejects(pending,e=>e instanceof RuntimeTypedIngressError);await tick();finish();f.tracker.close();await rejected;}finally{f.close();}});
test('completed operation is not spuriously aborted after its result was selected',async()=>{const f=fixture();let aborts=0;try{assert.deepEqual(await guard(async signal=>{signal.addEventListener('abort',()=>{aborts++;},{once:true});return 7;},f.conflict,f.shutdown.signal,f.force.signal),{completed:true,value:7});assert.equal(aborts,0);}finally{f.close();}});
