import assert from 'node:assert/strict';import {test} from 'node:test';import {setImmediate as tick} from 'node:timers/promises';
import {GatewayIdentityTracker,type GatewayIdentity,type GatewayIdentityConflict,type GatewayStateReceiver} from '../../../src/discord/gateway/identity.ts';
import {BroadcastClosedError,BroadcastLaggedError} from '../../../src/app-server/broadcast.ts';
import {waitForGatewayIdentity as wait,RuntimeGatewayIdentityConflictError} from '../../../src/runtime/discord-runtime/identity-wait.ts';
import {RuntimeTypedIngressError} from '../../../src/runtime/discord-runtime/receive-error-consumer.ts';
function fixture(){const tracker=new GatewayIdentityTracker(),identity=tracker.subscribeIdentity(),conflict=tracker.subscribeConflict(),shutdown=new AbortController(),force=new AbortController();return {tracker,identity,conflict,shutdown,force,start:()=>wait(identity,conflict,shutdown.signal,force.signal),close:()=>{tracker.close();identity.dispose();conflict.dispose();}};}
test('identity wait remains pending until actual ready and leaves borrowed subscriptions usable',async()=>{const f=fixture();try{let settled=false;const pending=f.start().then(v=>{settled=true;return v;});await tick();assert.equal(settled,false);f.tracker.observe({userId:11n,applicationId:22n});assert.deepEqual(await pending,{userId:11n,applicationId:22n});const changed=f.conflict.changed();f.tracker.observe({userId:33n,applicationId:44n});assert.deepEqual((await changed)?.observed,{userId:33n,applicationId:44n});}finally{f.close();}});
test('sticky conflict beats stale identity before any hint is awaited',async()=>{const f=fixture();try{f.tracker.observe({userId:1n,applicationId:2n});f.tracker.observe({userId:3n,applicationId:4n});await assert.rejects(f.start(),e=>e instanceof RuntimeGatewayIdentityConflictError&&e.conflict===f.conflict.snapshot());}finally{f.close();}});
test('shutdown beats already-present conflict and identity',async()=>{const f=fixture();try{f.tracker.observe({userId:1n,applicationId:2n});f.tracker.observe({userId:3n,applicationId:4n});f.shutdown.abort();assert.equal(await f.start(),null);}finally{f.close();}});
test('shutdown joins both pending hint reads, allowing subsequent reuse',async()=>{const f=fixture();try{const pending=f.start();await tick();f.shutdown.abort();assert.equal(await pending,null);const next=f.identity.changed();f.tracker.observe({userId:1n,applicationId:2n});assert.deepEqual(await next,{userId:1n,applicationId:2n});}finally{f.close();}});
test('simultaneous ready and conflict never return the stale established identity',async()=>{const f=fixture();try{const pending=f.start(),rejected=assert.rejects(pending,e=>e instanceof RuntimeGatewayIdentityConflictError);await tick();f.tracker.observe({userId:1n,applicationId:2n});f.tracker.observe({userId:3n,applicationId:4n});await rejected;}finally{f.close();}});
test('closed conflict notification wins over simultaneous closed identity',async()=>{const f=fixture();try{const pending=f.start(),rejected=assert.rejects(pending,e=>e instanceof RuntimeTypedIngressError&&e.lane==='identity-conflict');await tick();f.tracker.close();await rejected;}finally{f.close();}});
test('force cancellation preserves reason and joins both borrowed reads',async()=>{const f=fixture(),reason=new Error('force');try{const pending=f.start(),rejected=assert.rejects(pending,e=>e===reason);await tick();f.force.abort(reason);await rejected;const next=f.identity.changed();f.tracker.observe({userId:1n,applicationId:2n});assert.deepEqual(await next,{userId:1n,applicationId:2n});}finally{f.close();}});
test('lagged hints retry from sticky snapshots without discarding valid identity',async()=>{const f=fixture();try{let calls=0;const identity:GatewayStateReceiver<GatewayIdentity|null>={...f.identity,changed:async signal=>{if(calls++===0)throw new BroadcastLaggedError(1n);return f.identity.changed(signal);}};const pending=wait(identity,f.conflict,f.shutdown.signal,f.force.signal);await tick();f.tracker.observe({userId:1n,applicationId:2n});assert.deepEqual(await pending,{userId:1n,applicationId:2n});assert.ok(calls>=2);}finally{f.close();}});
test('identity-only closure is distinguished from conflict closure',async()=>{const f=fixture();try{const identity:GatewayStateReceiver<GatewayIdentity|null>={...f.identity,changed:async()=>{throw new BroadcastClosedError();}};await assert.rejects(wait(identity,f.conflict,f.shutdown.signal,f.force.signal),e=>e instanceof RuntimeTypedIngressError&&e.lane==='identity');}finally{f.close();}});
