import assert from 'node:assert/strict';import {test} from 'node:test';import {setImmediate as tick} from 'node:timers/promises';
import {GatewayIngressLane} from '../../../src/discord/gateway/lane.ts';import {decodeGatewayInteraction} from '../../../src/discord/gateway/decoded-interaction.ts';import {runInteractionLane,RuntimeInteractionTagError,type OwnedInteractionIngress,type InteractionLane,type InteractionLaneHandler} from '../../../src/runtime/discord-runtime/interaction-lane.ts';import {RuntimeTypedIngressError} from '../../../src/runtime/discord-runtime/receive-error-consumer.ts';import {InteractionDispatchError} from '../../../src/runtime/discord-dispatch/errors.ts';
class Clock{time=0;waiting=new Set<{at:number;wake:()=>void}>();now=()=>this.time;sleepUntil=(at:number,signal:AbortSignal):Promise<void>=>{signal.throwIfAborted();if(at<=this.time)return Promise.resolve();return new Promise((resolve,reject)=>{const item={at,wake:()=>{clean();resolve();}},clean=()=>{this.waiting.delete(item);signal.removeEventListener('abort',abort);},abort=()=>{clean();reject(signal.reason);};this.waiting.add(item);signal.addEventListener('abort',abort,{once:true});});};advance(at:number){this.time=at;for(const item of [...this.waiting])if(item.at<=at)item.wake();}}
async function until(predicate:()=>boolean){for(let i=0;i<2000&&!predicate();i++)await tick();assert.equal(predicate(),true);}
const item=(id:number,tag:'Normal'|'Busy'|'Stopping'):OwnedInteractionIngress=>Object.freeze({sequence:BigInt(id),receivedAtMs:0,tag,event:decodeGatewayInteraction(JSON.stringify({application_id:'2',authorizing_integration_owners:{},id:String(id),token:`offline-${id}`,type:1}))});
function fixture(mode:InteractionLane){const lane=new GatewayIngressLane<OwnedInteractionIngress>(64),receiver=lane.receiver(),shutdown=new AbortController(),force=new AbortController(),clock=new Clock(),reports:unknown[]=[];return {lane,receiver,shutdown,force,clock,reports,start:(handler:InteractionLaneHandler)=>runInteractionLane(mode,receiver,handler,shutdown.signal,force.signal,{report:value=>{reports.push(value);},clock})};}
function probe(){let active=0,max=0;const started:bigint[]=[],finish=new Map<bigint,()=>void>();const handle:InteractionLaneHandler=(item,signal)=>new Promise<void>((resolve,reject)=>{active++;max=Math.max(max,active);started.push(item.sequence);let settled=false;const end=(error?:unknown)=>{if(settled)return;settled=true;active--;finish.delete(item.sequence);signal.removeEventListener('abort',abort);if(error===undefined)resolve();else reject(error);},abort=()=>end(signal.reason);signal.addEventListener('abort',abort,{once:true});finish.set(item.sequence,()=>end());});return {handle,started,finish,active:()=>active,max:()=>max};}
test('normal lane never starts more than sixteen active handlers',{timeout:5000},async()=>{const f=fixture('Normal'),p=probe();for(let i=1;i<=17;i++)f.lane.trySend(item(i,'Normal'));const run=f.start(p.handle);await until(()=>p.started.length===16);assert.equal(p.max(),16);p.finish.get(1n)!();await until(()=>p.started.length===17);assert.equal(p.max(),16);f.shutdown.abort();await run;assert.equal(p.active(),0);assert.equal(f.lane.trySend(item(18,'Normal')),'Closed');});
test('reserved four handlers progress independently of blocked normal sixteen',{timeout:5000},async()=>{const a=fixture('Normal'),b=fixture('Reserved'),normal=probe(),reserved=probe();for(let i=1;i<=17;i++)a.lane.trySend(item(i,'Normal'));for(let i=1;i<=5;i++)b.lane.trySend(item(i,'Busy'));const x=a.start(normal.handle),y=b.start(reserved.handle);await until(()=>normal.started.length===16&&reserved.started.length===4);reserved.finish.get(1n)!();await until(()=>reserved.started.length===5);assert.equal(reserved.max(),4);a.shutdown.abort();b.shutdown.abort();b.lane.close();for(const release of reserved.finish.values())release();await Promise.all([x,y]);assert.equal(normal.active(),0);});
test('wrong ready tag is rejected before any buffered handler is polled',async()=>{const f=fixture('Normal');f.lane.trySend(item(1,'Normal'));f.lane.trySend(item(2,'Busy'));let calls=0;await assert.rejects(f.start(async()=>{calls++;}),e=>e instanceof RuntimeInteractionTagError&&e.tag==='Busy');assert.equal(calls,0);assert.equal(f.receiver.length,0);});
test('reserved lane drains stopping item arriving after shutdown',{timeout:5000},async()=>{const f=fixture('Reserved'),p=probe();f.shutdown.abort();const run=f.start(p.handle);await tick();f.lane.trySend(item(40,'Stopping'));f.lane.close();await until(()=>p.started.length===1);p.finish.get(40n)!();await run;assert.equal(f.clock.waiting.size,0);});
test('reserved thirteen-second deadline cancels and joins actual handlers',{timeout:5000},async()=>{const f=fixture('Reserved'),p=probe();f.shutdown.abort();f.lane.trySend(item(1,'Stopping'));const run=f.start(p.handle),rejected=assert.rejects(run,e=>e instanceof RuntimeTypedIngressError&&e.kind==='DrainTimeout');await until(()=>p.started.length===1);f.clock.advance(13000);await rejected;assert.equal(p.active(),0);assert.equal(f.clock.waiting.size,0);});
test('event-local HTTP failures do not stop later events and tokens are redacted',{timeout:5000},async()=>{for(const mode of ['Normal','Reserved'] as const){const f=fixture(mode),seen:bigint[]=[];f.lane.trySend(item(1,mode==='Normal'?'Normal':'Stopping'));f.lane.trySend(item(2,mode==='Normal'?'Normal':'Stopping'));const run=f.start(async item=>{seen.push(item.sequence);if(item.sequence===1n)throw new InteractionDispatchError('Acknowledge','HTTP failed offline-1');});await until(()=>seen.length===2&&f.reports.length===1);assert.ok(!JSON.stringify(f.reports,(_k,v)=>typeof v==='bigint'?String(v):v).includes('offline-1'));f.shutdown.abort();if(mode==='Reserved')f.lane.close();await run;}});
test('state invariant error remains original fatal lane failure',async()=>{const f=fixture('Normal'),error=new InteractionDispatchError('ClaimState');f.lane.trySend(item(1,'Normal'));await assert.rejects(f.start(async()=>{throw error;}),e=>e===error);assert.equal(f.reports.length,0);});
test('unexpected input closure does not start queued lazy handlers',async()=>{const f=fixture('Normal');f.lane.trySend(item(1,'Normal'));f.lane.close();let calls=0;await assert.rejects(f.start(async()=>{calls++;}),e=>e instanceof RuntimeTypedIngressError&&e.kind==='Closed');assert.equal(calls,0);});
test('normal shutdown before first poll starts no handler and drops backlog',async()=>{const f=fixture('Normal');f.lane.trySend(item(1,'Normal'));f.shutdown.abort();let calls=0;await f.start(async()=>{calls++;});assert.equal(calls,0);assert.equal(f.receiver.length,0);});
test('forced cancellation keeps exact reason after all active jobs settle',{timeout:5000},async()=>{const f=fixture('Normal'),p=probe(),reason=new Error('force');f.lane.trySend(item(1,'Normal'));const run=f.start(p.handle),rejected=assert.rejects(run,e=>e===reason);await until(()=>p.started.length===1);f.force.abort(reason);await rejected;assert.equal(p.active(),0);});
test('receiver cleanup errors never skip cancellation/join of started operations',{timeout:5000},async()=>{const f=fixture('Normal'),p=probe(),closeError=new Error('close'),disposeError=new Error('dispose');f.lane.trySend(item(1,'Normal'));const receiver={...f.receiver,close(){throw closeError;},dispose(){f.receiver.dispose();throw disposeError;}},run=runInteractionLane('Normal',receiver,p.handle,f.shutdown.signal,f.force.signal,{report:()=>{},clock:f.clock}),rejected=assert.rejects(run,e=>e instanceof AggregateError&&e.errors.includes(closeError)&&e.errors.includes(disposeError));await until(()=>p.started.length===1);f.shutdown.abort();await rejected;assert.equal(p.active(),0);assert.equal(f.lane.trySend(item(2,'Normal')),'Closed');});
test('normal shutdown waits for actual asynchronous handler finally cleanup',{timeout:5000},async()=>{const f=fixture('Normal');f.lane.trySend(item(1,'Normal'));let release!:()=>void,started=false,cleaned=false;const cleanup=new Promise<void>(r=>{release=r;}),run=f.start(async(_item,signal)=>{started=true;try{await new Promise<void>((_r,j)=>signal.addEventListener('abort',()=>j(signal.reason),{once:true}));}finally{await cleanup;cleaned=true;}});await until(()=>started);f.shutdown.abort();let settled=false;void run.then(()=>{settled=true;});await tick();assert.equal(settled,false);assert.equal(cleaned,false);release();await run;assert.equal(cleaned,true);});
test('reserved deadline outranks a simultaneously available late item',async()=>{const f=fixture('Reserved');f.shutdown.abort();let calls=0;const run=f.start(async()=>{calls++;}),rejected=assert.rejects(run,e=>e instanceof RuntimeTypedIngressError&&e.kind==='DrainTimeout');await tick();f.lane.trySend(item(1,'Stopping'));f.clock.advance(13000);await rejected;assert.equal(calls,0);});
