import assert from 'node:assert/strict';
import {test} from 'node:test';
import {dirname,join} from 'node:path';
import {storeFixture} from '../../helpers/store-fixture.ts';
import {httpFixture} from '../../helpers/interaction-worker-fixture.ts';
import {asyncChoiceServer} from '../../helpers/async-choice-server.ts';
import {promptFixture,callPromptFixture} from '../../helpers/server-prompt-fixture.ts';
import {createGatewayMessageHandler,type MessageHandlerOptions} from '../../../src/runtime/discord-runtime/message-handler.ts';
import {runMessageConsumer} from '../../../src/runtime/discord-runtime/message-consumer.ts';
import {decodeGatewayMessage} from '../../../src/discord/gateway/decoded-message.ts';
import {GatewayIdentityTracker} from '../../../src/discord/gateway/identity.ts';
import {GatewayIngressLane} from '../../../src/discord/gateway/lane.ts';
import type {MessageIngress} from '../../../src/discord/gateway/ingress.ts';
import {InteractionAccessPolicy} from '../../../src/discord/interaction-access.ts';
import {SettingsTargetResolver} from '../../../src/runtime/settings-binding.ts';
import {BridgeState} from '../../../src/runtime/bridge-state.ts';
import {ControlTurnVerifier} from '../../../src/runtime/action-executor/control-turn.ts';
import {TargetLocks} from '../../../src/core/keyed-locks.ts';
import {AdmissionGate,DrainFenceKey} from '../../../src/admission/drain-gate.ts';
import {StateAccessFacade as state} from '../../../src/store/state-access-facade.ts';
import type {PortableResidentLifecycle} from '../../../src/app-server/portable-resident-lifecycle.ts';
import type {DiscordChannelClient} from '../../../src/discord/channel-client.ts';
import {RuntimeGatewayIdentityConflictError} from '../../../src/runtime/discord-runtime/identity-wait.ts';
const identity={userId:9n,applicationId:4n};
function message(content='!help',id=3){return decodeGatewayMessage(JSON.stringify({attachments:[],author:{id:'2',username:'u',discriminator:'0',bot:false},channel_id:'1',content,embeds:[],id:String(id),mention_everyone:false,mention_roles:[],mentions:[],pinned:false,timestamp:'2020-01-01T00:00:00+00:00',tts:false,type:0}));}
function options(path:string,server:PortableResidentLifecycle,http:DiscordChannelClient){const calls={execute:0,target:0,notify:0},reports:string[]=[],bridge=new BridgeState(join(dirname(path),'bridge.json')),gate=new AdmissionGate();const value:MessageHandlerOptions={context:{database:path,server,http,config:{attachmentsEnabled:true,attachmentMaxBytes:100n,attachmentTextInlineMaxBytes:100n},attachmentRoot:dirname(path),attachmentTransport:{async get(){assert.fail();}},attachmentReport:()=>{},controlVerifier:new ControlTurnVerifier(path,server,bridge,new TargetLocks()),services:{async targetThreadId(){calls.target++;return 't';},async executeWithIngressContext(){calls.execute++;return {text:'done',waitsForFinal:false,ui:null};},notifyDeliveryReady(){calls.notify++;}},now:()=>102},gate,classification:{enableMessageContent:true,plainAskMentionUserIds:new Set()},policy:new InteractionAccessPolicy({allowAllChannels:true,allowedChannelIds:[],allowedUserIds:[],mirroredChannelIds:[]}),resolver:new SettingsTargetResolver(join(dirname(path),'codex.sqlite'),path,bridge),report:code=>{reports.push(code);}};return {value,calls,reports,gate};}
function fixture(run:(path:string,server:PortableResidentLifecycle,http:DiscordChannelClient,seen:string[])=>Promise<void>){return storeFixture(path=>httpFixture((http,seen)=>asyncChoiceServer({},server=>run(path,server,http,seen))));}
test('actual message handler composes fresh policy, durable claim, execution and reply exactly once',()=>fixture(async(path,server,http,seen)=>{const f=options(path,server,http),handler=createGatewayMessageHandler(f.value),signal=new AbortController().signal;await handler(message(),identity,signal);await handler(message(),identity,signal);assert.equal(f.calls.execute,1);assert.equal(f.calls.notify,1);assert.deepEqual(seen,['POST']);assert.equal((await state.getIngress(path,'message:3'))!.confirmationDelivered,true);assert.deepEqual(f.reports,[]);}));
test('sealed runtime probes actual empty pending state and reports unavailable without durable execution',()=>fixture(async(path,server,http,seen)=>{const f=options(path,server,http),key=DrainFenceKey.create('runtime','1|2','worker');f.gate.seal(key);const handler=createGatewayMessageHandler(f.value);await handler(message('answer'),identity,new AbortController().signal);assert.equal(f.calls.target,1);assert.equal(f.calls.execute,0);assert.equal(await state.getIngress(path,'message:3'),null);assert.deepEqual(seen,['POST']);assert.deepEqual(f.reports,['on_message_error']);assert.equal(f.gate.isDrainedFor(key),true);}));
test('sealed runtime with native approval admits only pending reply and emits no business command',()=>promptFixture((path,server)=>httpFixture(async(http,seen)=>{const f=options(path,server,http),key=DrainFenceKey.create('runtime','1|2','worker');f.gate.seal(key);await createGatewayMessageHandler(f.value)(message('1'),identity,new AbortController().signal);assert.equal(f.calls.target,3);assert.equal(f.calls.execute,0);assert.equal(f.calls.notify,0);assert.deepEqual(await callPromptFixture(server,'answers'),[{id:'approval',result:{decision:'accept'}}]);assert.deepEqual(seen,['POST']);assert.equal(f.gate.isDrainedFor(key),true);}),{enableResponses:true}));
test('authorized emergency skips native pending probe and executes once with both drain gates closed',()=>fixture(async(path,server,http,seen)=>{const f=options(path,server,http),key=DrainFenceKey.create('runtime','1|2','worker');f.gate.seal(key);f.gate.closeControls(key);const handler=createGatewayMessageHandler(f.value);await handler(message('!force_restart'),identity,new AbortController().signal);await handler(message('!force_restart'),identity,new AbortController().signal);assert.equal(f.calls.target,0);assert.equal(f.calls.execute,1);assert.deepEqual(seen,['POST']);}));
test('self identity is ignored and no error receipt or ingress is produced',()=>fixture(async(path,server,http,seen)=>{const f=options(path,server,http);await createGatewayMessageHandler(f.value)(message(),{...identity,userId:2n},new AbortController().signal);assert.equal(f.calls.execute,0);assert.deepEqual(seen,[]);assert.deepEqual(f.reports,['ignored_message']);assert.equal(await state.isProcessedMessage(path,3n),false);}));
test('service and mention configuration are captured before handling and cannot be swapped later',()=>fixture(async(path,server,http,seen)=>{const f=options(path,server,http),handler=createGatewayMessageHandler(f.value);f.value.classification.plainAskMentionUserIds.add(77n);f.value.context.services.executeWithIngressContext=async()=>{throw Error('replacement must not run');};await handler(message('hello'),identity,new AbortController().signal);assert.equal(f.calls.execute,1);assert.deepEqual(seen,['POST']);}));
test('pre-aborted full handler creates no store or outbound request',()=>fixture(async(path,server,http,seen)=>{const f=options(path,server,http),abort=new AbortController(),reason=new Error('preabort');abort.abort(reason);await assert.rejects(createGatewayMessageHandler(f.value)(message(),identity,abort.signal),e=>e===reason);assert.equal(f.calls.execute,0);assert.equal(f.calls.target,0);assert.deepEqual(seen,[]);}));
async function consumerCase(conflictMode:boolean){await fixture(async(path,server,http,seen)=>{
 const f=options(path,server,http);let entered!:()=>void,cleanup!:()=>void,aborted!:()=>void;const started=new Promise<void>(r=>entered=r),cleaned=new Promise<void>(r=>cleanup=r),cancelled=new Promise<void>(r=>aborted=r);let done=false;
 f.value.context.services.executeWithIngressContext=async(_action,_actor,_key,signal)=>{entered();await new Promise<void>(r=>signal!.addEventListener('abort',()=>{aborted();r();},{once:true}));await cleaned;done=true;throw signal!.reason;};
 const lane=new GatewayIngressLane<MessageIngress>(4),receiver=lane.receiver(),tracker=new GatewayIdentityTracker(),identityRx=tracker.subscribeIdentity(),conflictRx=tracker.subscribeConflict(),shutdown=new AbortController(),force=new AbortController();tracker.observe(identity);lane.trySend({sequence:1n,event:message()});lane.trySend({sequence:2n,event:message('!help',4)});
 const pending=runMessageConsumer(receiver,identityRx,conflictRx,shutdown.signal,force.signal,createGatewayMessageHandler(f.value));const observed=conflictMode?assert.rejects(pending,RuntimeGatewayIdentityConflictError):pending;
 try{await started;if(conflictMode)tracker.observe({userId:90n,applicationId:40n});else shutdown.abort();await cancelled;assert.equal(done,false);cleanup();await observed;assert.equal(done,true);assert.deepEqual(seen,[]);assert.equal((await state.getIngress(path,'message:3'))!.state,'held');assert.equal(await state.getIngress(path,'message:4'),null);assert.equal(receiver.length,0);assert.deepEqual(f.reports,[]);const key=DrainFenceKey.create('runtime','1|2','worker');f.gate.seal(key);assert.equal(f.gate.isDrainedFor(key),true);}
 finally{cleanup();shutdown.abort();tracker.close();identityRx.dispose();conflictRx.dispose();}
 });}
test('real normal message consumer shutdown cancels composed handler and joins custody before return',()=>consumerCase(false));
test('identity conflict cancels active composed handler and prevents the next queued message',()=>consumerCase(true));
