import assert from 'node:assert/strict';import {test} from 'node:test';import {setImmediate as tick} from 'node:timers/promises';
import {GatewayIngressLane} from '../../../src/discord/gateway/lane.ts';import type {MessageIngress} from '../../../src/discord/gateway/ingress.ts';import {GatewayIdentityTracker} from '../../../src/discord/gateway/identity.ts';import {decodeGatewayMessage} from '../../../src/discord/gateway/decoded-message.ts';import {runMessageConsumer,type GatewayMessageHandler} from '../../../src/runtime/discord-runtime/message-consumer.ts';import {RuntimeGatewayIdentityConflictError} from '../../../src/runtime/discord-runtime/identity-wait.ts';import {RuntimeTypedIngressError} from '../../../src/runtime/discord-runtime/receive-error-consumer.ts';
const message=(id='1')=>decodeGatewayMessage(JSON.stringify({attachments:[],author:{id:'3',username:'u',discriminator:'1'},channel_id:'7',content:'hello',embeds:[],id,type:0,mention_everyone:false,mention_roles:[],mentions:[],pinned:false,timestamp:'2020-02-02T02:02:02.020000+00:00',tts:false}));
async function turns(){for(let i=0;i<10;i++)await tick();}
function fixture(){const lane=new GatewayIngressLane<MessageIngress>(8),receiver=lane.receiver(),tracker=new GatewayIdentityTracker(),identity=tracker.subscribeIdentity(),conflict=tracker.subscribeConflict(),shutdown=new AbortController(),force=new AbortController();return {lane,receiver,tracker,identity,conflict,shutdown,force,start:(handler:GatewayMessageHandler)=>runMessageConsumer(receiver,identity,conflict,shutdown.signal,force.signal,handler),send:(id='1')=>lane.trySend(Object.freeze({sequence:BigInt(id),event:message(id)})),ready:()=>tracker.observe({userId:11n,applicationId:22n}),close:()=>{shutdown.abort();tracker.close();identity.dispose();conflict.dispose();}};}
test('buffered message waits for identity and passes exact bot/application context',async()=>{const f=fixture(),seen:unknown[]=[];try{f.send();const pending=f.start(async(event,identity)=>{seen.push([event.id,identity]);});await turns();assert.equal(seen.length,0);f.ready();await turns();assert.deepEqual(seen,[[1n,{userId:11n,applicationId:22n}]]);f.shutdown.abort();await pending;assert.equal(f.send('2'),'Closed');}finally{f.close();}});
test('shutdown before READY disposes queued messages without processing',async()=>{const f=fixture();try{f.send();let calls=0;const pending=f.start(async()=>{calls++;});f.shutdown.abort();await pending;assert.equal(calls,0);assert.equal(f.receiver.length,0);}finally{f.close();}});
test('each lane serializes handlers and does not begin second before first settles',async()=>{const f=fixture();let release!:()=>void;const first=new Promise<void>(r=>{release=r;}),seen:bigint[]=[];try{f.ready();f.send();f.send('2');const pending=f.start(async event=>{seen.push(event.id);if(event.id===1n)await first;});await turns();assert.deepEqual(seen,[1n]);release();await turns();assert.deepEqual(seen,[1n,2n]);f.shutdown.abort();await pending;}finally{release();f.close();}});
test('shutdown during processing cancels and joins real asynchronous cleanup',async()=>{const f=fixture();let release!:()=>void,aborted=false,cleaned=false;const cleanup=new Promise<void>(r=>{release=r;});try{f.ready();f.send();f.send('2');let calls=0;const pending=f.start(async(_event,_identity,signal)=>{calls++;try{await new Promise<void>((_r,j)=>signal.addEventListener('abort',()=>{aborted=true;j(signal.reason);},{once:true}));}finally{await cleanup;cleaned=true;}});await turns();f.shutdown.abort();await turns();assert.equal(aborted,true);assert.equal(cleaned,false);release();await pending;assert.equal(cleaned,true);assert.equal(calls,1);assert.equal(f.receiver.length,0);}finally{release();f.close();}});
test('conflicting identity stops before queued message handler',async()=>{const f=fixture();try{f.ready();f.tracker.observe({userId:33n,applicationId:44n});f.send();let calls=0;await assert.rejects(f.start(async()=>{calls++;}),e=>e instanceof RuntimeGatewayIdentityConflictError);assert.equal(calls,0);assert.equal(f.receiver.length,0);}finally{f.close();}});
test('unexpected message closure remains typed ingress domain error',async()=>{const f=fixture();try{f.ready();f.lane.close();await assert.rejects(f.start(async()=>{}),e=>e instanceof RuntimeTypedIngressError&&e.lane==='message'&&e.kind==='Closed');}finally{f.close();}});
test('handler failure preserves identity, stops next message and disposes lane',async()=>{const f=fixture(),error=new Error('handler');try{f.ready();f.send();f.send('2');let calls=0;await assert.rejects(f.start(async()=>{calls++;throw error;}),e=>e===error);assert.equal(calls,1);assert.equal(f.receiver.length,0);}finally{f.close();}});
test('separate normal and emergency consumers do not block each other',async()=>{const normal=fixture(),emergency=fixture();let release!:()=>void;const held=new Promise<void>(r=>{release=r;});let seen=false;try{normal.ready();emergency.ready();normal.send();emergency.send();const a=normal.start(async()=>{await held;}),b=emergency.start(async()=>{seen=true;});await turns();assert.equal(seen,true);release();normal.shutdown.abort();emergency.shutdown.abort();await Promise.all([a,b]);}finally{release();normal.close();emergency.close();}});
test('unbranded synthetic payload cannot reach handler',async()=>{const f=fixture();try{f.ready();f.lane.trySend({sequence:1n,event:{} as never});let calls=0;await assert.rejects(f.start(async()=>{calls++;}),/completely decoded/);assert.equal(calls,0);}finally{f.close();}});
test('busy message stream yields and preserves forced cancellation reason',{timeout:3000},async()=>{const f=fixture(),reason=new Error('force');try{f.ready();f.send();let calls=0;const pending=f.start(async()=>{calls++;f.send();}),rejected=assert.rejects(pending,e=>e===reason);setImmediate(()=>f.force.abort(reason));await rejected;assert.ok(calls>0&&calls<=64);assert.equal(f.receiver.length,0);}finally{f.close();}});
