import assert from 'node:assert/strict';import {test} from 'node:test';import {createServer,type RequestListener} from 'node:http';import {setImmediate as tick} from 'node:timers/promises';
import {DiscordChannelClient} from '../../../src/discord/channel-client.ts';import {GatewayIdentityTracker} from '../../../src/discord/gateway/identity.ts';import {readyHttpPort} from '../../../src/runtime/discord-runtime/ready-http-port.ts';import {runReadySetup} from '../../../src/runtime/discord-runtime/ready-setup.ts';import {idempotentMessageRequest} from '../../../src/discord/idempotent-message.ts';import {messageNonce} from '../../../src/discord/message-nonce.ts';
const message={attachments:[],author:{id:'1',username:'fixture',discriminator:'0'},channel_id:'91',content:'',embeds:[],id:'123',type:0,mention_everyone:false,mention_roles:[],mentions:[],pinned:false,timestamp:'2020-01-01T00:00:00+00:00',tts:false};
async function until(predicate:()=>boolean){for(let i=0;i<2000&&!predicate();i++)await tick();assert.equal(predicate(),true);}
async function fixture(handler:RequestListener,run:(client:DiscordChannelClient)=>Promise<void>){const server=createServer(handler);await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const client=await DiscordChannelClient.create({token:null,testOrigin:`http://127.0.0.1:${(server.address() as {port:number}).port}/api/v10/`,report:()=>{}});try{await run(client);}finally{await client.close();server.closeAllConnections();await new Promise<void>((r,j)=>server.close(e=>e?j(e):r()));}}
test('Ready identity lifecycle performs actual PUT registration and nonce-enforced POST on shared client',{timeout:5000},async()=>{const seen:{method:string;path:string;body:string}[]=[];await fixture((req,res)=>{assert.equal(req.headers.authorization,undefined);let body='';req.on('data',b=>body+=b);req.on('end',()=>{seen.push({method:req.method!,path:req.url!,body});res.end(req.method==='PUT'?'[]':JSON.stringify(message));});},async client=>{const tracker=new GatewayIdentityTracker(),identity=tracker.subscribeIdentity(),conflict=tracker.subscribeConflict(),shutdown=new AbortController(),force=new AbortController();try{const pending=runReadySetup(identity,conflict,shutdown.signal,force.signal,{port:readyHttpPort(client),guildId:7n,qaCommands:false,startupNotify:true,startupChannelId:91n,report:()=>{},bootKey:()=> 'test-boot'});await tick();assert.equal(seen.length,0);tracker.observe({userId:11n,applicationId:22n});await until(()=>seen.length===2&&client.activeRequests===0);assert.deepEqual(new Set(seen.map(x=>x.method+' '+x.path)),new Set(['PUT /api/v10/applications/22/guilds/7/commands','POST /api/v10/channels/91/messages']));const body=seen.find(x=>x.method==='POST')!.body;assert.ok(body.includes(`"nonce":${messageNonce('runtime/startup-notice/v1',91n,'test-boot',0)}`));assert.equal(JSON.parse(body).enforce_nonce,true);shutdown.abort();await pending;assert.equal(client.activeRequests,0);await client.close();assert.equal(client.ownedSockets,0);}finally{shutdown.abort();tracker.close();identity.dispose();conflict.dispose();}});});
test('source notice ignores success body while durable receipt sender still requires full model',{timeout:5000},async()=>{await fixture((_req,res)=>res.end('{"id":"123"}'),async client=>{await readyHttpPort(client).sendNotice(91n,'notice','domain','key',0,new AbortController().signal);await assert.rejects(client.sendValidated(idempotentMessageRequest(91n,'receipt','domain','key',0)),/receipt decode failed/);assert.equal(client.activeRequests,0);});});
test('pre-aborted notice preserves reason and opens no HTTP request',{timeout:5000},async()=>{let calls=0;await fixture((_req,res)=>{calls++;res.end(JSON.stringify(message));},async client=>{const abort=new AbortController(),reason=new Error('preabort');abort.abort(reason);await assert.rejects(readyHttpPort(client).sendNotice(91n,'notice','domain','key',0,abort.signal),e=>e===reason);assert.equal(calls,0);});});
test('notice cancellation joins an actual pending request without closing shared client',{timeout:5000},async()=>{let calls=0;await fixture((_req,res)=>{calls++;if(calls>1)res.end(JSON.stringify(message));},async client=>{const port=readyHttpPort(client),abort=new AbortController(),reason=new Error('notice cancel'),pending=port.sendNotice(91n,'notice','domain','key',0,abort.signal),rejected=assert.rejects(pending,e=>e===reason);await until(()=>calls===1);abort.abort(reason);await rejected;assert.equal(client.activeRequests,0);await port.sendNotice(91n,'notice','domain','key',0,new AbortController().signal);assert.equal(calls,2);});});
test('port captures owner methods and rejects forged client without invoking getters',{timeout:5000},async()=>{await fixture((_req,res)=>res.end(JSON.stringify(message)),async client=>{const port=readyHttpPort(client);Object.defineProperty(client,'sendWithoutReceipt',{value:()=>{throw new Error('replacement');}});await port.sendNotice(91n,'notice','domain','key',0,new AbortController().signal);assert.throws(()=>readyHttpPort(Object.create(DiscordChannelClient.prototype)));assert.throws(()=>port.register(1n,{kind:'Other'} as never,false,new AbortController().signal));});});
test('source notice releases stalled success body without receipt decoding',{timeout:5000},async()=>{await fixture((_req,res)=>{res.writeHead(200);res.write('{');},async client=>{await readyHttpPort(client).sendNotice(91n,'notice','domain','key',0,AbortSignal.timeout(1000));assert.equal(client.activeRequests,0);await client.close();assert.equal(client.ownedSockets,0);});});
