import assert from 'node:assert/strict';import {test} from 'node:test';import {setImmediate as tick} from 'node:timers/promises';
import {GatewayIdentityTracker} from '../../../src/discord/gateway/identity.ts';import {runReadySetup,readyRetryDelay,type ReadySetupOptions} from '../../../src/runtime/discord-runtime/ready-setup.ts';import {RuntimeGatewayIdentityConflictError} from '../../../src/runtime/discord-runtime/identity-wait.ts';
class Clock{time=0;waiting=new Set<{at:number;wake:()=>void}>();now=()=>this.time;sleepUntil=(at:number,signal:AbortSignal):Promise<void>=>{signal.throwIfAborted();if(at<=this.time)return Promise.resolve();return new Promise((resolve,reject)=>{const item={at,wake:()=>{clean();resolve();}},clean=()=>{this.waiting.delete(item);signal.removeEventListener('abort',abort);},abort=()=>{clean();reject(signal.reason);};this.waiting.add(item);signal.addEventListener('abort',abort,{once:true});});};advance(at:number){this.time=at;for(const item of [...this.waiting])if(item.at<=at)item.wake();}}
async function turns(){for(let i=0;i<8;i++)await tick();}
function fixture(){const tracker=new GatewayIdentityTracker(),identity=tracker.subscribeIdentity(),conflict=tracker.subscribeConflict(),shutdown=new AbortController(),force=new AbortController(),clock=new Clock(),registrations:unknown[][]=[],notices:unknown[][]=[],reports:unknown[][]=[];let keys=0;const options:ReadySetupOptions={port:{register:async(...a)=>{registrations.push(a);},sendNotice:async(...a)=>{notices.push(a);}},guildId:null,qaCommands:false,startupNotify:true,startupChannelId:91n,report:(...a)=>{reports.push(a);},clock,bootKey:()=>{keys++;return 'fixed-boot';}};return {tracker,identity,conflict,shutdown,force,clock,registrations,notices,reports,options,keys:()=>keys,start:()=>runReadySetup(identity,conflict,shutdown.signal,force.signal,options),close:()=>{tracker.close();identity.dispose();conflict.dispose();}};}
test('retry schedule saturates independently at thirty seconds',()=>{assert.deepEqual([0,1,2,3,4,5,6,100].map(readyRetryDelay),[1000,2000,4000,8000,16000,30000,30000,30000]);assert.equal(readyRetryDelay(0),1000);});
test('Ready setup waits for identity then registers and sends exact single boot notice',async()=>{const f=fixture();try{const pending=f.start();await turns();assert.equal(f.registrations.length,0);f.tracker.observe({userId:11n,applicationId:22n});await turns();assert.equal(f.registrations.length,1);assert.deepEqual(f.registrations[0]!.slice(0,3),[22n,{kind:'Global'},false]);assert.deepEqual(f.notices[0]!.slice(0,5),[91n,'Codex Discord Rust runtime started.','runtime/startup-notice/v1','fixed-boot',0]);assert.equal(f.keys(),1);f.tracker.observe({userId:11n,applicationId:22n});await turns();assert.equal(f.notices.length,1);f.shutdown.abort();await pending;assert.equal(f.clock.waiting.size,0);}finally{f.close();}});
test('disabled or absent startup channel creates no key and no send',async()=>{for(const variant of [{startupNotify:false},{startupChannelId:null}]){const f=fixture();Object.assign(f.options,variant,{guildId:8n,qaCommands:true});try{f.tracker.observe({userId:1n,applicationId:2n});const pending=f.start();await turns();assert.equal(f.notices.length,0);assert.equal(f.keys(),0);assert.deepEqual(f.registrations[0]!.slice(0,3),[2n,{kind:'Guild',guildId:8n},true]);f.shutdown.abort();await pending;}finally{f.close();}}});
test('registration and notice failures have independent retry indices and stable boot key',async()=>{const f=fixture();let registrations=0,notices=0;const seenKeys:string[]=[];f.options.port.register=async()=>{if(++registrations<3)throw new Error('register');};f.options.port.sendNotice=async(_c,_t,_d,key)=>{seenKeys.push(key);if(++notices<2)throw new Error('notice');};try{f.tracker.observe({userId:1n,applicationId:2n});const pending=f.start();await turns();assert.deepEqual([registrations,notices],[1,1]);f.clock.advance(1000);await turns();assert.deepEqual([registrations,notices],[2,2]);f.clock.advance(3000);await turns();assert.deepEqual([registrations,notices],[3,2]);assert.deepEqual(seenKeys,['fixed-boot','fixed-boot']);assert.equal(f.keys(),1);f.shutdown.abort();await pending;}finally{f.close();}});
test('conflict after successful setup still terminates Ready lifecycle',async()=>{const f=fixture();try{f.tracker.observe({userId:1n,applicationId:2n});const pending=f.start(),rejected=assert.rejects(pending,e=>e instanceof RuntimeGatewayIdentityConflictError);await turns();f.tracker.observe({userId:3n,applicationId:4n});await rejected;}finally{f.close();}});
test('shutdown during retry joins all timers and performs no later retries',async()=>{const f=fixture();let calls=0;f.options.port.register=async()=>{calls++;throw new Error('retry');};try{f.tracker.observe({userId:1n,applicationId:2n});const pending=f.start();await turns();assert.equal(f.clock.waiting.size,1);f.shutdown.abort();await pending;f.clock.advance(100000);await turns();assert.equal(calls,1);assert.equal(f.clock.waiting.size,0);}finally{f.close();}});
test('setup failure cancels and joins sibling native cleanup before escaping',async()=>{const f=fixture(),error=new Error('logger failed');let release!:()=>void,aborted=false,settled=false;const cleanup=new Promise<void>(r=>{release=r;});f.options.port.register=async(_a,_s,_q,signal)=>{try{await new Promise<void>((_r,j)=>signal.addEventListener('abort',()=>{aborted=true;j(signal.reason);},{once:true}));}finally{await cleanup;}};f.options.port.sendNotice=async()=>{throw new Error('notice failure');};Object.assign(f.options,{report:(kind:string)=>{if(kind==='notice')throw error;}});try{f.tracker.observe({userId:1n,applicationId:2n});const pending=f.start(),rejected=assert.rejects(pending,e=>e===error);void rejected.then(()=>{settled=true;});await turns();assert.equal(aborted,true);assert.equal(settled,false);release();await rejected;}finally{release();f.close();}});
test('shutdown before first READY opens neither effect branch',async()=>{const f=fixture();try{const pending=f.start();f.shutdown.abort();await pending;assert.equal(f.registrations.length,0);assert.equal(f.notices.length,0);assert.equal(f.keys(),0);}finally{f.close();}});
