import assert from 'node:assert/strict';import {test} from 'node:test';import {setImmediate as tick} from 'node:timers/promises';
import {GatewayIngressLane} from '../../../src/discord/gateway/lane.ts';import type {GatewayReceiveError} from '../../../src/discord/gateway/ingress.ts';
import {runReceiveErrorConsumer as run,RuntimeTypedIngressError,RECEIVE_ERROR_DRAIN_TIMEOUT_MS} from '../../../src/runtime/discord-runtime/receive-error-consumer.ts';
class Clock{time=0;waiting=new Set<{at:number;wake:()=>void}>();now=()=>this.time;sleepUntil=(at:number,signal:AbortSignal):Promise<void>=>{signal.throwIfAborted();if(at<=this.time)return Promise.resolve();return new Promise((resolve,reject)=>{const item={at,wake:()=>{clean();resolve();}},clean=()=>{this.waiting.delete(item);signal.removeEventListener('abort',abort);},abort=()=>{clean();reject(signal.reason);};this.waiting.add(item);signal.addEventListener('abort',abort,{once:true});});};advance(at:number){this.time=at;for(const item of [...this.waiting])if(item.at<=at)item.wake();}}
function fixture(){const lane=new GatewayIngressLane<GatewayReceiveError>(16),receiver=lane.receiver(),shutdown=new AbortController(),force=new AbortController(),clock=new Clock(),items:GatewayReceiveError[]=[];return {lane,receiver,shutdown,force,clock,items,start:()=>run(receiver,shutdown.signal,force.signal,item=>{items.push(item);},clock)};}
test('late diagnostic after shutdown is drained before lane closure',async()=>{const f=fixture();f.shutdown.abort();const pending=f.start();await tick();f.lane.trySend({shard:7,message:'decode-7'});f.lane.close();assert.deepEqual(await pending,{ok:true});assert.deepEqual(f.items,[{shard:7,message:'decode-7'}]);assert.equal(f.clock.waiting.size,0);});
test('unexpected lane closure is a distinct domain error',async()=>{const f=fixture();f.lane.close();const result=await f.start();assert.ok(!result.ok);assert.ok(result.error instanceof RuntimeTypedIngressError);assert.equal(result.error.kind,'Closed');});
test('shutdown drain stops at exactly thirteen seconds and disposes the owned receiver',async()=>{const f=fixture();f.shutdown.abort();const pending=f.start();await tick();f.clock.advance(12999);await tick();assert.equal(f.clock.waiting.size,1);f.clock.advance(RECEIVE_ERROR_DRAIN_TIMEOUT_MS);const result=await pending;assert.ok(!result.ok);assert.ok(result.error instanceof RuntimeTypedIngressError);assert.equal(result.error.kind,'DrainTimeout');assert.equal(f.lane.trySend({shard:0,message:'late'}),'Closed');assert.equal(f.clock.waiting.size,0);});
test('shutdown wins over concurrent lane closure and preserves already-read item',async()=>{const f=fixture(),pending=f.start();f.lane.trySend({shard:1,message:'item'});f.shutdown.abort();f.lane.close();assert.deepEqual(await pending,{ok:true});assert.equal(f.items.length,1);});
test('expired deadline wins over a simultaneously ready item',async()=>{const f=fixture();f.shutdown.abort();const pending=f.start();await tick();f.lane.trySend({shard:1,message:'too late'});f.clock.advance(13000);const result=await pending;assert.ok(!result.ok);assert.equal(f.items.length,0);});
test('force cancellation preserves exact private reason and joins pending receive',async()=>{const f=fixture(),reason=new Error('force'),pending=f.start(),rejected=assert.rejects(pending,e=>e===reason);await tick();f.force.abort(reason);await rejected;assert.equal(f.lane.trySend({shard:1,message:'closed'}),'Closed');assert.equal(f.clock.waiting.size,0);});
test('reporting failure preserves original error and disposes the receiver',async()=>{const f=fixture(),error=new Error('report');f.lane.trySend({shard:1,message:'raw'});await assert.rejects(run(f.receiver,f.shutdown.signal,f.force.signal,()=>{throw error;},f.clock),e=>e===error);assert.equal(f.lane.trySend({shard:1,message:'closed'}),'Closed');});
test('continuous diagnostics yield so force cancellation is observed with exact reason',{timeout:3000},async()=>{const f=fixture(),reason=new Error('stop busy loop');let calls=0;f.lane.trySend({shard:1,message:'again'});const pending=run(f.receiver,f.shutdown.signal,f.force.signal,item=>{calls++;f.lane.trySend(item);},f.clock),rejected=assert.rejects(pending,e=>e===reason);setImmediate(()=>f.force.abort(reason));await rejected;assert.ok(calls>=1&&calls<=64);assert.equal(f.lane.trySend({shard:1,message:'closed'}),'Closed');});
test('native timer failure still joins pending read and disposes receiver',async()=>{const f=fixture(),error=new Error('clock');f.shutdown.abort();await assert.rejects(run(f.receiver,f.shutdown.signal,f.force.signal,()=>{},{now:()=>0,sleepUntil:async()=>{throw error;}}),e=>e===error);assert.equal(f.lane.trySend({shard:1,message:'closed'}),'Closed');});
test('typed ingress errors preserve exact pinned display strings',()=>{assert.equal(new RuntimeTypedIngressError('Closed','receive-error').message,'Discord typed ingress receive-error channel closed before shutdown');assert.equal(new RuntimeTypedIngressError('DrainTimeout','receive-error').message,'Discord typed ingress receive-error shutdown drain exceeded its deadline');});
