import test from 'node:test';import assert from 'node:assert/strict';
import {waitRuntimeShutdownCause,type RuntimeShutdownWatchPorts} from '../../../src/runtime/discord-runtime/shutdown-watch.ts';
import {coordinateRuntimeCleanup,type RuntimeCleanupPorts} from '../../../src/runtime/discord-runtime/cleanup-coordinator.ts';
import {DrainFenceKey} from '../../../src/admission/owned-key.ts';
import {RuntimeMonitoredWorker,RuntimeWorkerExitChannel} from '../../../src/runtime/discord-runtime/monitored-worker.ts';
import {GatewayRuntime} from '../../../src/discord/gateway/runtime.ts';
const wait=(signal:AbortSignal)=>new Promise<never>((_r,reject)=>{if(signal.aborted)reject(signal.reason);else signal.addEventListener('abort',()=>reject(signal.reason),{once:true});});
function ports(o:Partial<RuntimeShutdownWatchPorts>={}):RuntimeShutdownWatchPorts{return {control:wait,workerExit:wait,gatewayExit:wait,...o};}
test('control Shutdown and exact Drained key select successful control while cancelling other reads',async()=>{for(const drained of [false,true]){const key=DrainFenceKey.create('runtime','123|456','nonce');const r=await waitRuntimeShutdownCause(ports({control:async()=>drained?{kind:'Drained',key}:{kind:'Shutdown'}}),new AbortController().signal);assert.deepEqual(r.cause,{kind:'Control',result:{ok:true}});assert.equal(r.drainKey,drained?key:null);assert.deepEqual(r.secondaryWatchErrors,[]);}});
test('worker, shard and closed monitors are distinct shutdown causes',async()=>{for(const [field,value,expected] of [['workerExit','queue',{kind:'Worker',worker:'queue'}],['workerExit',null,{kind:'WorkerMonitorClosed'}],['gatewayExit',2,{kind:'GatewayShard',shard:2}],['gatewayExit',null,{kind:'GatewayMonitorClosed'}]] as const){const r=await waitRuntimeShutdownCause(ports({[field]:async()=>value}),new AbortController().signal);assert.deepEqual(r.cause,expected);assert.equal(r.drainKey,null);}});
test('winning failure retains raw identity and unexpected losing error remains separate',async()=>{const primary={},secondary={};const r=await waitRuntimeShutdownCause(ports({control:async()=>{throw primary;},workerExit:async()=>{throw secondary;}}),new AbortController().signal);assert.equal(r.cause.kind,'Control');if(r.cause.kind==='Control'&&!r.cause.result.ok)assert.equal(r.cause.result.error,primary);assert.deepEqual(r.secondaryWatchErrors,[secondary]);});
test('selection cancels but waits for actual losing control finally to finish',async()=>{let started=false,aborted=false,done=false,release!:()=>void;const blocked=new Promise<void>(r=>{release=r;});const task=waitRuntimeShutdownCause(ports({control:async s=>{started=true;s.addEventListener('abort',()=>{aborted=true;},{once:true});await blocked;return {kind:'Shutdown'};},workerExit:async()=> 'worker'}),new AbortController().signal).then(r=>{done=true;return r;});await new Promise(r=>setImmediate(r));assert.equal(started,true);assert.equal(aborted,true);assert.equal(done,false);release();assert.deepEqual((await task).cause,{kind:'Worker',worker:'worker'});});
test('explicit stop is normal shutdown and joins every active watcher',async()=>{const a=new AbortController();let cleaned=0;const run=async(s:AbortSignal)=>{try{return await wait(s);}finally{cleaned++;}};const task=waitRuntimeShutdownCause({control:run,workerExit:run,gatewayExit:run},a.signal);await new Promise(r=>setImmediate(r));a.abort(new Error('stop'));const r=await task;assert.deepEqual(r.cause,{kind:'Control',result:{ok:true}});assert.equal(cleaned,3);});
test('prestop starts no watcher and consumed port cannot be reused',async()=>{let calls=0;const p=ports({control:async()=>{calls++;return {kind:'Shutdown'};}}),a=new AbortController();a.abort();assert.deepEqual((await waitRuntimeShutdownCause(p,a.signal)).cause,{kind:'Control',result:{ok:true}});assert.equal(calls,0);await assert.rejects(waitRuntimeShutdownCause(p,a.signal),/consumed/);});
test('malformed control key or exit identity becomes failed control, never Drained',async()=>{for(const p of [ports({control:async()=>({kind:'Drained',key:{} as never})}),ports({workerExit:async()=>123 as never}),ports({gatewayExit:async()=>-1})]){const r=await waitRuntimeShutdownCause(p,new AbortController().signal);assert.equal(r.drainKey,null);assert.ok(r.cause.kind==='Control'&&!r.cause.result.ok);}});
test('active port getters are rejected without execution',async()=>{let called=0;const p=ports();Object.defineProperty(p,'control',{get(){called++;return wait;}});await assert.rejects(waitRuntimeShutdownCause(p,new AbortController().signal),TypeError);assert.equal(called,0);});
test('actual worker exit cancels native gateway exit read without shutting down that owner early',async()=>{const notifier=new RuntimeWorkerExitChannel(),receiver=notifier.receiver(),worker=new RuntimeMonitoredWorker('real-worker',notifier,async()=>({ok:true}));notifier.close();const gateway=GatewayRuntime.fromOwnedPorts([{shardId:4,nextEvent:async()=>null,requestNormalClose(){},dispose:async()=>{}}],{reportTriggerFailure(){},reportReceiveErrorDrop(){}});try{const r=await waitRuntimeShutdownCause({control:wait,workerExit:s=>receiver.receive(s),gatewayExit:s=>gateway.waitForShardExit(s)},new AbortController().signal);assert.deepEqual(r.cause,{kind:'Worker',worker:'real-worker'});assert.ok(worker.peek());assert.equal(gateway.resourcesClosed,false);const a=new AbortController();a.abort();await assert.rejects(gateway.waitForShardExit(a.signal),e=>e===a.signal.reason);}finally{receiver.dispose();await gateway.shutdown();await worker.join();}});
test('cleanup retains original selection deadline instead of resetting after watcher join',async()=>{const deadlines:number[]=[];const ok={ok:true} as const,report={trigger:null,cleanup:ok};const clock={now:()=>11000,sleepUntil:(_d:number,s:AbortSignal)=>wait(s)};const p:RuntimeCleanupPorts={requestRemoteHandoff:async()=>{},beginGatewayStopping(){},closeInteractionInput(){},signalWorkers(){},joinGateway:async d=>{deadlines.push(d);return report;},joinWorkers:async d=>{deadlines.push(d);return report;},closeServer:async()=>{},completeDrain:async()=> 'Stop',signalHeartbeat(){},joinHeartbeat:async d=>{deadlines.push(d);return ok;}};await coordinateRuntimeCleanup({kind:'Control',result:ok},null,p,{clock,startedAt:1000});assert.deepEqual(deadlines,[16000,16000,31000]);});
