import test from 'node:test';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {createInterface} from 'node:readline';
const moduleUrl=new URL('../../../src/runtime/discord-runtime/stop-signal.ts',import.meta.url).href;
async function childRun(body:string):Promise<string>{const child=spawn(process.execPath,['--input-type=module','-e',`import assert from 'node:assert/strict';import {RuntimeStopSignal} from ${JSON.stringify(moduleUrl)};${body}`],{stdio:['ignore','pipe','pipe']});let output='',error='';child.stdout.on('data',b=>{output+=b;});child.stderr.on('data',b=>{error+=b;});const timer=setTimeout(()=>child.kill('SIGKILL'),5000);try{const code=await new Promise<number|null>((resolve,reject)=>{child.once('error',reject);child.once('exit',resolve);});assert.equal(code,0,error);return output;}finally{clearTimeout(timer);if(child.exitCode===null&&child.signalCode===null){child.kill('SIGKILL');await new Promise(r=>child.once('exit',r));}}}
test('owned signal aborts once with stable reason and preserves unrelated listeners',async()=>{await childRun(`let foreign=0;const other=()=>{foreign++;};process.on('SIGINT',other);const before=process.listenerCount('SIGINT'),owner=RuntimeStopSignal.install();assert.equal(process.listenerCount('SIGINT'),before+1);let observed=0;owner.signal.addEventListener('abort',()=>observed++);process.emit('SIGINT');const reason=owner.signal.reason;process.emit('SIGINT');assert.equal(observed,1);assert.equal(foreign,2);assert.equal(owner.signal.reason,reason);assert.equal(Object.isFrozen(owner),true);owner.dispose();owner.dispose();assert.equal(process.listenerCount('SIGINT'),before);process.removeListener('SIGINT',other);`);});
test('second owner rejects before adding listener, and disposed owner cannot remove replacement',async()=>{await childRun(`const a=RuntimeStopSignal.install(),count=process.listenerCount('SIGINT');assert.throws(()=>RuntimeStopSignal.install(),/already owned/);assert.equal(process.listenerCount('SIGINT'),count);a.dispose();const b=RuntimeStopSignal.install();a.dispose();process.emit('SIGINT');assert.equal(b.signal.aborted,true);assert.equal(a.signal.aborted,false);b.dispose();`);});
test('dispose alone neither aborts signal nor changes another listener',async()=>{await childRun(`const other=()=>{};process.on('SIGINT',other);const a=RuntimeStopSignal.install();a.dispose();assert.equal(a.signal.aborted,false);assert.ok(process.listeners('SIGINT').includes(other));process.removeListener('SIGINT',other);`);});
test('actual POSIX SIGINT to owned inert child requests and completes cooperative cleanup',{skip:process.platform==='win32'?'Windows requires native console Ctrl-C delivery fixture':false},async()=>{
 const code=`import {RuntimeStopSignal} from ${JSON.stringify(moduleUrl)};const owner=RuntimeStopSignal.install();const timer=setInterval(()=>{},1000);owner.signal.addEventListener('abort',()=>{clearInterval(timer);owner.dispose();console.log('CLEANED');});console.log('READY');`;
 const child=spawn(process.execPath,['--input-type=module','-e',code],{stdio:['ignore','pipe','pipe']});const lines=createInterface({input:child.stdout});let errors='';child.stderr.on('data',b=>{errors+=b;});let sent=false,cleaned=false;const timer=setTimeout(()=>child.kill('SIGKILL'),5000);const exit=new Promise<number|null>((resolve,reject)=>{child.once('exit',resolve);child.once('error',reject);});try{for await(const line of lines){if(line==='READY'){sent=child.kill('SIGINT');}if(line==='CLEANED')cleaned=true;}assert.equal(await exit,0,errors);assert.equal(sent,true);assert.equal(cleaned,true);}finally{clearTimeout(timer);lines.close();if(child.exitCode===null&&child.signalCode===null){child.kill('SIGKILL');await exit;}}
});
