import assert from 'node:assert/strict';import {test} from 'node:test';import {setImmediate as tick} from 'node:timers/promises';
import {RuntimeMonitoredWorker,RuntimeWorkerExitChannel,type RuntimeWorkerResult} from '../../../src/runtime/discord-runtime/monitored-worker.ts';
import {joinRuntimeWorkersForCause as join,RuntimeWorkerTaskError,RuntimeWorkerTimeoutError,RuntimeWorkerReportingError} from '../../../src/runtime/discord-runtime/worker-shutdown.ts';
class Clock{time=0;waiting=new Set<{at:number;wake:()=>void}>();now=()=>this.time;sleepUntil=(at:number,signal:AbortSignal):Promise<void>=>{signal.throwIfAborted();if(at<=this.time)return Promise.resolve();return new Promise((resolve,reject)=>{const item={at,wake:()=>{clean();resolve();}},clean=()=>{this.waiting.delete(item);signal.removeEventListener('abort',abort);},abort=()=>{clean();reject(signal.reason);};this.waiting.add(item);signal.addEventListener('abort',abort,{once:true});});};advance(at:number){this.time=at;for(const item of [...this.waiting])if(item.at<=at)item.wake();}}
function fixture(name:string,obey=true,onAbort=()=>{}){const exits=new RuntimeWorkerExitChannel();let finish!:(r:RuntimeWorkerResult)=>void,fail!:(e:unknown)=>void;const worker=new RuntimeMonitoredWorker(name,exits,signal=>new Promise((resolve,reject)=>{const clean=()=>signal.removeEventListener('abort',abort),abort=()=>{onAbort();if(obey){clean();reject(signal.reason);}};finish=r=>{clean();resolve(r);};fail=e=>{clean();reject(e);};signal.addEventListener('abort',abort,{once:true});}));exits.close();return {worker,finish:(r:RuntimeWorkerResult={ok:true})=>finish(r),fail:(e:unknown)=>fail(e)};}
function options(){const clock=new Clock(),fatal=new Error('fatal'),reports:unknown[][]=[];return {clock,fatal,reports,value:{clock,report:(...args:unknown[])=>{reports.push(args);},fatal:()=>{throw fatal;}}};}
test('empty set and absent trigger yield clean report without timers',async()=>{const o=options();assert.deepEqual(await join([],2000,'absent',o.value),{trigger:null,cleanup:{ok:true}});assert.equal(o.clock.waiting.size,0);});
test('trigger returned error remains separate from earlier cleanup error and input is consumed',async()=>{const o=options(),a=fixture('cleanup'),b=fixture('trigger'),primary=new Error('primary'),secondary=new Error('cleanup');await tick();a.finish({ok:false,error:secondary});b.finish({ok:false,error:primary});const input=[a.worker,b.worker],result=await join(input,2000,'trigger',o.value);assert.deepEqual(input,[]);assert.deepEqual(result,{trigger:{ok:false,error:primary},cleanup:{ok:false,error:secondary}});assert.equal(o.reports[0]![0],'primary');});
test('thrown failure is wrapped with exact worker and cause identity',async()=>{const o=options(),f=fixture('panic'),error=new Error('panic');await tick();f.fail(error);const result=await join([f.worker],2000,null,o.value);assert.ok(!result.cleanup.ok);assert.ok(result.cleanup.error instanceof RuntimeWorkerTaskError);assert.equal(result.cleanup.error.taskError,error);assert.equal(result.cleanup.error.worker,'panic');});
test('all remaining workers abort before any forced join and timeout preserves names',async()=>{const o=options(),aborts:string[]=[],a=fixture('a',true,()=>aborts.push('a')),b=fixture('b',true,()=>aborts.push('b'));await tick();const pending=join([a.worker,b.worker],2000,null,o.value);await tick();o.clock.advance(1000);const result=await pending;assert.deepEqual(aborts,['a','b']);assert.ok(!result.cleanup.ok);assert.ok(result.cleanup.error instanceof RuntimeWorkerTimeoutError);assert.equal(result.cleanup.error.workers,'a,b');assert.equal(o.clock.waiting.size,0);});
test('first returned error wins over later forced timeout but every task joins',async()=>{const o=options(),a=fixture('failed'),b=fixture('stuck'),error=undefined;await tick();a.finish({ok:false,error});const pending=join([a.worker,b.worker],2000,null,o.value);await tick();o.clock.advance(1000);assert.deepEqual((await pending).cleanup,{ok:false,error});assert.notEqual(b.worker.peek(),undefined);assert.equal(o.reports.at(-1)![0],'timeout');});
test('abort-resistant callback reaches fatal sentinel without fabricated completion',async()=>{const o=options(),f=fixture('resistant',false);await tick();const pending=join([f.worker],2000,null,o.value),rejected=assert.rejects(pending,e=>e===o.fatal);try{await tick();o.clock.advance(1000);await tick();o.clock.advance(2000);await rejected;assert.equal(f.worker.peek(),undefined);}finally{f.finish();await f.worker.join();}});
test('diagnostic failure is deferred until actual remaining cleanup',async()=>{const o=options(),a=fixture('trigger'),b=fixture('cleanup'),error=new Error('report');await tick();a.finish({ok:false,error:new Error('primary')});const pending=join([a.worker,b.worker],2000,'trigger',{...o.value,report:()=>{throw error;}}),rejected=assert.rejects(pending,e=>e instanceof RuntimeWorkerReportingError&&e.reportingError===error);await tick();b.finish();await rejected;assert.notEqual(b.worker.peek(),undefined);});
test('duplicate owners reject before ownership transfer',async()=>{const o=options(),f=fixture('same');await tick();const input=[f.worker,f.worker];await assert.rejects(join(input,2000,null,o.value),/unique/);assert.equal(input.length,2);f.finish();await f.worker.join();});
test('overridden array splice cannot substitute or discard actual task owners',async()=>{const o=options(),f=fixture('owned');await tick();f.finish();const input=[f.worker];Object.defineProperty(input,'splice',{value:()=>{throw new Error('untrusted splice');}});assert.deepEqual(await join(input,2000,null,o.value),{trigger:null,cleanup:{ok:true}});assert.equal(input.length,0);});
