import {it} from 'node:test';import assert from 'node:assert/strict';import {createServer} from 'node:http';
import {abandonmentStoreFixture} from '../../helpers/abandonment-store-fixture.ts';import {work} from '../../helpers/interaction-worker-fixture.ts';import {AdmissionGate} from '../../../src/admission/drain-gate.ts';import {TargetLocks} from '../../../src/core/keyed-locks.ts';import {ControlTurnVerifier} from '../../../src/runtime/action-executor/control-turn.ts';import {createOrdinaryComponentHandler} from '../../../src/runtime/component-worker/ordinary-handler.ts';import {componentWorkerErrorInfo} from '../../../src/runtime/component-worker/errors.ts';import {proposeAbandonment,bindAbandonmentDelivery} from '../../../src/store/abandonment-proposal.ts';import {serializeSerdeValue} from '../../../src/core/serde-json.ts';import {DiscordChannelClient} from '../../../src/discord/channel-client.ts';
const proposal='c'.repeat(32),job='550e8400-e29b-41d4-a716-446655440000';
it('abandonment confirmation shares one ten-second deadline across POST and clear, keeps confirmed receipt and never replays disposition',{timeout:30000},async()=>abandonmentStoreFixture(async(db,path)=>{
 const now=Date.now()/1000,p=proposeAbandonment(path,{proposal_id:proposal,job_id:job,ingress_id:'message:5',application_id:4n,now,expires_at:now+120});bindAbandonmentDelivery(path,proposal,9n,p.review_sha256,now);
 const w=work(path,6n,new AdmissionGate(),`codex_discard:v1:${proposal}:1:a`),v=new ControlTurnVerifier(path,null,{selectedThreadId:()=>null},new TargetLocks());db.prepare("INSERT INTO discord_ingress_journal(ingress_id,kind,event_id,application_id,channel_id,owner_user_id,source_message_id,payload_json,runtime_id,state,phase,target_thread_id,created_at,updated_at) VALUES('interaction:6','interaction',6,4,1,2,9,?,'app','executing','processing','t',?,?)").run(serializeSerdeValue({version:1n,work:w.work}),now,now);
 const seen:string[]=[],timers=new Set<ReturnType<typeof setTimeout>>();let recovery=false;const local=createServer((req,res)=>{req.resume();req.on('end',()=>{seen.push(req.method!);const complete=()=>{if(req.method==='PATCH'){res.statusCode=204;res.end();}else res.end(JSON.stringify({attachments:[],author:{id:'1',username:'u',discriminator:'0'},channel_id:'1',content:'',embeds:[],id:'100',type:0,mention_everyone:false,mention_roles:[],mentions:[],pinned:false,timestamp:'2020-01-01T00:00:00+00:00',tts:false}));};if(recovery)complete();else {const timer=setTimeout(()=>{timers.delete(timer);complete();},req.method==='POST'?6000:8000);timers.add(timer);res.once('close',()=>{clearTimeout(timer);timers.delete(timer);});}});});await new Promise<void>(r=>local.listen(0,'127.0.0.1',r));const http=await DiscordChannelClient.create({token:null,testOrigin:`http://127.0.0.1:${(local.address() as {port:number}).port}/api/v10/`,report:()=>{}});
 try{assert.ok('Component'in w.work);const prepared=await createOrdinaryComponentHandler(path,null as never,http,null as never,v,()=>{assert.fail('must not enqueue');})(w,w.work.Component),started=performance.now();await assert.rejects(prepared.deliver(),e=>componentWorkerErrorInfo(e)?.kind==='AbandonmentNotice');assert.ok(performance.now()-started>=9000);assert.ok(performance.now()-started<14000);assert.deepEqual(seen,['POST','PATCH']);assert.equal(http.activeRequests,0);assert.equal(db.prepare('SELECT count(*) AS n FROM cdr_recovery_abandonment_decisions').get()!.n,1);assert.equal(db.prepare('SELECT count(*) AS n FROM codex_turn_queue').get()!.n,0);assert.equal(db.prepare('SELECT count(*) AS n FROM codex_delivery_receipts WHERE message_id IS NOT NULL').get()!.n,1);
  recovery=true;await prepared.deliver();assert.deepEqual(seen,['POST','PATCH','PATCH']);assert.equal(db.prepare('SELECT count(*) AS n FROM cdr_recovery_abandonment_decisions').get()!.n,1);
 }finally{w.admissionPermit!.release();for(const timer of timers)clearTimeout(timer);await http.close();local.closeAllConnections();await new Promise<void>((r,j)=>local.close(e=>e?j(e):r()));assert.equal(http.activeRequests,0);assert.equal(http.ownedSockets,0);}
},true,job));
