import test from 'node:test';import assert from 'node:assert/strict';import type {DatabaseSync} from 'node:sqlite';
import {storeFixture} from '../../helpers/store-fixture.ts';import {openInitialized} from '../../../src/store/owned-driver.ts';import {selectDelivery,type StoredDelivery} from '../../../src/store/delivery.ts';
import {deliverFinal,type FinalDeliveryOptions} from '../../../src/runtime/completion/final-delivery.ts';import {splitDeliveryChunks} from '../../../src/discord/text.ts';import {receiptHash} from '../../../src/store/delivery-receipt-key.ts';import {serializeSerdeValue} from '../../../src/core/serde-json.ts';
async function edit<T>(path:string,run:(db:DatabaseSync)=>T):Promise<T>{const db=await openInitialized(path);try{return run(db);}finally{db.close();}}
async function seed(path:string,body='x'.repeat(2100)){return edit(path,db=>{db.prepare("INSERT INTO codex_delivery_outbox(delivery_id,job_id,target_thread_id,turn_id,channel_id,content,created_at,updated_at) VALUES('d','job','t','v',42,?,1,1)").run(body);return selectDelivery(db,'d');});}
async function confirm(path:string,p:StoredDelivery,limit=Infinity){await edit(path,db=>{for(const[i,c]of splitDeliveryChunks(p.content,true).entries())if(i<limit)db.prepare('INSERT INTO codex_delivery_receipts(receipt_key,content_hash,message_id) VALUES(?,?,?)').run(serializeSerdeValue([42n,'completion/v1','d',BigInt(i)]),receiptHash(c),String(100+i));});}
const options=(send:FinalDeliveryOptions['transport']['sendValidated']):FinalDeliveryOptions=>({transport:{sendValidated:send},failures:{render:()=> 'safe failure'},now:()=>123});
test('confirmed runtime fast path retires without transport, failure clock or ordinary second delete',async()=>storeFixture(async path=>{const p=await seed(path);await confirm(path,p);await deliverFinal(path,p,{transport:{async sendValidated(){assert.fail('confirmed receipt must not POST');}},failures:{render(){assert.fail('must not record failure');}},now(){assert.fail('must not sample failure time');}});assert.equal(await edit(path,db=>db.prepare('SELECT count(*) n FROM codex_delivery_outbox').get()?.n),0);assert.equal(await edit(path,db=>db.prepare('SELECT count(*) n FROM codex_delivery_receipts').get()?.n),2);}));
test('partial confirmed prefix rolls back tentative last intent before ordinary fallback sends only missing chunk',async()=>storeFixture(async path=>{const p=await seed(path);await confirm(path,p,1);const sent:string[]=[];await deliverFinal(path,p,options(async request=>{sent.push(JSON.parse(request.body).content);return 201n;}));assert.deepEqual(sent,[splitDeliveryChunks(p.content,true)[1]]);assert.equal(await edit(path,db=>db.prepare('SELECT count(*) n FROM codex_delivery_outbox').get()?.n),0);}));
test('another worker already retired outbox retains ordinary confirmed-receipt fallback without POST',async()=>storeFixture(async path=>{const p=await seed(path);await confirm(path,p);await edit(path,db=>db.exec('DELETE FROM codex_delivery_outbox'));await deliverFinal(path,p,options(async()=>{assert.fail('no duplicate POST after concurrent cleanup');}));assert.equal(await edit(path,db=>db.prepare('SELECT count(*) n FROM codex_delivery_receipts').get()?.n),2);}));
test('confirmed fast-path SQL failure records source failure and retains original outbox',async()=>storeFixture(async path=>{const p=await seed(path);await confirm(path,p);await edit(path,db=>db.exec("CREATE TRIGGER reject_retire BEFORE DELETE ON codex_delivery_outbox BEGIN SELECT RAISE(ABORT,'native retire failure'); END"));await assert.rejects(deliverFinal(path,p,options(async()=>{assert.fail('no POST');})),/native retire failure/);const after=await edit(path,db=>selectDelivery(db,'d'));assert.equal(after.attemptCount,1n);assert.equal(after.updatedAt,123);assert.equal(after.lastError,'safe failure');}));
test('stale attempt counters cannot directly retire but safely fall back to confirmed normal path',async()=>storeFixture(async path=>{const p=await seed(path);await confirm(path,p);await edit(path,db=>db.exec("UPDATE codex_delivery_outbox SET attempt_count=7,last_error='later attempt'"));await deliverFinal(path,p,options(async()=>{assert.fail('all receipts remain confirmed');}));assert.equal(await edit(path,db=>db.prepare('SELECT count(*) n FROM codex_delivery_outbox').get()?.n),0);}));
